- id: trie-verify
  name: trie verify
  description: Verify the trie doc tree is coherent with the source code.
  entry: trie -q verify
  language: python
  pass_filenames: false
  always_run: true
  stages: [pre-commit]
