"""AGM (Attention Gravity Map) contracts: the shared vocabulary for modelling
agent attention as a field over the symbol graph.

This module is the single source of truth for the *constants and shapes* the
Attention Gravity Map is built on. It deliberately holds no behaviour beyond
pure mappings/derivations — the live simulation runs in the desktop app, the
durable fold runs in `trie.sync`, and the capture path runs in the opencode
fork. All three import their numbers from here (the TypeScript side mirrors
these values; keep them in sync).

## The two masses (do not conflate)

There is no single "mass". AGM tracks two distinct quantities with different
homes, cadences, and meanings:

- **Live mass** — the in-memory session signal. A per-event field decayed
  continuously by wall-clock time (no ticks). Drives the visual: gravity,
  centroid, role rollups, investigations. Never persisted. Computed as

      live_mass(q, now) = Σ_e weight(type_e) · exp(-λ(type_e) · (now - ts_e))

  over every attention event `e` on symbol `q`, with per-event-type half-lives.

- **Historical mass** — a long-term *cognitive importance* signal stamped into
  the triefact sentinel (`hist_mass=<v>@<ts>`), updated only when a symbol's
  triefact is regenerated by `trie sync`, decayed on a 21-day half-life. It is
  NOT "old live mass": it answers *"how often does agent cognition return here
  across investigations?"* The sync-time fold increments it by the count of
  DISTINCT investigations that drew attention to the symbol since the last sync.

Both are logarithmically compressed for display (`display_mass`); raw values
grow unbounded, rendered values must not.

## Truthfulness

Mass is observation, not judgement. There is intentionally NO per-symbol
dampening by role/class/hub. If the agent spends attention on a utility, the
utility gets the mass. Correction for plumbing happens in propagation,
visibility, aggregation, and layout — never in mass itself.
"""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import Literal

# ---------------------------------------------------------------------------
# Event types + weights
# ---------------------------------------------------------------------------

# The cognitive stages an agent moves through, in increasing commitment:
#   grep  — exploration   ("this might matter")
#   read  — commitment    ("this is worth understanding")
#   trace — explanation   ("this explains something important")
#   write — modification  (patch / file edit)
EventType = Literal["grep", "read", "trace", "write"]

# Per-event live-mass weights (PRD §Event Interpretation). `write` shares
# `trace`'s magnitude: editing a symbol is the strongest possible commitment.
EVENT_WEIGHTS: dict[EventType, int] = {
    "grep": 10,
    "read": 40,
    "trace": 80,
    "write": 80,
}

# Per-event-type live half-lives (seconds). Exploration cools fast; explanation
# and edits stay warm far longer. Decay is continuous: λ = ln2 / half_life.
LIVE_HALFLIFE_SECONDS: dict[EventType, float] = {
    "grep": 30.0,
    "read": 180.0,
    "trace": 600.0,
    "write": 600.0,
}

# Historical mass half-life: cross-session cognitive memory on a multi-week
# horizon. A symbol revisited across investigations stays warm for weeks; one
# touched once and abandoned decays away.
HISTORICAL_HALFLIFE_SECONDS: float = 21.0 * 24.0 * 60.0 * 60.0


def live_lambda(event_type: EventType) -> float:
    """Continuous-decay rate λ for a live event type (1/seconds)."""
    return math.log(2.0) / LIVE_HALFLIFE_SECONDS[event_type]


HISTORICAL_LAMBDA: float = math.log(2.0) / HISTORICAL_HALFLIFE_SECONDS


def display_mass(raw_mass: float) -> float:
    """Logarithmic compression for rendering. Raw mass grows unbounded; the
    displayed value must stay bounded so long-lived systems remain readable."""
    return math.log(max(0.0, raw_mass) + 1.0)


# ---------------------------------------------------------------------------
# Tool → event-type classification
# ---------------------------------------------------------------------------

# Every trie MCP tool (and the file-edit tools) maps to exactly one attention
# event type, or to None when the tool carries no symbol-level attention (it is
# routed to a synthetic node instead — see SYNTHETIC_NODES). The opencode
# capture path and the desktop app both classify by this table; keep it aligned
# with the registered tool set in `trie.mcp_server`.
TOOL_EVENT_TYPE: dict[str, EventType | None] = {
    # read intent — commitment of context budget
    "read": "read",
    "read_source": "read",
    "explain_symbol": "read",
    "explain_symbol_references": "read",
    # trace intent — causal reasoning over the graph
    "trace": "trace",
    "trace_flow": "trace",
    "explain_flow": "trace",
    # scan / exploration intent (grep family)
    "grep": "grep",
    "grep_str": "grep",
    "grep_str_all": "grep",
    "grep_symbol": "grep",
    "grep_entry_points": "grep",
    "grep_symbol_and_neighbours": "grep",
    "find_files": "grep",
    # write intent — modification
    "patch": "write",
    "create_symbol": "write",
    "rename_symbol": "write",
    "delete_symbol": "write",
    "write_file": "write",
    "commit": "write",
    "patch_apply": "write",
    # navigation / bookkeeping tools carry no symbol attention
    "summary": None,
    "patch_list": None,
    "patch_drop": None,
    "preview": None,
    "blast_radius": None,
    "symbols_by_file": None,
    "file_triefact": None,
    "all_symbols": None,
    "all_edges": None,
    "system_model": None,
    "activity": None,
}


def classify_tool(tool: str) -> EventType | None:
    """Map a tool name (with or without the `trie_` MCP prefix) to an event
    type, or None when it carries no symbol-level attention.

    Unknown tools default to None — an unrecognised tool should never silently
    inject attention. File-edit tools from non-trie surfaces are matched on
    their bare names so the desktop and the fork agree.
    """
    bare = tool[5:] if tool.startswith("trie_") else tool
    return TOOL_EVENT_TYPE.get(bare, _DEFAULT_TOOL_EVENTS.get(bare))


# Bare-name fallbacks for file-edit tools an agent harness may expose under
# names other than trie's own (e.g. opencode's `edit` / `write`).
_DEFAULT_TOOL_EVENTS: dict[str, EventType | None] = {
    "edit": "write",
    "write": "write",
    "str_replace_editor": "write",
}


# ---------------------------------------------------------------------------
# Edge kinds + propagation weights
# ---------------------------------------------------------------------------

# Repository-graph edge kinds (possible relationships). Derived from the Python
# AST at parse time. `depends_on` from the PRD is intentionally deferred — it
# has no AST construct to extract from, and fabricating it would inject
# hallucinated topology, violating the truthfulness principle.
RepoEdgeKind = Literal[
    "calls",
    "references",
    "imports",
    "contains",
    "inherits",
    "implements",
]

# The attention graph (actual reasoning paths) is a separate graph carrying a
# single kind: `trace`. A trace EVENT creates trace EDGES between the symbols
# the agent moved between.
ATTENTION_EDGE_KIND: str = "trace"

# Default edge kind for legacy/ambiguous edges (pre-typed-edge rows render as
# plain calls until regenerated).
DEFAULT_EDGE_KIND: RepoEdgeKind = "calls"

# Propagation weights per edge kind (PRD §Edge Weights). Attention spreads ONE
# hop, weakly: neighbour_gain = source_heat · edge_weight · PROPAGATION_FACTOR.
# Multi-hop propagation hallucinates attention, so the simulation caps at one
# hop. Propagated heat is transient and never contributes to historical mass.
EDGE_WEIGHTS: dict[str, float] = {
    "trace": 1.0,
    "calls": 1.0,
    "inherits": 0.9,
    "implements": 0.8,
    "references": 0.7,
    "imports": 0.5,
    "contains": 0.2,
}

PROPAGATION_FACTOR: float = 0.15
PROPAGATION_HOPS: int = 1


def edge_weight(kind: str) -> float:
    """Propagation weight for an edge kind; unknown kinds fall back to `calls`."""
    return EDGE_WEIGHTS.get(kind, EDGE_WEIGHTS["calls"])


# ---------------------------------------------------------------------------
# Synthetic nodes (non-code cognition surfaces)
# ---------------------------------------------------------------------------

# A large fraction of agent cognition happens outside indexed code. These
# synthetic nodes give that attention a home so the visualisation is not
# systematically misleading. They live entirely in the AGM layer — never in the
# `symbols` table (which requires a real file path + line range) and never in
# triefacts. Their historical mass is reconstructed best-effort from the
# compressed event store.
SyntheticNode = Literal["Filesystem", "Bash", "Web", "Database", "Git"]

SYNTHETIC_NODES: tuple[SyntheticNode, ...] = (
    "Filesystem",
    "Bash",
    "Web",
    "Database",
    "Git",
)

# Synthetic qnames use a reserved scheme so they never collide with real
# symbols (which always contain a `:`), and so the desktop can recognise them.
SYNTHETIC_QNAME_PREFIX: str = "agm:synthetic/"


def synthetic_qname(node: SyntheticNode) -> str:
    """Reserved qname for a synthetic node, e.g. `agm:synthetic/Filesystem`."""
    return f"{SYNTHETIC_QNAME_PREFIX}{node}"


def is_synthetic_qname(qname: str) -> bool:
    return qname.startswith(SYNTHETIC_QNAME_PREFIX)


# Tools whose attention should be routed to a synthetic node instead of (or in
# addition to) a symbol. Maps a bare tool name to its synthetic surface.
TOOL_SYNTHETIC_NODE: dict[str, SyntheticNode] = {
    "read_source": "Filesystem",
    "write_file": "Filesystem",
    "find_files": "Filesystem",
    "grep_str_all": "Filesystem",
}


def classify_synthetic(tool: str) -> SyntheticNode | None:
    """Synthetic node a tool's attention belongs to, if any."""
    bare = tool[5:] if tool.startswith("trie_") else tool
    return TOOL_SYNTHETIC_NODE.get(bare)


# ---------------------------------------------------------------------------
# AttentionEvent — the unit captured at every tool call
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class AttentionEvent:
    """One unit of agent attention on a target, captured at a tool call.

    `target` is a symbol qname or a synthetic qname (see `synthetic_qname`).
    `ts` is a unix timestamp (seconds, float). `weight` is denormalised from
    `event_type` at capture time so the store doesn't need the weight table to
    replay. Everything is keyed by agent/session/investigation so the model can
    attribute attention correctly and support multi-agent later.
    """

    ts: float
    event_type: EventType
    target: str
    weight: int
    agent_id: str = ""
    session_id: str = ""
    investigation_id: str = ""

    @classmethod
    def make(
        cls,
        *,
        ts: float,
        event_type: EventType,
        target: str,
        agent_id: str = "",
        session_id: str = "",
        investigation_id: str = "",
    ) -> AttentionEvent:
        """Build an event, filling `weight` from the canonical table."""
        return cls(
            ts=ts,
            event_type=event_type,
            target=target,
            weight=EVENT_WEIGHTS[event_type],
            agent_id=agent_id,
            session_id=session_id,
            investigation_id=investigation_id,
        )


# ---------------------------------------------------------------------------
# Investigations
# ---------------------------------------------------------------------------

# Investigations are first-class, explicitly-created entities representing a
# user task — the meaningful unit of continuity (NOT turns). They are never
# inferred from graph clustering. Lifecycle is agent/user-declared.
InvestigationStatus = Literal["active", "resolved", "abandoned", "superseded"]

INVESTIGATION_STATUSES: tuple[InvestigationStatus, ...] = (
    "active",
    "resolved",
    "abandoned",
    "superseded",
)


@dataclass(frozen=True)
class Investigation:
    """An explicit investigation: a labelled span of agent cognition.

    `label` comes from the user prompt first, an LLM summary second — never
    graph-derived. Confidence (a measure of attention concentration, 0..1) and
    the symbol scope are derived live in the desktop app; this record is the
    durable identity the event store keys against.
    """

    id: str
    label: str
    status: InvestigationStatus = "active"
    created_at: float = 0.0
    agent_id: str = ""
    session_id: str = ""
