"""Project-local agent documentation install.

Companion to `mcp_install.py` and `hook_install.py`. Where `mcp_install`
makes trie available to an agent and `hook_install` makes it automatic,
this module makes trie *visible* — it materialises `TRIE.md` at the
project root and appends one marker-fenced line to `AGENTS.md` and
`CLAUDE.md` pointing agents at it.

Why two layers (the doc file plus the pointer line):

  - The pointer line is what guarantees discovery. Agents reliably read
    `AGENTS.md` / `CLAUDE.md`; a doc that only exists at `TRIE.md` won't
    be found unless something in the auto-loaded context names it.
  - The full guide lives in its own file rather than being inlined so it
    can be long enough to be useful (predicate fields, worked examples,
    error shapes) without bloating the agent's context budget for every
    unrelated query.

Both writes are idempotent. The marker fences match the pattern used by
the pre-commit hook installer — re-runs replace only the block between
the markers, leaving the rest of the user's file alone. `TRIE.md` is
treated as a generated artefact: a leading comment in the file says so,
and re-runs overwrite it unconditionally.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from importlib import resources
from pathlib import Path
from typing import Literal

from trie.mcp_install import TARGETS as MCP_TARGETS

Action = Literal["created", "updated", "skipped", "preview", "error"]


class DocsInstallError(Exception):
    pass


# Marker fences for the pointer line in AGENTS.md / CLAUDE.md. We keep
# them HTML-comment-shaped so the rendered Markdown ignores them; the
# install routine only ever rewrites the block between MARKER and
# END_MARKER, never anything outside.
POINTER_MARKER = "<!-- trie:docs (added by `trie setup`) -->"
POINTER_END_MARKER = "<!-- end trie:docs -->"


def _pointer_line(grep_name: str, read_name: str, trace_name: str) -> str:
    """Build the pointer line that nudges agents toward the trie tools.

    The literal tool names are baked in at install time so an agent reading
    AGENTS.md (or CLAUDE.md) sees the exact names its harness will surface,
    not the trie-internal canonical names. Default values are the unprefixed
    forms — what an agent would see if it inspected MCP tools directly with
    no harness prefix.
    """
    return (
        "**trie is installed in this project.** "
        "Read [TRIE.md](TRIE.md) for the navigation tools "
        f"(`{grep_name}`, `{read_name}`, `{trace_name}`) — use them "
        "instead of grep for code search."
    )


# Default pointer line, rendered with the bare (unprefixed) tool names.
# `_apply_pointer` re-renders this per-target when a target is provided.
POINTER_LINE = _pointer_line("grep", "read", "trace")
POINTER_BLOCK = f"{POINTER_MARKER}\n{POINTER_LINE}\n{POINTER_END_MARKER}\n"

# Files we'll touch at the project root. Both are written when present;
# missing files are NOT auto-created — agent doc files are user-owned
# territory and conjuring one out of thin air feels presumptuous. The
# `TRIE.md` file itself is the trie-owned artefact.
AGENT_DOC_FILES: tuple[str, ...] = ("AGENTS.md", "CLAUDE.md")

# Name of the project-local doc we write. Capitalised for visibility
# alongside README / AGENTS / CLAUDE / CONTRIBUTING. The leading
# generated-file notice goes inside; everything below it is the
# canonical content from `trie/data/TRIE.md`.
TRIE_DOC_FILENAME = "TRIE.md"

# Comment block prepended to TRIE.md so a curious reader knows where it
# came from and that hand-edits won't survive `trie setup`. Markdown
# treats the HTML comment as invisible; the heading below it is what
# the reader sees first.
_GENERATED_NOTICE = (
    "<!-- Generated by `trie setup`. Re-run that command to update. "
    "Hand-edits will be overwritten. -->\n\n"
)


@dataclass(frozen=True)
class DocsApplyResult:
    """Outcome of one file operation during docs install.

    A single `trie setup` invocation produces several of these — one for
    `TRIE.md`, and one each for the agent doc files we touched. The CLI
    renderer groups them under a single "docs" heading.
    """

    target: str
    action: Action
    path: Path | None
    detail: str = ""


@dataclass
class DocsInstallPlan:
    """Aggregate result of a full docs install pass."""

    print_only: bool
    dry_run: bool
    results: list[DocsApplyResult] = field(default_factory=list)


def _load_trie_doc_body() -> str:
    """Return the bundled `TRIE.md` body as text.

    Uses `importlib.resources` so the doc lives once in the package and
    travels with the wheel. The repo-root `USING_TRIE.md` is a symlink to
    the same file for human readers browsing GitHub.
    """
    try:
        return resources.files("trie.data").joinpath("TRIE.md").read_text(encoding="utf-8")
    except (FileNotFoundError, ModuleNotFoundError) as exc:
        # Package mis-built (data file not bundled). Surface a clear error
        # rather than writing an empty TRIE.md.
        raise DocsInstallError(
            "trie package is missing the bundled TRIE.md (trie/data/TRIE.md). "
            "Reinstall with `uv tool install --reinstall git+...trie` or rebuild."
        ) from exc


def _render_tool_names(target_name: str | None) -> tuple[str, str, str]:
    """Resolve the rendered `grep`/`read`/`trace` names for `target_name`.

    Each MCPTarget carries a `tool_name_format` string with a `{tool}`
    placeholder; we substitute the three canonical tool names and return
    the trio. When `target_name` is None or unknown, fall back to the
    bare names (no harness prefix) so the doc still reads sensibly — the
    agent will still find the tools via tool listing, the names in the
    doc just won't carry a harness-specific prefix.
    """
    target = MCP_TARGETS.get(target_name) if target_name else None
    fmt = target.tool_name_format if target is not None else "{tool}"
    return fmt.format(tool="grep"), fmt.format(tool="read"), fmt.format(tool="trace")


def _render_trie_doc_body(target_name: str | None, additional_targets: list[str]) -> str:
    """Render TRIE.md with tool names baked in for `target_name`.

    Substitutes the `«grep»`, `«read»`, `«trace»` placeholders in the
    template with the harness-specific tool names. When other targets are
    also installed, appends a footer listing each one's equivalent tool
    names so an agent running through any of the wired harnesses can
    still resolve the tools — without forcing us to write multiple doc
    files.
    """
    grep_name, read_name, trace_name = _render_tool_names(target_name)
    body = _load_trie_doc_body()
    body = (
        body.replace("«grep»", grep_name)
        .replace("«read»", read_name)
        .replace("«trace»", trace_name)
    )
    if additional_targets:
        body += _multi_target_footer(target_name, additional_targets)
    return body


def _multi_target_footer(primary: str | None, additional: list[str]) -> str:
    """Build the footer that names tool aliases under other installed harnesses.

    When `trie setup` wires more than one agent into the same project, the
    primary harness's names go in the body and the rest land here. Each
    row shows the harness's display name and the three rendered tool
    names — enough for the agent to recognise the same tools by a
    different prefix.
    """
    primary_display = (
        MCP_TARGETS[primary].display_name if primary and primary in MCP_TARGETS else "primary"
    )
    lines = [
        "",
        "---",
        "",
        "## Tool names under other installed harnesses",
        "",
        (
            f"The names above are rendered for **{primary_display}**. "
            "This project is also wired for other agent harnesses, which "
            "prefix MCP tool names differently. If you are one of the "
            "agents below, use these names instead:"
        ),
        "",
    ]
    for slug in additional:
        target = MCP_TARGETS.get(slug)
        if target is None:
            continue
        grep_name, read_name, trace_name = _render_tool_names(slug)
        lines.append(f"- **{target.display_name}**: `{grep_name}`, `{read_name}`, `{trace_name}`")
    lines.append("")
    return "\n".join(lines)


def _write_trie_doc(
    project_root: Path,
    *,
    print_only: bool,
    dry_run: bool,
    target_name: str | None,
    additional_targets: list[str],
) -> DocsApplyResult:
    """Materialise `TRIE.md` at the project root.

    Idempotent on content: if the existing file matches what we'd write
    byte-for-byte, the result is `skipped`. The leading "generated by"
    notice means a user can identify the file as a trie artefact at a
    glance — and lets them safely delete it knowing it'll come back next
    `trie setup`.

    `target_name` selects the harness whose tool-name prefix is baked
    into the body (e.g. `mcp__trie__grep` for Claude Code, `trie_grep`
    for opencode). `additional_targets` adds a footer that lists tool
    names under any other installed harnesses, so a multi-agent project
    still gets one doc that every wired agent can read.
    """
    body = _GENERATED_NOTICE + _render_trie_doc_body(target_name, additional_targets)
    path = project_root / TRIE_DOC_FILENAME

    if print_only:
        return DocsApplyResult(target=TRIE_DOC_FILENAME, action="preview", path=path, detail=body)

    existed_before = path.exists()
    if existed_before:
        try:
            current = path.read_text(encoding="utf-8")
        except OSError as exc:
            return DocsApplyResult(
                target=TRIE_DOC_FILENAME,
                action="error",
                path=path,
                detail=f"could not read existing {TRIE_DOC_FILENAME}: {exc}",
            )
        if current == body:
            return DocsApplyResult(
                target=TRIE_DOC_FILENAME,
                action="skipped",
                path=path,
                detail="already up to date",
            )

    if dry_run:
        return DocsApplyResult(target=TRIE_DOC_FILENAME, action="preview", path=path, detail=body)

    path.write_text(body, encoding="utf-8")
    return DocsApplyResult(
        target=TRIE_DOC_FILENAME,
        action="updated" if existed_before else "created",
        path=path,
    )


def _pointer_block_for(target_name: str | None) -> str:
    """Build the marker-fenced pointer block for `target_name`.

    Uses the harness's tool-name format so the pointer line that lands
    in AGENTS.md / CLAUDE.md names the same tools the agent will see
    via MCP. When `target_name` is None or unknown, falls back to the
    bare names.
    """
    grep_name, read_name, trace_name = _render_tool_names(target_name)
    line = _pointer_line(grep_name, read_name, trace_name)
    return f"{POINTER_MARKER}\n{line}\n{POINTER_END_MARKER}\n"


def _apply_pointer(
    project_root: Path,
    filename: str,
    *,
    print_only: bool,
    dry_run: bool,
    target_name: str | None,
) -> DocsApplyResult | None:
    """Append (or refresh) the trie pointer block in one agent doc file.

    Returns `None` when the target file doesn't exist — we don't create
    AGENTS.md or CLAUDE.md ourselves. Both are user-authored conventions;
    materialising one signals an opinion about which agent harness the
    user prefers, and we don't have that information.

    When the file does exist:
      - If the marker block is already present with identical contents,
        return `skipped`.
      - If it's present with different contents (older trie version
        wrote a slightly different pointer line), rewrite *only* the
        block between MARKER and END_MARKER.
      - Otherwise append a fresh block at the end, preserving a blank
        line of separation from whatever the user had above it.

    `target_name` selects which harness's tool names go in the pointer
    line — same logic as `_write_trie_doc`.
    """
    path = project_root / filename
    if not path.exists():
        return None

    try:
        existing = path.read_text(encoding="utf-8")
    except OSError as exc:
        return DocsApplyResult(
            target=filename,
            action="error",
            path=path,
            detail=f"could not read {filename}: {exc}",
        )

    new_text = _splice_pointer_block(existing, _pointer_block_for(target_name))

    if print_only or dry_run:
        # For preview, hand back the spliced text so the user can eyeball
        # the diff before committing to it.
        return DocsApplyResult(target=filename, action="preview", path=path, detail=new_text)

    if new_text == existing:
        return DocsApplyResult(
            target=filename,
            action="skipped",
            path=path,
            detail="pointer block already up to date",
        )

    had_marker = POINTER_MARKER in existing
    path.write_text(new_text, encoding="utf-8")
    # Both branches count as "updated" — the file existed and now has
    # different contents. The distinction between "refreshed an existing
    # block" and "appended a new one" goes into the detail line.
    return DocsApplyResult(
        target=filename,
        action="updated",
        path=path,
        detail="refreshed pointer block" if had_marker else "appended pointer block",
    )


def _splice_pointer_block(existing: str, pointer_block: str = POINTER_BLOCK) -> str:
    """Return `existing` with our pointer block freshly written between markers.

    Two regimes:
      - Marker present: replace whatever sits between MARKER and END_MARKER
        (inclusive). Defensive against the user having hand-edited the
        block — we always rewrite to the canonical line.
      - Marker absent: append the block at the end, separated by a blank
        line from whatever came before.

    `pointer_block` defaults to the bare (unprefixed) form so callers
    that don't know about target-specific rendering still get a sensible
    result. `_apply_pointer` passes a target-rendered block.

    Pure text in / text out so the caller can use the same routine for
    both write and preview paths.
    """
    if POINTER_MARKER in existing and POINTER_END_MARKER in existing:
        before, _, rest = existing.partition(POINTER_MARKER)
        _, _, after = rest.partition(POINTER_END_MARKER)
        # Trim a leading newline from `after` so we don't accumulate blank
        # lines on repeated rewrites; the trailing newline on pointer_block
        # provides the separator we need.
        after = after.lstrip("\n")
        return before + pointer_block + ("\n" + after if after else "")

    # Fresh append. Ensure a clear visual gap between the user's content
    # and our block, and a trailing newline on the file.
    sep = "" if existing == "" else ("\n" if existing.endswith("\n\n") else "\n\n")
    return existing + sep + pointer_block


def install(
    *,
    project_root: Path,
    print_only: bool,
    dry_run: bool,
    target_names: list[str] | None = None,
) -> DocsInstallPlan:
    """Run the full docs install: TRIE.md plus pointer-line refresh.

    The plan always covers `TRIE.md`. It additionally covers each of
    `AGENT_DOC_FILES` that exists at the project root; missing files are
    silently skipped (no result emitted) because materialising them
    means picking an agent convention we don't have signal to pick.

    `target_names` is the list of MCP harnesses that just got wired in
    (passed through from `mcp_run_install`). The first entry, if any,
    selects which harness's tool-name prefix is baked into TRIE.md and
    the pointer block; the rest land in a footer at the bottom of
    TRIE.md so a multi-agent project still gets one doc that every
    wired agent can read. When `target_names` is None or empty (e.g. a
    standalone `trie docs install` invocation without MCP context),
    fall back to the bare unprefixed names, which match what the trie
    server actually registers.

    Errors on individual files don't abort the rest — each file gets its
    own result, and the CLI sums them up at the end.
    """
    plan = DocsInstallPlan(print_only=print_only, dry_run=dry_run)

    targets = list(target_names or [])
    primary = targets[0] if targets else None
    additional = targets[1:]

    plan.results.append(
        _write_trie_doc(
            project_root,
            print_only=print_only,
            dry_run=dry_run,
            target_name=primary,
            additional_targets=additional,
        )
    )
    for filename in AGENT_DOC_FILES:
        result = _apply_pointer(
            project_root,
            filename,
            print_only=print_only,
            dry_run=dry_run,
            target_name=primary,
        )
        if result is not None:
            plan.results.append(result)
    return plan
