"""Turn-boundary hook installation for coding agents.

Companion to `mcp_install.py`. `mcp_install` makes trie *available* to an
agent; this module makes trie *automatic*. The hooks invoke
`trie sync --graph-only` at the boundaries of an agent's turn so the graph stays
current with the working copy without the agent (or the user) having to
remember.

Coverage today is intentionally narrow: opencode is the only agent with a
documented event API we can wire into (`session.status` with idle status;
the older `session.idle` event was deprecated upstream on 2025-11-17). For
every other agent we know about, this module returns a `needs_manual_setup`
result that surfaces the instructions a human has to follow.

The shape mirrors `mcp_install` so `trie setup` can present one unified
report. Each `HookTarget` describes:

  - the agent-side path the plugin/config lives at,
  - a renderer for the file contents,
  - whether automation is supported at all.

`apply_one` materialises the file (or returns the preview when --print-only
or --dry-run). Idempotency is handled the same way as MCP install: if the
existing file matches what we'd write, the result is `skipped`.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from trie.mcp_install import Scope

Action = Literal["created", "updated", "skipped", "preview", "error", "needs_manual_setup"]


class HookInstallError(Exception):
    pass


@dataclass(frozen=True)
class HookApplyResult:
    """Outcome of a single-target hook install operation.

    `needs_manual_setup` is the explicit "we know about this agent but can't
    automate it yet" state. It carries `detail` text suitable for printing —
    the user follows those instructions by hand.
    """

    target: str
    action: Action
    path: Path | None
    contents: str
    detail: str = ""


@dataclass(frozen=True)
class HookSupportFile:
    """A secondary file written alongside the primary plugin file.

    Used for runtime scaffolding the hook depends on but doesn't itself
    contain — e.g. the `.opencode/package.json` that lets opencode's bun
    install pin `@opencode-ai/plugin` cleanly. Reported in the apply result
    via `detail` but doesn't appear as a separate `HookApplyResult`; this is
    intentionally a quiet, hook-internal concern.
    """

    relative_path: tuple[str, ...]
    render_contents: Callable[[Path], str]


@dataclass(frozen=True)
class HookTarget:
    """Static description of an agent's turn-boundary hook surface.

    `render_contents` returns the bytes (as text) that should land at
    `relative_path`. When `None`, the target is known but doesn't have an
    automatable hook story — `apply_one` returns `needs_manual_setup` so the
    user knows to wire it themselves.

    `support_files` is for ancillary files the hook's runtime depends on
    (e.g. `.opencode/package.json`). They're written transparently as part
    of `apply_one` and are subject to the same idempotency rules as the
    primary file.
    """

    name: str
    display_name: str
    # When None: this target doesn't support automated hook install.
    # Otherwise: the relative path (under project root) where the plugin lives,
    # and a callable returning its contents.
    relative_path: tuple[str, ...] | None = None
    render_contents: Callable[[Path], str] | None = None
    manual_instructions: str = ""
    support_files: tuple[HookSupportFile, ...] = ()


# ---------------------------------------------------------------------------
# opencode: plugin-based turn hook via the `session.status` event (idle status).
# ---------------------------------------------------------------------------


_OPENCODE_PLUGIN_FILENAME = "trie-refresh.ts"


def _render_opencode_plugin(_project_root: Path) -> str:
    """Render the opencode plugin file that fires
    `trie sync --graph-only --after-turn` every time an agent session goes idle.

    The plugin listens for `session.status` with `status.type === "idle"`
    (documented in opencode's plugin reference) and shells out to the global
    `trie` binary. opencode also still emits a deprecated `session.idle` event;
    we ignore it to avoid double-firing — `session.status` is the future-proof
    surface (the legacy event was marked deprecated in upstream commit
    bdfa213c on 2025-11-17).

    The hook runs fire-and-await: opencode pauses for the duration before
    moving on, which is the right tradeoff during eval runs where we'd rather
    the next turn see a fresh graph than start fast and look stale.

    `quiet()` suppresses Bun shell stdout/stderr so the opencode TUI isn't
    flooded with graph-sync output. Telemetry events still land in trie's own
    `debug.jsonl`, so the activity is visible via `trie audit`.
    """
    return """// Auto-generated by `trie setup`. Do not hand-edit — it'll be overwritten
// next time you run `trie setup`. The hook fires
// `trie sync --graph-only --after-turn` when an opencode session goes idle,
// keeping the symbol graph in sync with edits the agent made during the turn
// (prose regen stays manual via a full `trie sync`).
//
// We listen for `session.status` with status.type === "idle" — the
// `session.idle` event was deprecated upstream (commit bdfa213c, 2025-11-17)
// and listening for both would double-fire the hook.
//
// See https://opencode.ai/docs/plugins for the plugin API.

import type { Plugin } from "@opencode-ai/plugin"

const TrieRefreshPlugin: Plugin = async ({ $, directory }) => {
  return {
    event: async ({ event }) => {
      if (event.type !== "session.status") return
      if ((event as any).properties?.status?.type !== "idle") return
      try {
        await $`trie sync --graph-only --after-turn`.cwd(directory).quiet()
      } catch {
        // Swallow errors. trie logs to debug.jsonl on failure; the
        // plugin throwing would noisy-up the opencode TUI for problems the
        // user can diagnose via `trie audit` later.
      }
    },
  }
}

// opencode v1.x prefers a default-exported PluginModule object ({ id, server }).
// Named exports (the v0 shape) still work via the legacy loader, but the v1
// shape is what the loader looks for first and is required for path plugins
// since `resolvePluginId` mandates an explicit id.
export default {
  id: "trie-refresh",
  server: TrieRefreshPlugin,
}
"""


def _render_opencode_package_json(_project_root: Path) -> str:
    """Render `.opencode/package.json` pinning `@opencode-ai/plugin`.

    Without this file, opencode runs `bun install` against the `.opencode/`
    directory at startup and tries to add `@opencode-ai/plugin` with a version
    derived from the running opencode build. For dev/source builds (or any
    stale state where the version resolves to `"local"`), bun writes
    `"@opencode-ai/plugin": "local"` into the generated package.json, the next
    install fails ("No matching version found for @opencode-ai/plugin@local"),
    and every `.opencode/tools/*.ts` import that pulls from `@opencode-ai/plugin`
    dies with ERR_MODULE_NOT_FOUND. The user-visible symptom is that opencode
    sessions become silently unresponsive (see anomalyco/opencode#28286 and
    #27676).

    Shipping a known-good baseline pinned to `"latest"` pre-empts opencode's
    broken auto-pin: arborist will overwrite our `"latest"` with the running
    opencode version, which is a real published version and resolves cleanly.

    We declare it as a `dependencies` entry (not `peerDependencies`) so bun's
    arborist treats it as the canonical install target.
    """
    return """{
  "//": "Auto-generated by `trie setup`. Do not hand-edit — opencode rewrites this on every startup. The pin pre-empts the @opencode-ai/plugin@local resolution failure that silently kills tool overrides; see https://github.com/anomalyco/opencode/issues/28286.",
  "name": "trie-opencode-overrides",
  "private": true,
  "dependencies": {
    "@opencode-ai/plugin": "latest"
  }
}
"""


# ---------------------------------------------------------------------------
# Target registry.
# ---------------------------------------------------------------------------

# Every name MUST also exist in `trie.mcp_install.TARGETS` so the setup
# subcommand can pair MCP and hook install for the same target slug.
TARGETS: dict[str, HookTarget] = {
    "opencode": HookTarget(
        name="opencode",
        display_name="opencode",
        relative_path=(".opencode", "plugins", _OPENCODE_PLUGIN_FILENAME),
        render_contents=_render_opencode_plugin,
        support_files=(
            # opencode runs `bun install` against `.opencode/` at startup and
            # tries to add `@opencode-ai/plugin`. If a stale `package.json`
            # pins it to `"local"` (the dev-build sentinel), every subsequent
            # install fails and tool-override `.ts` files die with
            # ERR_MODULE_NOT_FOUND, silently breaking the session. Shipping
            # our own baseline pre-empts that.
            HookSupportFile(
                relative_path=(".opencode", "package.json"),
                render_contents=_render_opencode_package_json,
            ),
        ),
    ),
    "claude-code": HookTarget(
        name="claude-code",
        display_name="Claude Code",
        manual_instructions=(
            "Claude Code does not currently expose a per-turn lifecycle hook in "
            "its public configuration surface. Run `trie sync --graph-only --after-turn` "
            "manually after Claude finishes a session, or wire it into a shell "
            "wrapper around the `claude` binary if you use one."
        ),
    ),
    "claude-desktop": HookTarget(
        name="claude-desktop",
        display_name="Claude Desktop",
        manual_instructions=(
            "Claude Desktop has no documented per-turn hook surface. Use the "
            "agent in conversational mode and run `trie sync --graph-only` from a "
            "terminal between sessions when you've made local edits."
        ),
    ),
    "cursor": HookTarget(
        name="cursor",
        display_name="Cursor",
        manual_instructions=(
            "Cursor exposes no per-turn hook in its current MCP integration. "
            "Run `trie sync --graph-only --after-turn` from a terminal after Cursor "
            "edits files, or watch this space for an automated path once the "
            "Cursor hook story is documented."
        ),
    ),
    "windsurf": HookTarget(
        name="windsurf",
        display_name="Windsurf",
        manual_instructions=(
            "Windsurf has no public per-turn hook API. Run `trie sync --graph-only` "
            "manually between sessions."
        ),
    ),
    "vscode": HookTarget(
        name="vscode",
        display_name="VS Code",
        manual_instructions=(
            "VS Code's MCP integration doesn't expose per-turn hooks. Use a "
            "task or a workspace `postCommit` hook to invoke `trie sync --graph-only`, "
            "or run it manually."
        ),
    ),
    "codex": HookTarget(
        name="codex",
        display_name="Codex CLI",
        manual_instructions=(
            "Codex CLI has no documented turn-boundary hook surface. Run "
            "`trie sync --graph-only --after-turn` after Codex sessions, or wrap the "
            "`codex` binary in a script that does so."
        ),
    ),
}


# ---------------------------------------------------------------------------
# Application logic.
# ---------------------------------------------------------------------------


@dataclass
class HookInstallPlan:
    """Result of a full `install` call across one or more targets."""

    target_names: list[str]
    print_only: bool
    dry_run: bool
    results: list[HookApplyResult] = field(default_factory=list)


def install(
    *,
    target_names: list[str] | None,
    install_all: bool,
    print_only: bool,
    dry_run: bool,
    project_root: Path,
) -> HookInstallPlan:
    """Apply turn-boundary hooks for one or more targets.

    Symmetric with `trie.mcp_install.install`: same flag semantics, same
    return-shape philosophy. Unknown target names raise `HookInstallError`
    so the caller can report a clean error.

    Agents without automated hook support don't error — they produce a
    `needs_manual_setup` result carrying the instructions for the user.
    """
    if install_all:
        chosen = list(TARGETS.values())
    elif target_names:
        chosen = []
        for name in target_names:
            if name not in TARGETS:
                raise HookInstallError(
                    f"unknown hook target: {name!r}. Known: {', '.join(TARGETS)}"
                )
            chosen.append(TARGETS[name])
    else:
        # Auto-detect mirrors mcp_install's behaviour by reusing the same
        # `detect()` outputs there. We import lazily to keep the modules
        # independent at import time.
        from trie.mcp_install import TARGETS as MCP_TARGETS

        chosen = []
        for slug, mcp_target in MCP_TARGETS.items():
            if slug in TARGETS and mcp_target.detect():
                chosen.append(TARGETS[slug])
        if not chosen:
            raise HookInstallError(
                "no agents detected on this system for hook install. "
                f"Pass --target NAME or --all (known: {', '.join(TARGETS)})."
            )

    plan = HookInstallPlan(
        target_names=[t.name for t in chosen],
        print_only=print_only,
        dry_run=dry_run,
    )
    for target in chosen:
        plan.results.append(apply_one(target, project_root, print_only, dry_run))
    return plan


def apply_one(
    target: HookTarget,
    project_root: Path,
    print_only: bool,
    dry_run: bool,
    *,
    scope: Scope = "project",
) -> HookApplyResult:
    """Install (or preview) the hook for one target.

    `scope` is accepted for API symmetry with `mcp_install.apply_one` but is
    currently ignored: opencode plugins always live under the project. We
    can revisit if a user-scope plugin location ever makes sense.
    """
    _ = scope  # reserved
    if target.render_contents is None or target.relative_path is None:
        return HookApplyResult(
            target=target.name,
            action="needs_manual_setup",
            path=None,
            contents="",
            detail=target.manual_instructions
            or f"{target.display_name} has no automated hook installer in this trie version.",
        )

    contents = target.render_contents(project_root)
    target_path = project_root.joinpath(*target.relative_path)

    if print_only:
        return HookApplyResult(
            target=target.name,
            action="preview",
            path=target_path,
            contents=contents,
        )

    existed_before = target_path.exists()
    if existed_before:
        try:
            current = target_path.read_text()
        except OSError as exc:
            return HookApplyResult(
                target=target.name,
                action="error",
                path=target_path,
                contents=contents,
                detail=f"could not read existing hook file: {exc}",
            )
        if current == contents:
            # Still pass through the support-file writer: a user upgrading
            # trie from a release that predates `support_files` (or one that
            # had a manually-deleted `.opencode/package.json`) needs the
            # baseline package.json to land even when the plugin itself is
            # already up to date.
            support_notes = _apply_support_files(target.support_files, project_root)
            detail = "hook already installed with the same contents"
            if support_notes:
                detail = f"{detail}; {'; '.join(support_notes)}"
            return HookApplyResult(
                target=target.name,
                action="skipped",
                path=target_path,
                contents=contents,
                detail=detail,
            )

    if dry_run:
        return HookApplyResult(
            target=target.name,
            action="preview",
            path=target_path,
            contents=contents,
        )

    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(contents)

    support_notes = _apply_support_files(target.support_files, project_root)
    detail = "; ".join(support_notes) if support_notes else ""

    return HookApplyResult(
        target=target.name,
        action="updated" if existed_before else "created",
        path=target_path,
        contents=contents,
        detail=detail,
    )


def _apply_support_files(
    files: tuple[HookSupportFile, ...],
    project_root: Path,
) -> list[str]:
    """Write each support file with the same created/updated/skipped semantics
    as the primary hook file, returning short human-readable notes.

    Failures to write a single support file are noted but don't propagate;
    the primary hook is the gating contract and we don't want a missing
    `.opencode/package.json` write permission to mask a successful plugin
    install. Issues become visible through trie's own telemetry and the
    notes returned here.
    """
    notes: list[str] = []
    for support in files:
        path = project_root.joinpath(*support.relative_path)
        rel = "/".join(support.relative_path)
        contents = support.render_contents(project_root)
        try:
            if path.exists() and path.read_text() == contents:
                notes.append(f"{rel}: up to date")
                continue
            path.parent.mkdir(parents=True, exist_ok=True)
            existed = path.exists()
            path.write_text(contents)
            notes.append(f"{rel}: {'updated' if existed else 'created'}")
        except OSError as exc:
            notes.append(f"{rel}: write failed ({exc})")
    return notes
