"""Turn-boundary hook installation for coding agents.

Companion to `mcp_install.py`. `mcp_install` makes trie *available* to an
agent; this module makes trie *automatic*. The hooks invoke `trie refresh`
at the boundaries of an agent's turn so the graph + triefact tree stay
current with the working copy without the agent (or the user) having to
remember.

Coverage today is intentionally narrow: opencode is the only agent with a
documented event API we can wire into (`session.idle`). For every other
agent we know about, this module returns a `needs_manual_setup` result
that surfaces the instructions a human has to follow.

The shape mirrors `mcp_install` so `trie setup` can present one unified
report. Each `HookTarget` describes:

  - the agent-side path the plugin/config lives at,
  - a renderer for the file contents,
  - whether automation is supported at all.

`apply_one` materialises the file (or returns the preview when --print-only
or --dry-run). Idempotency is handled the same way as MCP install: if the
existing file matches what we'd write, the result is `skipped`.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from trie.mcp_install import Scope

Action = Literal["created", "updated", "skipped", "preview", "error", "needs_manual_setup"]


class HookInstallError(Exception):
    pass


@dataclass(frozen=True)
class HookApplyResult:
    """Outcome of a single-target hook install operation.

    `needs_manual_setup` is the explicit "we know about this agent but can't
    automate it yet" state. It carries `detail` text suitable for printing —
    the user follows those instructions by hand.
    """

    target: str
    action: Action
    path: Path | None
    contents: str
    detail: str = ""


@dataclass(frozen=True)
class HookTarget:
    """Static description of an agent's turn-boundary hook surface.

    `render_contents` returns the bytes (as text) that should land at
    `relative_path`. When `None`, the target is known but doesn't have an
    automatable hook story — `apply_one` returns `needs_manual_setup` so the
    user knows to wire it themselves.
    """

    name: str
    display_name: str
    # When None: this target doesn't support automated hook install.
    # Otherwise: the relative path (under project root) where the plugin lives,
    # and a callable returning its contents.
    relative_path: tuple[str, ...] | None = None
    render_contents: Callable[[Path], str] | None = None
    manual_instructions: str = ""


# ---------------------------------------------------------------------------
# opencode: plugin-based turn hook via the `session.idle` event.
# ---------------------------------------------------------------------------


_OPENCODE_PLUGIN_FILENAME = "trie-refresh.ts"


def _render_opencode_plugin(_project_root: Path) -> str:
    """Render the opencode plugin file that fires `trie refresh --after-turn`
    every time an agent session goes idle.

    The plugin listens for the `session.idle` event (documented in opencode's
    plugin reference) and shells out to the global `trie` binary. The hook
    runs in fire-and-await fashion: opencode pauses for the duration before
    moving on, which is the right tradeoff during eval runs where we'd rather
    the next turn see a fresh graph than start fast and look stale.

    `quiet()` suppresses Bun shell stdout/stderr so the opencode TUI isn't
    flooded with refresh output. Telemetry events still land in trie's own
    `debug.jsonl`, so the refresh activity is visible via `trie audit`.
    """
    return """// Auto-generated by `trie setup`. Do not hand-edit — it'll be overwritten
// next time you run `trie setup`. The hook fires `trie refresh --after-turn`
// when an opencode session goes idle, keeping the graph + triefact tree in
// sync with edits the agent made during the turn.
//
// See https://opencode.ai/docs/plugins for the plugin API.

import type { Plugin } from "@opencode-ai/plugin"

export const TrieRefresh: Plugin = async ({ $, directory }) => {
  return {
    event: async ({ event }) => {
      if (event.type === "session.idle") {
        try {
          await $`trie refresh --after-turn`.cwd(directory).quiet()
        } catch {
          // Swallow errors. trie refresh logs to debug.jsonl on failure; the
          // plugin throwing would noisy-up the opencode TUI for problems the
          // user can diagnose via `trie audit` later.
        }
      }
    },
  }
}
"""


# ---------------------------------------------------------------------------
# Target registry.
# ---------------------------------------------------------------------------

# Every name MUST also exist in `trie.mcp_install.TARGETS` so the setup
# subcommand can pair MCP and hook install for the same target slug.
TARGETS: dict[str, HookTarget] = {
    "opencode": HookTarget(
        name="opencode",
        display_name="opencode",
        relative_path=(".opencode", "plugins", _OPENCODE_PLUGIN_FILENAME),
        render_contents=_render_opencode_plugin,
    ),
    "claude-code": HookTarget(
        name="claude-code",
        display_name="Claude Code",
        manual_instructions=(
            "Claude Code does not currently expose a per-turn lifecycle hook in "
            "its public configuration surface. Run `trie refresh --after-turn` "
            "manually after Claude finishes a session, or wire it into a shell "
            "wrapper around the `claude` binary if you use one."
        ),
    ),
    "claude-desktop": HookTarget(
        name="claude-desktop",
        display_name="Claude Desktop",
        manual_instructions=(
            "Claude Desktop has no documented per-turn hook surface. Use the "
            "agent in conversational mode and run `trie refresh` from a terminal "
            "between sessions when you've made local edits."
        ),
    ),
    "cursor": HookTarget(
        name="cursor",
        display_name="Cursor",
        manual_instructions=(
            "Cursor exposes no per-turn hook in its current MCP integration. "
            "Run `trie refresh --after-turn` from a terminal after Cursor "
            "edits files, or watch this space for an automated path once the "
            "Cursor hook story is documented."
        ),
    ),
    "windsurf": HookTarget(
        name="windsurf",
        display_name="Windsurf",
        manual_instructions=(
            "Windsurf has no public per-turn hook API. Run `trie refresh` "
            "manually between sessions."
        ),
    ),
    "vscode": HookTarget(
        name="vscode",
        display_name="VS Code",
        manual_instructions=(
            "VS Code's MCP integration doesn't expose per-turn hooks. Use a "
            "task or a workspace `postCommit` hook to invoke `trie refresh`, "
            "or run it manually."
        ),
    ),
    "codex": HookTarget(
        name="codex",
        display_name="Codex CLI",
        manual_instructions=(
            "Codex CLI has no documented turn-boundary hook surface. Run "
            "`trie refresh --after-turn` after Codex sessions, or wrap the "
            "`codex` binary in a script that does so."
        ),
    ),
}


# ---------------------------------------------------------------------------
# Application logic.
# ---------------------------------------------------------------------------


@dataclass
class HookInstallPlan:
    """Result of a full `install` call across one or more targets."""

    target_names: list[str]
    print_only: bool
    dry_run: bool
    results: list[HookApplyResult] = field(default_factory=list)


def install(
    *,
    target_names: list[str] | None,
    install_all: bool,
    print_only: bool,
    dry_run: bool,
    project_root: Path,
) -> HookInstallPlan:
    """Apply turn-boundary hooks for one or more targets.

    Symmetric with `trie.mcp_install.install`: same flag semantics, same
    return-shape philosophy. Unknown target names raise `HookInstallError`
    so the caller can report a clean error.

    Agents without automated hook support don't error — they produce a
    `needs_manual_setup` result carrying the instructions for the user.
    """
    if install_all:
        chosen = list(TARGETS.values())
    elif target_names:
        chosen = []
        for name in target_names:
            if name not in TARGETS:
                raise HookInstallError(
                    f"unknown hook target: {name!r}. Known: {', '.join(TARGETS)}"
                )
            chosen.append(TARGETS[name])
    else:
        # Auto-detect mirrors mcp_install's behaviour by reusing the same
        # `detect()` outputs there. We import lazily to keep the modules
        # independent at import time.
        from trie.mcp_install import TARGETS as MCP_TARGETS

        chosen = []
        for slug, mcp_target in MCP_TARGETS.items():
            if slug in TARGETS and mcp_target.detect():
                chosen.append(TARGETS[slug])
        if not chosen:
            raise HookInstallError(
                "no agents detected on this system for hook install. "
                f"Pass --target NAME or --all (known: {', '.join(TARGETS)})."
            )

    plan = HookInstallPlan(
        target_names=[t.name for t in chosen],
        print_only=print_only,
        dry_run=dry_run,
    )
    for target in chosen:
        plan.results.append(apply_one(target, project_root, print_only, dry_run))
    return plan


def apply_one(
    target: HookTarget,
    project_root: Path,
    print_only: bool,
    dry_run: bool,
    *,
    scope: Scope = "project",
) -> HookApplyResult:
    """Install (or preview) the hook for one target.

    `scope` is accepted for API symmetry with `mcp_install.apply_one` but is
    currently ignored: opencode plugins always live under the project. We
    can revisit if a user-scope plugin location ever makes sense.
    """
    _ = scope  # reserved
    if target.render_contents is None or target.relative_path is None:
        return HookApplyResult(
            target=target.name,
            action="needs_manual_setup",
            path=None,
            contents="",
            detail=target.manual_instructions
            or f"{target.display_name} has no automated hook installer in this trie version.",
        )

    contents = target.render_contents(project_root)
    target_path = project_root.joinpath(*target.relative_path)

    if print_only:
        return HookApplyResult(
            target=target.name,
            action="preview",
            path=target_path,
            contents=contents,
        )

    existed_before = target_path.exists()
    if existed_before:
        try:
            current = target_path.read_text()
        except OSError as exc:
            return HookApplyResult(
                target=target.name,
                action="error",
                path=target_path,
                contents=contents,
                detail=f"could not read existing hook file: {exc}",
            )
        if current == contents:
            return HookApplyResult(
                target=target.name,
                action="skipped",
                path=target_path,
                contents=contents,
                detail="hook already installed with the same contents",
            )

    if dry_run:
        return HookApplyResult(
            target=target.name,
            action="preview",
            path=target_path,
            contents=contents,
        )

    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(contents)
    return HookApplyResult(
        target=target.name,
        action="updated" if existed_before else "created",
        path=target_path,
        contents=contents,
    )
