"""Generate the wiki front door: an index README for the triefact tree.

The triefact tree mirrors source paths, which is perfect for "what does this
file do" and useless as a landing page. `trie index` writes
`<triefacts.root>/README.md` — a deterministic, LLM-free table of contents:

- **Entry points**: the most-referenced public symbols with their one-liners,
  linked to the triefact file that documents them. This is "start here."
- **Files**: every triefact, grouped by directory, with the file-level
  description from its front matter.

Everything is derived from data trie already has (the graph store and triefact
front matter), so regeneration is free and safe to run on every sync. The file
carries a managed-by marker and is wholly owned by trie — hand edits are
overwritten on the next sync.

The index lives inside the triefact root but is not a mirrored source file, so
`trie verify` ignores it; digest evidence collection excludes it explicitly
(see `session_diff._triefact_pathspecs`).
"""

from __future__ import annotations

from pathlib import Path
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from trie.config import Config
    from trie.graph.store import Store

INDEX_MARKER = "<!-- auto-generated by `trie index` (runs on every sync); do not edit -->"

_ENTRY_POINT_LIMIT = 15


def _file_descriptions(triefacts_root: Path, *, skip_dirs: set[str]) -> dict[str, str]:
    """Map triefact-relative paths -> front-matter description (may be '')."""
    import yaml

    from trie.sync.writer import FRONT_MATTER_RE

    out: dict[str, str] = {}
    if not triefacts_root.is_dir():
        return out
    for path in sorted(triefacts_root.rglob("*.md")):
        rel = path.relative_to(triefacts_root).as_posix()
        if rel == "README.md" or (rel.split("/", 1)[0] in skip_dirs):
            continue
        try:
            m = FRONT_MATTER_RE.match(path.read_text())
        except OSError:
            continue
        desc = ""
        if m:
            try:
                fm = yaml.safe_load(m.group("yaml"))
                if isinstance(fm, dict):
                    desc = str(fm.get("description") or "").strip()
            except Exception:
                desc = ""
        out[rel] = " ".join(desc.split())
    return out


def build_index(*, store: Store, config: Config, project_root: Path) -> str:
    """Render the triefact-tree index markdown. Pure function of store + tree."""
    from trie.graph.store import GrepPredicate

    triefacts_root = project_root / config.triefacts.root
    diffs_dir = getattr(getattr(config, "diff", None), "diffs_dir", "") or ""
    skip_dirs: set[str] = set()
    # The digest archive may live inside the triefact root; keep it out of the TOC.
    try:
        rel_diffs = (project_root / diffs_dir).relative_to(triefacts_root).as_posix()
        skip_dirs.add(rel_diffs.split("/", 1)[0])
    except ValueError:
        pass

    lines: list[str] = []
    lines.append("# Codebase wiki")
    lines.append("")
    lines.append(INDEX_MARKER)
    lines.append("")
    lines.append(
        "Prose descriptions of every in-scope source file and symbol, kept in "
        "sync with the code by [trie](https://github.com/computer-reinvention/trie). "
        "Each page mirrors a source file; free-form notes outside the generated "
        "sections survive regeneration."
    )

    # -- Entry points --------------------------------------------------------
    details = store.grep_symbols(
        GrepPredicate(public_only=True),
        rank_by="inbound_count",
        limit=_ENTRY_POINT_LIMIT,
    )
    details = [d for d in details if d.inbound_count > 0 and d.one_liner]
    if details:
        lines.append("")
        lines.append("## Entry points")
        lines.append("")
        lines.append("The most-referenced public symbols — start reading here.")
        lines.append("")
        for d in details:
            md_rel = Path(d.file_path).with_suffix(".md").as_posix()
            role = f" `{d.role}`" if d.role else ""
            lines.append(
                f"- [`{d.qualified_name}`]({md_rel}) ({d.inbound_count} refs){role} — {d.one_liner}"
            )

    # -- Files ----------------------------------------------------------------
    descriptions = _file_descriptions(triefacts_root, skip_dirs=skip_dirs)
    if descriptions:
        by_dir: dict[str, list[tuple[str, str]]] = {}
        for rel, desc in descriptions.items():
            parent = str(Path(rel).parent)
            by_dir.setdefault("" if parent == "." else parent, []).append((rel, desc))
        lines.append("")
        lines.append("## Files")
        for dirname in sorted(by_dir):
            lines.append("")
            lines.append(f"### {dirname or '(project root)'}")
            lines.append("")
            for rel, desc in sorted(by_dir[dirname]):
                name = Path(rel).name
                entry = f"- [{name}]({rel})"
                if desc:
                    entry += f" — {desc}"
                lines.append(entry)

    lines.append("")
    return "\n".join(lines)


def write_index(*, store: Store, config: Config, project_root: Path) -> Path | None:
    """Write the index to `<triefacts.root>/README.md`. Returns the path, or
    None when the triefact root doesn't exist yet (nothing synced)."""
    triefacts_root = project_root / config.triefacts.root
    if not triefacts_root.is_dir():
        return None
    text = build_index(store=store, config=config, project_root=project_root)
    path = triefacts_root / "README.md"
    path.write_text(text)
    return path
