"""Tool-override installation: replace an agent's built-in tools with trie wrappers.

Companion to `mcp_install.py` and `hook_install.py`. Where `mcp_install` makes
trie available to an agent and `hook_install` makes it automatic, this module
makes trie *unavoidable* — it replaces or supplements the agent's built-in
tools so the agent reaches for trie reflexively, not just when prompted.

The interception story differs per harness:

- **opencode** supports drop-in tool replacement via `.opencode/tools/<name>.ts`.
  A custom tool whose filename matches a built-in name takes precedence over
  the built-in. We override `grep` (which has matching semantics — both find
  things in code) and *add* new tools `trie_read` / `trie_trace` that wrap the
  read and trace operations under non-colliding names.
- **Claude Code** has no tool-override surface. The closest mechanism is a
  `PreToolUse` hook that fires before each built-in tool call and can emit a
  `systemMessage` Claude sees on its next turn. We use it for advisory
  steering on `Grep` only: "for symbol queries, prefer mcp__trie__grep".

Other harnesses don't have a documented interception path; they get a
`needs_manual_setup` result that explains the situation.

This is opt-in. `trie setup` prompts before writing any override files; the
user must say yes. The generated files carry the same "generated by, do not
hand-edit" notice as the hook plugin so re-running setup picks up
content drift, and the user can delete a file to opt back out.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from trie.mcp_install import Scope

Action = Literal["created", "updated", "skipped", "preview", "error", "needs_manual_setup"]


class ToolOverrideInstallError(Exception):
    pass


@dataclass(frozen=True)
class FileToWrite:
    """One file an override target needs on disk.

    A target may need several files: e.g. opencode needs `grep.ts` (the
    override) plus `trie_read.ts` and `trie_trace.ts` (additions). Each is
    rendered independently with its own idempotency check, so a partial
    failure on one file doesn't roll back the others.
    """

    relative_path: tuple[str, ...]
    render: Callable[[Path], str]
    description: str  # short label for the human-readable report


@dataclass(frozen=True)
class ToolOverrideApplyResult:
    """Outcome of installing override files for one target.

    `files` carries per-file results so the CLI can report which individual
    overrides landed and which were skipped. The top-level `action` summarises
    across files: if any file errored, action is "error"; if all skipped,
    "skipped"; otherwise "created"/"updated" reflecting the highest-energy
    change.
    """

    target: str
    action: Action
    files: list[ToolOverrideFileResult] = field(default_factory=list)
    detail: str = ""


@dataclass(frozen=True)
class ToolOverrideFileResult:
    """Per-file outcome inside a target's apply result."""

    relative_path: str
    action: Action
    path: Path | None
    description: str
    detail: str = ""


@dataclass(frozen=True)
class ToolOverrideTarget:
    """Static description of an agent's tool-override surface.

    `files` is the list of override files to write. Empty list means the
    target has no automatable override path; `apply_one` returns
    `needs_manual_setup` with `manual_instructions` for the user.
    """

    name: str
    display_name: str
    files: tuple[FileToWrite, ...] = ()
    manual_instructions: str = ""
    # Human-readable one-line description of what installing for this target
    # actually does. Used in the interactive prompt so the user knows what
    # they're consenting to.
    summary: str = ""


# ---------------------------------------------------------------------------
# opencode: override `grep`, add `trie_read` and `trie_trace`.
# ---------------------------------------------------------------------------


_GENERATED_HEADER = """// Auto-generated by `trie setup --override-builtins`. Do not hand-edit —
// re-running setup will overwrite this file. Delete the file to opt out of
// the override; trie setup won't recreate it without explicit consent.
//
// See https://opencode.ai/docs/custom-tools for the custom-tools API.
"""


def _render_opencode_grep_override(_project_root: Path) -> str:
    """Render `.opencode/tools/grep.ts` — overrides opencode's built-in `grep`.

    The file ships under the same filename as the built-in tool. Opencode's
    rule (documented at opencode.ai/docs/custom-tools): a default-exported
    custom tool whose filename matches a built-in takes precedence over the
    built-in. So once this file lands, every `grep` call from the agent
    routes through trie's `grep` instead of opencode's regex-over-files
    grep.

    Args are intentionally close to opencode's built-in grep so the agent
    doesn't have to relearn the call shape: `pattern` is the substring to
    search for (mapped to trie's `name_contains` predicate), `path` becomes
    `scope_prefix`, `include` is rejected (trie's scope is config-driven,
    not per-call). The wrapper shells out to `trie grep --json` and returns
    the envelope verbatim so the agent gets the same structured response it
    would get over MCP.

    `Bun.spawn` is what's used by the existing `trie-refresh.ts` plugin in
    this directory, so we know the runtime supports it. Errors from `trie`
    are bubbled up so the agent sees them on the next turn.
    """
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Search for symbols and source-body text via trie. Replaces opencode's " +
    "built-in grep with a symbol-aware search that returns signatures, " +
    "one-liners, and call-graph metrics — and falls back to ripgrep against " +
    "indexed source bodies when the query doesn't match a symbol name.",
  args: {
    pattern: tool.schema
      .string()
      .describe(
        "Substring to search for. Mapped to trie's `name_contains` " +
          "predicate; case-insensitive, matched against symbol local names. " +
          "If no symbol matches, trie's text-match fallback searches in-scope " +
          "source bodies and attributes hits to enclosing symbols.",
      ),
    path: tool.schema
      .string()
      .optional()
      .describe(
        "Path prefix to restrict the search to (e.g. 'src/' or 'trie/sync/'). " +
          "Maps to trie's `scope_prefix` predicate.",
      ),
    kind: tool.schema
      .string()
      .optional()
      .describe(
        "Restrict to one symbol kind: 'function', 'class', 'method', or 'any'.",
      ),
    public_only: tool.schema
      .boolean()
      .optional()
      .describe("If true, exclude symbols whose name starts with an underscore."),
    rank_by: tool.schema
      .string()
      .optional()
      .describe(
        "Result ordering: 'public_first' (default), 'inbound_count' " +
          "(centrality), or 'alphabetical'.",
      ),
    limit: tool.schema
      .number()
      .optional()
      .describe("Maximum number of hits to return. Defaults to 10."),
  },
  async execute(args, context) {
    const flags: string[] = ["grep", "--json", "--name", args.pattern]
    if (args.path) flags.push("--scope-prefix", args.path)
    if (args.kind) flags.push("--kind", args.kind)
    if (args.public_only) flags.push("--public-only")
    if (args.rank_by) flags.push("--rank-by", args.rank_by)
    if (args.limit !== undefined) flags.push("--limit", String(args.limit))

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])

    // Exit code 1 is a tool-level error (e.g. invalid predicate); the JSON
    // envelope on stdout carries the structured error. Code 2 is a CLI
    // usage error from trie itself. Anything else is unexpected.
    if (code === 0 || code === 1) {
      return stdout || "(empty response from trie)"
    }
    throw new Error(
      `trie grep failed (exit ${code}): ${stderr.trim() || "no stderr"}`,
    )
  },
})
"""
    )


def _render_opencode_trie_read(_project_root: Path) -> str:
    """Render `.opencode/tools/trie_read.ts` — exposes `trie read` to the agent.

    Unlike `grep.ts`, this filename does not collide with any opencode
    built-in. The file *adds* a new tool to the agent's palette under the
    name `trie_read`, sitting alongside the unmodified built-in `read`
    (which still opens files by path).

    The semantic distinction is intentional: built-in `read` takes a file
    path; this tool takes a qname and returns prose + immediate
    neighbours. Both are useful for different things. We don't override
    built-in `read` because doing so would break basic file reading; we
    add this as a parallel tool the agent can reach for when it has a
    symbol in mind, not a file path.
    """
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Read a symbol's prose plus its immediate callers and callees from the " +
    "trie graph. Takes a fully-qualified symbol name (qname), NOT a file " +
    "path — for file paths, use the built-in `read` tool. Returns the " +
    "symbol's signature, prose body from the triefact, source pointer, and " +
    "one-liner descriptions of every caller and callee.",
  args: {
    qname: tool.schema
      .string()
      .describe(
        "Fully-qualified symbol name. Format is 'path/to/file:LocalName' " +
          "for top-level symbols and 'path/to/file:ClassName.method' for " +
          "methods. Drop the .py extension; forward slashes on all OSes. " +
          "Round-trip qnames returned by `grep` or `trie_trace` verbatim.",
      ),
  },
  async execute(args, context) {
    const proc = Bun.spawn(["trie", "read", "--json", args.qname], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) {
      return stdout || "(empty response from trie)"
    }
    throw new Error(
      `trie read failed (exit ${code}): ${stderr.trim() || "no stderr"}`,
    )
  },
})
"""
    )


def _render_opencode_trie_trace(_project_root: Path) -> str:
    """Render `.opencode/tools/trie_trace.ts` — exposes `trie trace` to the agent.

    No built-in collision; this is purely additive. Gives the agent a
    direct tool entry for "trace the call graph from a symbol N hops out"
    instead of relying on the MCP-namespaced `mcp__trie__trace` (which is
    longer to type and visually noisy).
    """
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Trace the call graph outward from a symbol up to `depth` hops. " +
    "Returns the root, every reachable node within depth, and the directed " +
    "edges between them. Use to understand a change's blast radius (callers) " +
    "or what a function ends up doing (callees). For prose on any specific " +
    "node, follow up with `trie_read` on that qname.",
  args: {
    qname: tool.schema
      .string()
      .describe(
        "Fully-qualified symbol name to trace from. Same format as " +
          "`trie_read`'s qname argument.",
      ),
    direction: tool.schema
      .string()
      .optional()
      .describe(
        "Which direction to traverse: 'callers' (default), 'callees', or 'both'.",
      ),
    depth: tool.schema
      .number()
      .optional()
      .describe(
        "Maximum BFS depth. Defaults to 2. Clamped server-side by the " +
          "trace_max_depth config knob.",
      ),
  },
  async execute(args, context) {
    const flags: string[] = ["trace", "--json", args.qname]
    if (args.direction) flags.push("--direction", args.direction)
    if (args.depth !== undefined) flags.push("--depth", String(args.depth))

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) {
      return stdout || "(empty response from trie)"
    }
    throw new Error(
      `trie trace failed (exit ${code}): ${stderr.trim() || "no stderr"}`,
    )
  },
})
"""
    )


# ---------------------------------------------------------------------------
# Claude Code: PreToolUse advisory hook on `Grep`.
# ---------------------------------------------------------------------------


def _render_claude_code_hooks_json(_project_root: Path) -> str:
    """Render `.claude/hooks/trie-tools.json` — advisory hook on the built-in Grep.

    Claude Code has no tool-override surface comparable to opencode's. The
    closest mechanism is a `PreToolUse` hook that fires before every tool
    call and can emit a `systemMessage` Claude sees on its next turn. We
    use it for advisory steering only: every time Claude reaches for the
    built-in `Grep`, the hook injects a one-line tip pointing at
    `mcp__trie__grep`. Claude's call is allowed (no permissionDecision), so
    nothing breaks; we just nudge the model toward the trie tool on the
    next round.

    We don't try to intercept Read or Glob — their semantics are too
    different from trie's read/trace, and false positives on those would
    block legitimate file reads.

    The hook calls `echo` with a JSON payload on stdout. Claude Code reads
    the `systemMessage` field and shows it to the model. We keep the
    message short and instruction-shaped because system reminders are
    consumed every turn the hook fires; a long message would burn context.
    """
    # The hook file lands at `.claude/hooks/trie-tools.json`. Claude Code
    # also accepts hook configuration in settings.json, but a dedicated
    # file is easier to remove (delete the file → no more nudging) and
    # easier to detect for idempotency on re-runs of `trie setup`.
    import json as _json

    body = {
        "_comment": (
            "Auto-generated by `trie setup --override-builtins`. Do not hand-edit — "
            "re-running setup will overwrite this file. Delete it to opt out of "
            "the advisory hook."
        ),
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Grep",
                    "hooks": [
                        {
                            "type": "command",
                            "command": (
                                'echo \'{"systemMessage":"For symbol or '
                                "code-structure queries, prefer mcp__trie__grep "
                                "(or `trie grep --json` from a shell): it "
                                "searches the indexed symbol graph and falls "
                                "back to ripgrep against in-scope source "
                                "bodies, attributing hits to enclosing "
                                "symbols. Use built-in Grep only when you "
                                "specifically need raw line-level matches.\"}'"
                            ),
                        }
                    ],
                }
            ]
        },
    }
    return _json.dumps(body, indent=2) + "\n"


# ---------------------------------------------------------------------------
# Target registry.
# ---------------------------------------------------------------------------

# Every name MUST also exist in `trie.mcp_install.TARGETS` so `trie setup` can
# pair MCP / hook / tool-override install under one target slug.
TARGETS: dict[str, ToolOverrideTarget] = {
    "opencode": ToolOverrideTarget(
        name="opencode",
        display_name="opencode",
        summary=(
            "Override built-in `grep` with a wrapper that calls `trie grep`. "
            "Also add `trie_read` and `trie_trace` as new tools (no built-in "
            "collision). The agent will route every grep through trie and "
            "see trie_read / trie_trace alongside its existing tools."
        ),
        files=(
            FileToWrite(
                relative_path=(".opencode", "tools", "grep.ts"),
                render=_render_opencode_grep_override,
                description="override built-in `grep` (routes to `trie grep`)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "trie_read.ts"),
                render=_render_opencode_trie_read,
                description="add `trie_read` (read a symbol by qname)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "trie_trace.ts"),
                render=_render_opencode_trie_trace,
                description="add `trie_trace` (trace the call graph)",
            ),
        ),
    ),
    "claude-code": ToolOverrideTarget(
        name="claude-code",
        display_name="Claude Code",
        summary=(
            "Install a PreToolUse advisory hook that emits a system reminder "
            "every time Claude reaches for built-in `Grep`, nudging the model "
            "toward `mcp__trie__grep`. Claude Code has no full tool-override "
            "surface, so this is the strongest available steer. Non-blocking — "
            "Grep still works; the agent just sees the tip."
        ),
        files=(
            FileToWrite(
                relative_path=(".claude", "hooks", "trie-tools.json"),
                render=_render_claude_code_hooks_json,
                description="advisory PreToolUse hook on built-in `Grep`",
            ),
        ),
    ),
    "claude-desktop": ToolOverrideTarget(
        name="claude-desktop",
        display_name="Claude Desktop",
        summary="",
        manual_instructions=(
            "Claude Desktop exposes no tool-override mechanism. Use the trie "
            "MCP server (already registered by `trie setup`) and prefer "
            "`mcp__trie__grep` / `mcp__trie__read` / `mcp__trie__trace` over "
            "the built-in tools manually."
        ),
    ),
    "cursor": ToolOverrideTarget(
        name="cursor",
        display_name="Cursor",
        summary="",
        manual_instructions=(
            "Cursor has no documented tool-override mechanism. Use the trie "
            "MCP server (already registered by `trie setup`) and the `trie "
            "grep` / `trie read` / `trie trace` CLI commands from the "
            "terminal when you want the symbol-aware path."
        ),
    ),
    "windsurf": ToolOverrideTarget(
        name="windsurf",
        display_name="Windsurf",
        summary="",
        manual_instructions=(
            "Windsurf has no documented tool-override mechanism. Use the trie "
            "MCP server and the `trie` CLI commands directly."
        ),
    ),
    "vscode": ToolOverrideTarget(
        name="vscode",
        display_name="VS Code",
        summary="",
        manual_instructions=(
            "VS Code's MCP integration has no tool-override mechanism. Use "
            "the trie MCP server and the `trie` CLI commands directly."
        ),
    ),
    "codex": ToolOverrideTarget(
        name="codex",
        display_name="Codex CLI",
        summary="",
        manual_instructions=(
            "Codex CLI has no documented tool-override mechanism. Use the "
            "trie MCP server and the `trie` CLI commands directly."
        ),
    ),
}


# ---------------------------------------------------------------------------
# Application logic.
# ---------------------------------------------------------------------------


@dataclass
class ToolOverrideInstallPlan:
    """Aggregate result of a full `install` call across one or more targets."""

    target_names: list[str]
    print_only: bool
    dry_run: bool
    results: list[ToolOverrideApplyResult] = field(default_factory=list)


def install(
    *,
    target_names: list[str] | None,
    print_only: bool,
    dry_run: bool,
    project_root: Path,
) -> ToolOverrideInstallPlan:
    """Apply tool-override files for one or more targets.

    Symmetric with `mcp_install.install` and `hook_install.install`: same
    flag semantics, same return-shape philosophy. Unknown target names
    raise `ToolOverrideInstallError`.

    Unlike the other installers, there's no `install_all`: tool overrides
    are explicit per harness and we don't want a multi-target rollout to
    happen by accident. The CLI is expected to drive this with the
    `target_names` from a prior `mcp_install` plan, after the user has
    consented via the interactive prompt.
    """
    if not target_names:
        raise ToolOverrideInstallError(
            "tool-override install requires explicit target names; pass --target."
        )

    chosen: list[ToolOverrideTarget] = []
    for name in target_names:
        if name not in TARGETS:
            raise ToolOverrideInstallError(
                f"unknown tool-override target: {name!r}. Known: {', '.join(TARGETS)}"
            )
        chosen.append(TARGETS[name])

    plan = ToolOverrideInstallPlan(
        target_names=[t.name for t in chosen],
        print_only=print_only,
        dry_run=dry_run,
    )
    for target in chosen:
        plan.results.append(apply_one(target, project_root, print_only, dry_run))
    return plan


def apply_one(
    target: ToolOverrideTarget,
    project_root: Path,
    print_only: bool,
    dry_run: bool,
    *,
    scope: Scope = "project",
) -> ToolOverrideApplyResult:
    """Install (or preview) every override file for one target.

    Each file in `target.files` is rendered, compared against any existing
    contents at its path, and written when content differs. Per-file
    results land in the returned `ToolOverrideApplyResult.files` list so
    the CLI can show which individual overrides changed.

    `scope` is accepted for API symmetry but currently unused: override
    files always live under the project (a user-scope override would have
    to know which project to target).
    """
    _ = scope  # reserved
    if not target.files:
        return ToolOverrideApplyResult(
            target=target.name,
            action="needs_manual_setup",
            detail=target.manual_instructions
            or f"{target.display_name} has no automated tool-override path in this trie version.",
        )

    file_results: list[ToolOverrideFileResult] = []
    for spec in target.files:
        file_results.append(_apply_file(spec, project_root, print_only, dry_run))

    # Summarise the per-file actions into one target-level action so the
    # rendered report can lead with a single status verb. Precedence:
    # error > created/updated > preview > skipped.
    actions = {r.action for r in file_results}
    if "error" in actions:
        top_action: Action = "error"
    elif "created" in actions:
        top_action = "created"
    elif "updated" in actions:
        top_action = "updated"
    elif "preview" in actions:
        top_action = "preview"
    else:
        top_action = "skipped"

    return ToolOverrideApplyResult(
        target=target.name,
        action=top_action,
        files=file_results,
    )


def _apply_file(
    spec: FileToWrite,
    project_root: Path,
    print_only: bool,
    dry_run: bool,
) -> ToolOverrideFileResult:
    """Materialise one override file, with idempotency check.

    Same write semantics as `hook_install.apply_one`: if the file exists
    with identical contents, return `skipped`; if it exists with different
    contents, overwrite (the user opted in by re-running setup); if
    `--print-only` or `--dry-run`, return `preview` without touching the
    disk.
    """
    contents = spec.render(project_root)
    target_path = project_root.joinpath(*spec.relative_path)
    rel_str = str(Path(*spec.relative_path))

    if print_only:
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="preview",
            path=target_path,
            description=spec.description,
            detail=contents,
        )

    existed_before = target_path.exists()
    if existed_before:
        try:
            current = target_path.read_text()
        except OSError as exc:
            return ToolOverrideFileResult(
                relative_path=rel_str,
                action="error",
                path=target_path,
                description=spec.description,
                detail=f"could not read existing file: {exc}",
            )
        if current == contents:
            return ToolOverrideFileResult(
                relative_path=rel_str,
                action="skipped",
                path=target_path,
                description=spec.description,
                detail="already installed with the same contents",
            )

    if dry_run:
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="preview",
            path=target_path,
            description=spec.description,
            detail=contents,
        )

    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(contents)
    return ToolOverrideFileResult(
        relative_path=rel_str,
        action="updated" if existed_before else "created",
        path=target_path,
        description=spec.description,
    )
