"""Tool-override installation: replace an agent's built-in tools with trie wrappers.

Companion to `mcp_install.py` and `hook_install.py`. Where `mcp_install` makes
trie available to an agent and `hook_install` makes it automatic, this module
makes trie *unavoidable* — it replaces or supplements the agent's built-in
tools so the agent reaches for trie reflexively, not just when prompted.

NOTE — trie-native opencode fork: the `computer-reinvention/opencode` fork
ships the trie tools as first-class native tools (`trie_*`), demotes the stock
file tools to backup, and injects the trie usage guide into its system prompt
(see `docs/core/trie-tool-extensions.md` and the fork's
`packages/opencode/src/tool/trie/`). On that fork these injected `.opencode/
tools/*.ts` wrappers are REDUNDANT — they duplicate native tools. When
installing against the fork, prefer MCP registration + the refresh hook only,
and skip the tool-override files (delete `.opencode/tools/*.ts` if present).
Stock upstream opencode still needs the wrappers below; that path is unchanged.

The interception story differs per harness:

- **opencode** supports drop-in tool replacement via `.opencode/tools/<name>.ts`.
  A custom tool whose filename matches a built-in name takes precedence over
  the built-in. We override `grep` (symbol-aware search) and `read`
  (triefact-first dispatch on qname vs path with a `show_source` escape
  hatch), and add `trace` as a new tool for graph traversal (no built-in
  collision).
- **Claude Code** has no tool-override surface. The closest mechanism is a
  `PreToolUse` hook that fires before each built-in tool call and can emit a
  `systemMessage` Claude sees on its next turn. We use it for advisory
  steering on `Grep` only: "for symbol queries, prefer mcp__trie__grep".

Other harnesses don't have a documented interception path; they get a
`needs_manual_setup` result that explains the situation.

This is opt-in. `trie setup` prompts before writing any override files; the
user must say yes. The generated files carry the same "generated by, do not
hand-edit" notice as the hook plugin so re-running setup picks up
content drift, and the user can delete a file to opt back out.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from trie.mcp_install import Scope

Action = Literal["created", "updated", "skipped", "preview", "error", "needs_manual_setup"]


class ToolOverrideInstallError(Exception):
    pass


@dataclass(frozen=True)
class FileToWrite:
    """One file an override target needs on disk.

    A target may need several files: e.g. opencode needs `grep.ts` and
    `read.ts` (built-in overrides) plus `trace.ts` (addition). Each is
    rendered independently with its own idempotency check, so a partial
    failure on one file doesn't roll back the others.
    """

    relative_path: tuple[str, ...]
    render: Callable[[Path], str]
    description: str  # short label for the human-readable report


@dataclass(frozen=True)
class ToolOverrideApplyResult:
    """Outcome of installing override files for one target.

    `files` carries per-file results so the CLI can report which individual
    overrides landed and which were skipped. The top-level `action` summarises
    across files: if any file errored, action is "error"; if all skipped,
    "skipped"; otherwise "created"/"updated" reflecting the highest-energy
    change.
    """

    target: str
    action: Action
    files: list[ToolOverrideFileResult] = field(default_factory=list)
    detail: str = ""


@dataclass(frozen=True)
class ToolOverrideFileResult:
    """Per-file outcome inside a target's apply result."""

    relative_path: str
    action: Action
    path: Path | None
    description: str
    detail: str = ""


@dataclass(frozen=True)
class ToolOverrideTarget:
    """Static description of an agent's tool-override surface.

    `files` is the list of override files to write. Empty list means the
    target has no automatable override path; `apply_one` returns
    `needs_manual_setup` with `manual_instructions` for the user.

    `obsolete_files` is the list of paths to delete on apply if they
    exist — for cleaning up files that prior versions of `trie setup`
    wrote but newer versions no longer need (e.g. when a separate
    `trie_read.ts` tool was subsumed by an override of `read.ts`).
    The cleanup is silent: an obsolete file that doesn't exist is a
    no-op, and a successful delete is reported as part of the apply
    result so users know the migration happened.
    """

    name: str
    display_name: str
    files: tuple[FileToWrite, ...] = ()
    obsolete_files: tuple[tuple[str, ...], ...] = ()
    manual_instructions: str = ""
    # Human-readable one-line description of what installing for this target
    # actually does. Used in the interactive prompt so the user knows what
    # they're consenting to.
    summary: str = ""


# ---------------------------------------------------------------------------
# opencode: override `grep` and `read`, add `trace`.
# ---------------------------------------------------------------------------


_GENERATED_HEADER = """// Auto-generated by `trie setup --override-builtins`. Do not hand-edit —
// re-running setup will overwrite this file. Delete the file to opt out of
// the override; trie setup won't recreate it without explicit consent.
//
// See https://opencode.ai/docs/custom-tools for the custom-tools API.
"""


def _render_opencode_grep_override(_project_root: Path) -> str:
    """Render `.opencode/tools/grep.ts` — overrides opencode's built-in `grep`.

    The file ships under the same filename as the built-in tool. Opencode's
    rule (documented at opencode.ai/docs/custom-tools): a default-exported
    custom tool whose filename matches a built-in takes precedence over the
    built-in. So once this file lands, every `grep` call from the agent
    routes through trie's `grep` instead of opencode's regex-over-files
    grep.

    Args are intentionally close to opencode's built-in grep so the agent
    doesn't have to relearn the call shape: `pattern` is the substring to
    search for (mapped to trie's `name_contains` predicate), `path` becomes
    `scope_prefix`, `include` is rejected (trie's scope is config-driven,
    not per-call). The wrapper shells out to `trie grep` and returns the
    plain-text output directly — no JSON parsing, no format overhead.

    `Bun.spawn` is what's used by the existing `trie-refresh.ts` plugin in
    this directory, so we know the runtime supports it. Errors from `trie`
    are bubbled up so the agent sees them on the next turn.
    """
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Search for symbols and source-body text via trie. Replaces opencode's " +
    "built-in grep with a symbol-aware search that returns signatures, " +
    "one-liners, and call-graph metrics as plain text — and falls back to " +
    "ripgrep against indexed source bodies when the query doesn't match a " +
    "symbol name.",
  args: {
    pattern: tool.schema
      .string()
      .describe(
        "Substring to search for. Mapped to trie's `name_contains` " +
          "predicate; case-insensitive, matched against symbol local names. " +
          "If no symbol matches, trie's text-match fallback searches in-scope " +
          "source bodies and attributes hits to enclosing symbols; when name " +
          "matches are sparse, body/prose-matched candidates are appended " +
          "under 'related by prose'.",
      ),
    path: tool.schema
      .string()
      .optional()
      .describe(
        "Path prefix to restrict the search to (e.g. 'src/' or 'trie/sync/'). " +
          "Maps to trie's `scope_prefix` predicate.",
      ),
    kind: tool.schema
      .string()
      .optional()
      .describe(
        "Restrict to one symbol kind: 'function', 'class', 'method', or 'any'.",
      ),
    public_only: tool.schema
      .boolean()
      .optional()
      .describe("If true, exclude symbols whose name starts with an underscore."),
    rank_by: tool.schema
      .string()
      .optional()
      .describe(
        "Result ordering: 'public_first' (default), 'inbound_count' " +
          "(centrality), or 'alphabetical'.",
      ),
    limit: tool.schema
      .number()
      .optional()
      .describe("Maximum number of hits to return. Defaults to 10."),
  },
  async execute(args, context) {
    const flags: string[] = ["grep", "--name", args.pattern]
    if (args.path) flags.push("--scope-prefix", args.path)
    if (args.kind) flags.push("--kind", args.kind)
    if (args.public_only) flags.push("--public-only")
    if (args.rank_by) flags.push("--rank-by", args.rank_by)
    if (args.limit !== undefined) flags.push("--limit", String(args.limit))

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])

    // Exit code 1 is a tool-level error (e.g. invalid predicate); the JSON
    // envelope on stdout carries the structured error. Code 2 is a CLI
    // usage error from trie itself. Anything else is unexpected.
    if (code === 0 || code === 1) {
      return stdout || "(empty response from trie)"
    }
    throw new Error(
      `trie grep failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`,
    )
  },
})
"""
    )


def _render_opencode_read_override(_project_root: Path) -> str:
    """Render `.opencode/tools/read.ts` — overrides opencode's built-in `read`.

    The override dispatches on the argument shape so a single tool call
    serves three distinct intents the agent has:

    1. **Symbol read (qname)**: arg looks like a qname
       (`path/to/file:Name` — contains `:`, not a URL scheme, not a
       Windows drive prefix).     Routes to `trie read <qname>` and
       returns the standard trie envelope: signature, prose, source
       pointer, callers, callees. This is the "I have a specific symbol
       in mind, show me its prose and immediate neighbours" path.

    2. **File-as-triefact**: arg is a plain file path AND a triefact
       exists for it at `triefacts/<path>.md`. Returns either the
       compact view (default) or an agent-trimmed full view (`full:
       true`). The full view strips trie's internal frontmatter
       (`trie_version`, `file_fingerprint`, `last_synced_at`, `source`)
       and every `<!-- trie:section ... -->` / `<!-- trie:end -->`
       sentinel — including the fingerprints they carry — keeping only
       the agent-relevant frontmatter keys (`description`, `defines`,
       `incoming_refs`, `outgoing_refs`) and the section bodies as
       plain Markdown. The agent gets trie's synthesised view trie
       already paid LLM cost to produce, with none of the machinery
       noise.

    3. **Source fallthrough**: `show_source: true` OR the path has no
       triefact OR `offset`/`limit` were passed (the agent wants raw
       line ranges, which are meaningless against triefact prose). The
       wrapper shells out to a small `cat`-equivalent so the agent sees
       the raw file bytes. This is the "I'm about to edit this and
       need exact source" escape hatch.

    Detection rule for qname vs path: any string containing `:` (and
    not a URL scheme like `https://` or Windows drive prefix like
    `C:\\`) is treated as a qname. This is intentionally permissive —
    qnames have a stable `path/to/file:Name` shape; on the rare chance
    a real file is named with a colon, the agent can pass
    `show_source: true` to escape.

    The triefact lookup uses the default `triefacts/` root. Projects
    that have configured a different `triefacts.root` in trie.toml
    will fall through to source for path reads — a known limitation
    with a graceful failure mode.
    """
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"
import { readFile, stat, appendFile } from "node:fs/promises"
import { join, normalize, isAbsolute } from "node:path"

// Conservative qname detection: an argument is a qname when it contains
// `:` but is NOT a URL (scheme://...) and NOT a Windows drive prefix
// (^[A-Za-z]:[\\\\/]). Real qnames have shape `path/to/file:Name` or
// `path/to/file:Class.method` — colon-bearing strings with at least one
// slash and no URL/drive markers.
function looksLikeQname(s: string): boolean {
  if (!s.includes(":")) return false
  if (/^[A-Za-z][A-Za-z0-9+.-]*:\\/\\//.test(s)) return false  // URL scheme
  if (/^[A-Za-z]:[\\\\/]/.test(s)) return false                  // Windows drive
  return true
}

// --- Telemetry --------------------------------------------------------------
// The read override has three code paths that don't shell out to `trie`
// (triefact lookup, source fallthrough, show_source). Without TS-side
// telemetry those calls would be invisible to `trie audit`, which would
// only see the qname path. We emit `cli_call` events from here that mirror
// the shape Python emits, so the audit aggregator buckets them the same
// way regardless of which surface (CLI subprocess or in-process TS wrapper)
// produced them.

interface TelemetryConfig {
  enabled: boolean
  logPath: string | null  // absolute path to debug.jsonl, or null when off
  captureArgs: boolean
  captureResponses: boolean
}

// Cache the resolved config per (cwd) so we parse trie.toml at most once
// per project root over the wrapper's lifetime. The cwd-keyed map handles
// the unusual case of opencode being driven against multiple projects in
// one session.
const telemetryConfigCache = new Map<string, TelemetryConfig>()

function resolveTelemetryConfig(cwd: string): TelemetryConfig {
  const cached = telemetryConfigCache.get(cwd)
  if (cached !== undefined) return cached
  const cfg = computeTelemetryConfig(cwd)
  telemetryConfigCache.set(cwd, cfg)
  return cfg
}

function computeTelemetryConfig(cwd: string): TelemetryConfig {
  // Defaults match Python's behaviour when no config is present: off.
  const off: TelemetryConfig = {
    enabled: false,
    logPath: null,
    captureArgs: true,
    captureResponses: false,
  }

  // Parse trie.toml's [debug] section. Hand-rolled because we don't want
  // to drag a TOML parser dep into the .opencode/ package just for four
  // string/bool fields with a known schema. If the file is missing or
  // unreadable, fall back to env-var-only mode.
  let toml = ""
  try {
    toml = require("node:fs").readFileSync(join(cwd, "trie.toml"), "utf-8")
  } catch {
    // No trie.toml; honour TRIE_DEBUG anyway (see below).
  }
  const debugSection = extractTomlSection(toml, "debug")

  let enabled = parseBool(debugSection["enabled"]) ?? false
  let logPath = parseString(debugSection["log_path"]) ?? "debug.jsonl"
  const captureArgs = parseBool(debugSection["capture_args"]) ?? true
  const captureResponses = parseBool(debugSection["capture_responses"]) ?? false

  // Env var wins (mirrors Python's precedence): `TRIE_DEBUG=1` enables
  // with the default path; `TRIE_DEBUG=/some/path` enables with that path;
  // `TRIE_DEBUG=0` force-disables; anything else enables at default.
  const env = process.env.TRIE_DEBUG
  if (env !== undefined) {
    if (env === "0" || env === "" || env.toLowerCase() === "false") {
      return { ...off, captureArgs, captureResponses }
    }
    enabled = true
    if (env !== "1" && env.toLowerCase() !== "true") {
      logPath = env
    }
  }

  if (!enabled) {
    return { ...off, captureArgs, captureResponses }
  }

  // Resolve logPath: absolute → use as-is; relative → resolve against
  // project root (cwd). Matches what `trie/telemetry.py` does.
  const resolvedPath = isAbsolute(logPath) ? logPath : join(cwd, logPath)
  return { enabled: true, logPath: resolvedPath, captureArgs, captureResponses }
}

function extractTomlSection(toml: string, section: string): Record<string, string> {
  // Minimal TOML section extractor. Walks lines; tracks the current
  // section header; collects `key = value` pairs from `[section]`.
  // Skips comments and blank lines. Strings, bools, and numbers come
  // back as their raw string form so the caller can parse per-key.
  // Doesn't handle multi-line strings, arrays, or nested tables —
  // none of which we use in [debug].
  const out: Record<string, string> = {}
  let inSection = false
  for (const raw of toml.split(/\\r?\\n/)) {
    const line = raw.replace(/(^|\\s)#.*$/, "").trim()
    if (line === "") continue
    const header = /^\\[([^\\]]+)\\]$/.exec(line)
    if (header !== null) {
      inSection = header[1].trim() === section
      continue
    }
    if (!inSection) continue
    const kv = /^([A-Za-z_][A-Za-z0-9_]*)\\s*=\\s*(.+)$/.exec(line)
    if (kv === null) continue
    out[kv[1]] = kv[2].trim()
  }
  return out
}

function parseBool(raw: string | undefined): boolean | null {
  if (raw === undefined) return null
  const v = raw.toLowerCase()
  if (v === "true") return true
  if (v === "false") return false
  return null
}

function parseString(raw: string | undefined): string | null {
  if (raw === undefined) return null
  // Strip surrounding quotes if present (single or double).
  const m = /^["']([\\s\\S]*)["']$/.exec(raw)
  return m !== null ? m[1] : raw
}

interface TelemetryEvent {
  event: string
  tool: string
  mode: string  // "qname" | "triefact" | "source" | "show_source"
  result_kind: "ok" | "error"
  duration_ms: number
  response_bytes?: number
  args?: Record<string, unknown>
  error?: string
}

async function emitTelemetry(cwd: string, evt: TelemetryEvent): Promise<void> {
  // Telemetry is best-effort: any failure here (no config, no log path,
  // permission denied, disk full, etc.) is swallowed silently. The wrapper
  // must never crash the agent's turn over an observability concern.
  try {
    const cfg = resolveTelemetryConfig(cwd)
    if (!cfg.enabled || cfg.logPath === null) return
    const payload: Record<string, unknown> = {
      ts: new Date().toISOString(),
      ...evt,
    }
    if (!cfg.captureArgs && "args" in payload) {
      delete payload.args
    }
    await appendFile(cfg.logPath, JSON.stringify(payload) + "\\n", "utf-8")
  } catch {
    // Swallow. Nothing we can usefully do here.
  }
}

// --- I/O helpers ------------------------------------------------------------

async function shellOutToTrie(
  flags: string[],
  cwd: string,
): Promise<string> {
  const proc = Bun.spawn(["trie", ...flags], {
    cwd,
    stdout: "pipe",
    stderr: "pipe",
  })
  const [stdout, stderr, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ])
  // 0 = success, 1 = structured error envelope (e.g. not_found).
  // Both produce useful JSON on stdout that the agent can consume.
  if (code === 0 || code === 1) {
    return stdout || "(empty response from trie)"
  }
  throw new Error(`trie failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
}

function resolveAbsolutePath(cwd: string, path: string): string {
  // Agents sometimes pass absolute paths (e.g. when copy-pasting from a
  // grep result or a stack trace). Without this branch, `join(cwd, path)`
  // produces `<cwd>/<abs-path-with-leading-slash-stripped>` — the literal
  // Node behaviour for `path.join` with an absolute second arg, which is
  // almost always wrong. Detect absolute paths and use them verbatim;
  // relative paths land under cwd as before.
  return isAbsolute(path) ? normalize(path) : normalize(join(cwd, path))
}

function projectRelativePath(cwd: string, path: string): string | null {
  // Triefact lookup needs a path *relative to the project root*. When
  // the agent passes an absolute path that lives inside the project
  // tree, strip the cwd prefix and look up the triefact under the
  // resulting relative path. When the absolute path is outside the
  // project tree, return null — there's no triefact for files we
  // didn't sync, and the caller should fall through to source.
  if (!isAbsolute(path)) return path
  const cwdNorm = normalize(cwd)
  const absNorm = normalize(path)
  // Path must start with cwd + separator. Use endsWith-slash check to
  // avoid matching siblings like `/Users/foo-bar` from `/Users/foo`.
  const prefix = cwdNorm.endsWith("/") ? cwdNorm : cwdNorm + "/"
  if (!absNorm.startsWith(prefix)) return null
  return absNorm.slice(prefix.length)
}

async function readSourceFile(
  cwd: string,
  path: string,
  offset?: number,
  limit?: number,
): Promise<string> {
  // Resolve the path: absolute paths are used verbatim; relative paths
  // land under cwd. No path-traversal guard — the agent already has free
  // reign over the project via the bash tool; this matches built-in
  // `read`'s permissiveness rather than imposing a stricter sandbox.
  const absPath = resolveAbsolutePath(cwd, path)
  const text = await readFile(absPath, "utf-8")
  if (offset === undefined && limit === undefined) {
    return text
  }
  // Honour line-range args the same way built-in read does: 1-indexed
  // `offset` is the first line to include; `limit` is the count.
  const lines = text.split("\\n")
  const start = offset !== undefined ? Math.max(0, offset - 1) : 0
  const end = limit !== undefined ? start + limit : lines.length
  return lines.slice(start, end).join("\\n")
}

async function readTriefact(cwd: string, path: string): Promise<string | null> {
  // Default triefact location: `<cwd>/triefacts/<rel>.md`. We swap the
  // source extension for `.md` (matching how the writer maps source →
  // triefact in trie/sync/single_file.py). Projects with a non-default
  // `triefacts.root` config won't be picked up here — we fall through
  // to source in that case rather than parsing trie.toml from TS.
  //
  // When the agent passes an absolute path, we strip the cwd prefix so
  // the triefact lookup still works for absolute paths inside the
  // project tree. Absolute paths outside the tree return null — there's
  // no triefact for files we didn't sync.
  const rel = projectRelativePath(cwd, path)
  if (rel === null) return null
  const dotIdx = rel.lastIndexOf(".")
  const stem = dotIdx > 0 ? rel.slice(0, dotIdx) : rel
  const triefactPath = join(cwd, "triefacts", stem + ".md")
  try {
    const s = await stat(triefactPath)
    if (!s.isFile()) return null
  } catch {
    return null  // ENOENT or any stat failure → no triefact
  }
  return readFile(triefactPath, "utf-8")
}

// --- Compact-mode triefact rendering ---------------------------------------
//
// Default `read(path)` returns a compact view: the file's `description` and
// ref counts (from the front matter), followed by one entry per symbol
// containing the qname, kind, lines, public flag, signature, and the first
// paragraph of the section body ("intro"). Agents probing "is this file
// relevant?" pay one-line-per-symbol budget; if they need a specific
// symbol's full prose they follow up with `read(qname)` or `read(path, full=true)`.
//
// Full mode (`full: true`) keeps the historical behaviour of returning the
// .md body verbatim — useful when the agent really does want every section's
// prose, e.g. for narrow files where the bundle fits in a turn.

interface FrontMatter {
  description?: string
  incoming_refs?: number
  outgoing_refs?: number
  defines: { qualified_name: string; kind: string; lines: string }[]
}

function parseFrontMatter(triefact: string): { fm: FrontMatter; rest: string } {
  // The writer always emits a `---\\n<yaml>\\n---\\n` block at the very start
  // of the file. We hand-parse the slice — only flat scalars and one
  // list-of-objects (`defines`) appear in this schema, so a TOML parser
  // or a YAML dep is overkill. Anything we don't recognise lands in the
  // rest of the file, untouched.
  const fm: FrontMatter = { defines: [] }
  if (!triefact.startsWith("---\\n")) return { fm, rest: triefact }
  const end = triefact.indexOf("\\n---\\n", 4)
  if (end === -1) return { fm, rest: triefact }
  const yaml = triefact.slice(4, end)
  const rest = triefact.slice(end + 5)

  // Walk lines. `defines:` opens a list block until the next dedented
  // top-level key. Within a list item, `- kind: ...` starts a new entry;
  // continuation lines (`  qualified_name: ...`, `  lines: ...`) extend
  // the current entry. Everything else is a flat scalar assignment.
  let inDefines = false
  let current: { qualified_name: string; kind: string; lines: string } | null = null
  for (const raw of yaml.split(/\\r?\\n/)) {
    const line = raw.replace(/\\s+$/, "")
    if (line === "") continue
    if (!line.startsWith(" ") && !line.startsWith("-")) {
      // Top-level key. Flush any in-progress defines entry.
      if (current !== null) {
        fm.defines.push(current)
        current = null
      }
      inDefines = false
      const m = /^([A-Za-z_][A-Za-z0-9_]*):\\s*(.*)$/.exec(line)
      if (m === null) continue
      const [, key, val] = m
      if (key === "defines") {
        inDefines = true
        continue
      }
      const stripped = val.replace(/^["']|["']$/g, "")
      if (key === "description") fm.description = stripped
      else if (key === "incoming_refs") fm.incoming_refs = Number(stripped) || 0
      else if (key === "outgoing_refs") fm.outgoing_refs = Number(stripped) || 0
    } else if (inDefines) {
      const trimmed = line.replace(/^\\s+/, "")
      if (trimmed.startsWith("- ")) {
        // New entry — flush previous.
        if (current !== null) fm.defines.push(current)
        current = { qualified_name: "", kind: "", lines: "" }
        const m = /^- ([A-Za-z_]+):\\s*(.*)$/.exec(trimmed)
        if (m !== null && current !== null) {
          const [, key, val] = m
          ;(current as Record<string, string>)[key] = val.replace(/^["']|["']$/g, "")
        }
      } else if (current !== null) {
        const m = /^([A-Za-z_]+):\\s*(.*)$/.exec(trimmed)
        if (m !== null) {
          const [, key, val] = m
          ;(current as Record<string, string>)[key] = val.replace(/^["']|["']$/g, "")
        }
      }
    }
  }
  if (current !== null) fm.defines.push(current)
  return { fm, rest }
}

interface SectionBody {
  qname: string
  signature: string  // first line of body, conventionally `## <signature>`
  intro: string      // first paragraph after the signature line
}

function extractSections(rest: string): Map<string, SectionBody> {
  // Sentinel format mirrors trie/sync/writer.py SECTION_OPEN_RE:
  //   <!-- trie:section symbol=<qname> fingerprint=<fp> [body_fp=<bfp>] [source_ref=<ref>] -->
  // We extract just `symbol=<qname>` per opening sentinel, find the
  // matching `<!-- trie:end -->`, and break the body into a signature
  // line + first-paragraph intro.
  const out = new Map<string, SectionBody>()
  const openRe =
    /<!--\\s*trie:section\\s+symbol=(\\S+)[^>]*-->[\\t ]*\\n/g
  const closeMarker = "<!-- trie:end -->"
  let m: RegExpExecArray | null
  while ((m = openRe.exec(rest)) !== null) {
    const qname = m[1]
    const bodyStart = m.index + m[0].length
    const closeIdx = rest.indexOf(closeMarker, bodyStart)
    if (closeIdx === -1) continue
    const body = rest.slice(bodyStart, closeIdx).trimEnd()
    out.set(qname, parseSectionBody(qname, body))
  }
  return out
}

function parseSectionBody(qname: string, body: string): SectionBody {
  // Body convention: first line is `## <signature>` (the markdown
  // header carrying the symbol's signature); a blank line follows;
  // then the prose. The first paragraph (= up to the next blank line)
  // is the intro. The signature line strips the leading `## ` and the
  // intro is paragraph-1 trimmed.
  const lines = body.split("\\n")
  let signature = ""
  let i = 0
  if (lines.length > 0 && lines[0].startsWith("## ")) {
    signature = lines[0].slice(3).trim()
    i = 1
  }
  // Skip blank lines after the signature.
  while (i < lines.length && lines[i].trim() === "") i++
  // Collect lines until the next blank line.
  const introLines: string[] = []
  while (i < lines.length && lines[i].trim() !== "") {
    introLines.push(lines[i])
    i++
  }
  return { qname, signature, intro: introLines.join("\\n").trim() }
}

function renderCompact(triefact: string, path: string): string {
  const { fm, rest } = parseFrontMatter(triefact)
  const sections = extractSections(rest)
  const out: string[] = []
  out.push(`# ${path} (compact triefact view)`)
  if (fm.description) out.push(`description: ${fm.description}`)
  const refsParts: string[] = []
  if (fm.incoming_refs !== undefined) refsParts.push(`incoming_refs: ${fm.incoming_refs}`)
  if (fm.outgoing_refs !== undefined) refsParts.push(`outgoing_refs: ${fm.outgoing_refs}`)
  if (refsParts.length > 0) out.push(refsParts.join(" · "))
  out.push("")
  out.push(`Symbols (${fm.defines.length}). Use \\`read(<qname>)\\` for full prose, ` +
    `or \\`read(<path>, full=true)\\` for the full file bundle.`)
  out.push("")
  for (const entry of fm.defines) {
    const sec = sections.get(entry.qualified_name)
    const isPublic = !entry.qualified_name.split(":").pop()?.startsWith("_") ||
      isDunder(entry.qualified_name.split(":").pop() || "")
    out.push(
      `## ${entry.qualified_name} (${entry.kind}, lines ${entry.lines}` +
        `${isPublic ? "" : ", private"})`,
    )
    if (sec?.signature) out.push(`signature: \\`${sec.signature}\\``)
    if (sec?.intro) {
      out.push("")
      out.push(sec.intro)
    }
    out.push("")
  }
  return out.join("\\n")
}

function isDunder(name: string): boolean {
  return name.startsWith("__") && name.endsWith("__") && name.length > 4
}

// --- Full-mode triefact rendering (agent-trimmed) --------------------------
//
// `full: true` historically returned the raw `.md` bytes — frontmatter +
// every sentinel with its fingerprints. None of that machinery is useful
// to the agent. `renderForAgent` strips it down to the agent-facing
// surface: a frontmatter block containing only the keys an agent can act
// on (description, defines, incoming_refs, outgoing_refs) and the section
// bodies with their `<!-- trie:section ... -->` / `<!-- trie:end -->`
// sentinels removed. Inter-section prose is preserved verbatim.
//
// Kept in lockstep with Python's `trie.sync.writer.render_for_agent` —
// the two MUST emit equivalent output for the same input so the agent
// surface is consistent whether it goes through MCP or the read override.

function renderFrontMatterForAgent(fm: FrontMatter): string {
  // Emit only the agent-facing keys, in the order Python's helper uses
  // (description, defines, incoming_refs, outgoing_refs). Missing keys
  // are dropped. If nothing's left, return empty string so the caller
  // can omit the `---/---` block entirely.
  const lines: string[] = []
  if (fm.description !== undefined) {
    lines.push(`description: ${quoteYamlScalar(fm.description)}`)
  }
  if (fm.defines.length > 0) {
    lines.push("defines:")
    for (const entry of fm.defines) {
      lines.push(`- kind: ${entry.kind}`)
      lines.push(`  qualified_name: ${entry.qualified_name}`)
      lines.push(`  lines: ${quoteYamlScalar(entry.lines)}`)
    }
  }
  if (fm.incoming_refs !== undefined) {
    lines.push(`incoming_refs: ${fm.incoming_refs}`)
  }
  if (fm.outgoing_refs !== undefined) {
    lines.push(`outgoing_refs: ${fm.outgoing_refs}`)
  }
  if (lines.length === 0) return ""
  return lines.join("\\n") + "\\n"
}

function quoteYamlScalar(value: string): string {
  // PyYAML's safe_dump emits unquoted scalars when the value is plain
  // (no leading sigils, no embedded special chars). For the small set
  // of values we emit here (descriptions, qnames, line ranges), an
  // unquoted form is safe in nearly all cases. We only single-quote
  // when the value starts with a char YAML treats specially.
  if (value === "") return "''"
  const first = value[0]
  if ("!&*?|>%@\\`#-:[]{},".includes(first)) {
    return `'${value.replace(/'/g, "''")}'`
  }
  return value
}

function stripSentinels(rest: string): string {
  // Remove both open and close sentinel lines (each on their own line)
  // from `rest`. The regex anchors at line start/end so sentinel-shaped
  // text inside fenced code blocks is left alone — same anchoring rule
  // as the Python parser. Collapse any run of 3+ blank lines down to a
  // single blank line so the output reads as continuous Markdown.
  const openRe = /^<!--\\s*trie:section\\s+[^>]*-->[\\t ]*\\r?\\n?/gm
  const closeRe = /^<!--\\s*trie:end\\s*-->[\\t ]*\\r?\\n?/gm
  let out = rest.replace(openRe, "").replace(closeRe, "")
  // Collapse runs of 3+ newlines to exactly 2 (one blank line).
  out = out.replace(/\\n{3,}/g, "\\n\\n")
  return out
}

function renderForAgent(triefact: string): string {
  const { fm, rest } = parseFrontMatter(triefact)
  const fmBlock = renderFrontMatterForAgent(fm)
  const body = stripSentinels(rest).replace(/^\\s+/, "")
  if (fmBlock === "") return body
  return `---\\n${fmBlock}---\\n${body}`
}

export default tool({
  description:
    "Read source code or trie's synthesised description of it. Replaces " +
    "opencode's built-in `read` with a triefact-first wrapper that maximises " +
    "context per token: " +
    "(1) when `path` is a qualified symbol name like `pkg/module:Name`, returns " +
    "the symbol's prose plus its callers/callees from the trie graph; " +
    "(2) when `path` is a regular file path and a triefact exists at " +
    "`triefacts/<path>.md`, returns a COMPACT view by default — file " +
    "description, ref counts, and one entry per symbol with its qname, kind, " +
    "lines, signature, and a first-paragraph intro. Pass `full: true` to get " +
    "every section's full prose (with trie's internal frontmatter and " +
    "section sentinels stripped); " +
    "(3) when `show_source: true`, or no triefact exists, or `offset`/`limit` " +
    "are passed for a line-range read, returns the raw source verbatim. " +
    "Default flow for understanding a file: read in compact mode to see " +
    "what's there, then `read(<qname>)` on the specific symbol that matters " +
    "(or `read(<path>, full=true)` for the whole bundle). Use " +
    "`show_source: true` right before editing when you need exact source. " +
    "Both relative paths and absolute paths are accepted.",
  args: {
    path: tool.schema
      .string()
      .describe(
        "Either a file path (e.g. 'src/foo.py') OR a qualified symbol " +
          "name (e.g. 'src/foo:bar' for a top-level symbol, or " +
          "'src/foo:Bar.baz' for a method). Qnames are detected by the " +
          "presence of `:` (excluding URL schemes and Windows drive " +
          "prefixes). Drop the source extension in qnames.",
      ),
    show_source: tool.schema
      .boolean()
      .optional()
      .describe(
        "Force raw source mode. Use right before editing when you need " +
          "exact bytes/lines, not trie's synthesised description.",
      ),
    offset: tool.schema
      .number()
      .optional()
      .describe(
        "1-indexed first line to include. Implies `show_source: true` " +
          "since line numbers are only meaningful against source bytes, " +
          "not triefact prose.",
      ),
    limit: tool.schema
      .number()
      .optional()
      .describe(
        "Maximum number of lines to return from `offset`. Implies " +
          "`show_source: true` for the same reason as `offset`.",
      ),
    full: tool.schema
      .boolean()
      .optional()
      .describe(
        "When `path` is a file path and a triefact exists for it, return " +
          "every section's full prose. Trie's internal frontmatter " +
          "(`trie_version`, `file_fingerprint`, `last_synced_at`, " +
          "`source`) and all section sentinels (with their fingerprints) " +
          "are stripped; only `description`, `defines`, `incoming_refs`, " +
          "and `outgoing_refs` survive in the frontmatter. Default " +
          "behaviour is compact mode (one entry per symbol with qname, " +
          "kind, lines, signature, and first-paragraph intro), which is " +
          "much cheaper per token for narrow probing. Ignored for qname-" +
          "shaped paths and for `show_source: true` calls.",
      ),
  },
  async execute(args, context) {
    const cwd = context.directory
    const started = performance.now()

    // Telemetry args: only the path and the call-shape knobs. We don't
    // capture the full envelope arg unless the operator opts in via
    // capture_responses (handled below).
    const teleArgs: Record<string, unknown> = { path: args.path }
    if (args.show_source !== undefined) teleArgs.show_source = args.show_source
    if (args.offset !== undefined) teleArgs.offset = args.offset
    if (args.limit !== undefined) teleArgs.limit = args.limit
    if (args.full !== undefined) teleArgs.full = args.full

    let mode = "source"
    let result: string
    let resultKind: "ok" | "error" = "ok"
    let errorMessage: string | undefined
    try {
      const forceSource =
        args.show_source === true ||
        args.offset !== undefined ||
        args.limit !== undefined

      if (forceSource) {
        // Escape hatch: raw source bytes (or a line range from them).
        // The qname path emits its own `cli_call` from the subprocess
        // we spawn below; the in-process paths (this one + triefact +
        // source fallthrough) emit from here.
        mode = "show_source"
        result = await readSourceFile(cwd, args.path, args.offset, args.limit)
      } else if (looksLikeQname(args.path)) {
        // Symbol mode: route to `trie read <qname>`. The trie CLI emits
        // its own `cli_call` event from inside the subprocess, so we mark
        // this mode as `qname` here but skip our own emission at the bottom
        // to avoid double-counting.
        mode = "qname"
        result = await shellOutToTrie(["read", args.path], cwd)
      } else {
        // File-as-triefact mode: return the .md if it exists, otherwise
        // fall through to source. Non-source files (README.md, configs,
        // .gitignore, freshly added unsynced files) all 'just work' via
        // the fallthrough — the override is transparent for them.
        const triefact = await readTriefact(cwd, args.path)
        if (triefact !== null) {
          // Default: compact view (symbol manifest + intros). `full: true`
          // returns the entire .md bundle for callers that genuinely need
          // every section's prose.
          if (args.full === true) {
            mode = "triefact_full"
            // Strip trie's internal frontmatter (trie_version,
            // file_fingerprint, last_synced_at, source) and every
            // sentinel (which carries fingerprints / body_fps /
            // source_refs). Keeps only the agent-facing keys plus the
            // section bodies. Mirrors `trie.sync.writer.render_for_agent`.
            result = renderForAgent(triefact)
          } else {
            mode = "triefact_compact"
            result = renderCompact(triefact, args.path)
          }
        } else {
          mode = "source"
          result = await readSourceFile(cwd, args.path)
        }
      }
    } catch (e) {
      resultKind = "error"
      errorMessage = e instanceof Error ? e.message : String(e)
      // Emit before re-throwing so we don't lose the call from telemetry.
      // The qname path emits its own event from `trie read` — but only
      // when that subprocess actually fires. If `shellOutToTrie` threw
      // (e.g. trie binary missing), the subprocess never emitted, so
      // we cover the gap by emitting here in all error cases.
      const elapsed = Math.round(performance.now() - started)
      await emitTelemetry(cwd, {
        event: "cli_call",
        tool: "read",
        mode,
        result_kind: "error",
        duration_ms: elapsed,
        args: teleArgs,
        error: errorMessage,
      })
      throw e
    }

    // Successful return: emit a `cli_call` for the in-process paths.
    // Skip emission on the qname path because `trie read` already
    // emitted its own `cli_call` from inside the subprocess; emitting
    // here too would double-count.
    if (mode !== "qname") {
      const elapsed = Math.round(performance.now() - started)
      await emitTelemetry(cwd, {
        event: "cli_call",
        tool: "read",
        mode,
        result_kind: resultKind,
        duration_ms: elapsed,
        response_bytes: Buffer.byteLength(result, "utf-8"),
        args: teleArgs,
      })
    }
    return result
  },
})
"""
    )


def _render_opencode_trace(_project_root: Path) -> str:
    """Render `.opencode/tools/trace.ts` — exposes `trie trace` to the agent.

    No built-in collision; this is purely additive. Custom tools in
    opencode are named by file basename with no prefix, so this lands as
    a bare `trace` tool — distinct from the MCP-side `trie_trace` that
    opencode auto-prefixes from the trie MCP server. The custom tool
    wins on naming clarity for agents that have both surfaces.
    """
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Trace the call graph outward from a symbol up to `depth` hops. " +
    "Returns the root, every reachable node within depth, and the directed " +
    "edges between them. Use to understand a change's blast radius (callers) " +
    "or what a function ends up doing (callees). For prose on any specific " +
    "node, follow up by calling `read` with that qname (the read override " +
    "detects qname-shaped paths and routes to `trie read`).",
  args: {
    qname: tool.schema
      .string()
      .describe(
        "Fully-qualified symbol name to trace from. Format is " +
          "'path/to/file:LocalName' for top-level symbols and " +
          "'path/to/file:ClassName.method' for methods. Drop the source " +
          "extension; forward slashes on all OSes.",
      ),
    direction: tool.schema
      .string()
      .optional()
      .describe(
        "Which direction to traverse: 'callers' (default), 'callees', or 'both'.",
      ),
    depth: tool.schema
      .number()
      .optional()
      .describe(
        "Maximum BFS depth. Defaults to 2. Clamped server-side by the " +
          "trace_max_depth config knob.",
      ),
  },
  async execute(args, context) {
    const flags: string[] = ["trace", args.qname]
    if (args.direction) flags.push("--direction", args.direction)
    if (args.depth !== undefined) flags.push("--depth", String(args.depth))

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) {
      return stdout || "(empty response from trie)"
    }
    throw new Error(
      `trie trace failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`,
    )
  },
})
"""
    )


# ---------------------------------------------------------------------------
# opencode: 8 new extended tools.
# ---------------------------------------------------------------------------


def _render_opencode_grep_str(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Search source bodies with a full regex and get back the enclosing symbols. " +
    "Unlike the symbol-name grep, this searches raw source text and attributes " +
    "each matched line to its enclosing symbol. Use when you know a literal " +
    "string or pattern that should appear in the code rather than in a symbol name.",
  args: {
    regexp: tool.schema
      .string()
      .describe("Regex pattern to search source bodies with (ripgrep syntax, case-insensitive)."),
  },
  async execute(args, context) {
    const proc = Bun.spawn(["trie", "grep-str", args.regexp], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) return stdout || "(no matches)"
    throw new Error(`trie grep-str failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_grep_entry_points(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Find architectural entry points (high-inbound public symbols) whose triefact " +
    "prose matches a topic or concept. Use when orienting in an unfamiliar codebase " +
    "or looking for the main path that handles something.",
  args: {
    query: tool.schema
      .string()
      .describe("Topic or concept to match against symbol prose (e.g. 'authentication', 'error handling')."),
  },
  async execute(args, context) {
    const proc = Bun.spawn(["trie", "grep-entry-points", args.query], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) return stdout || "(no entry points found)"
    throw new Error(`trie grep-entry-points failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_grep_symbol(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Fuzzy symbol name lookup. Returns the best-matching symbol plus a list of " +
    "similar symbols. Better than grep for typo-tolerance and discovering related " +
    "symbols in one call. Use when you have a rough name but not the exact qname.",
  args: {
    sym: tool.schema
      .string()
      .describe("Symbol name or fragment to fuzzy-match (e.g. 'compute_casc', 'slugify')."),
  },
  async execute(args, context) {
    const proc = Bun.spawn(["trie", "grep-symbol", args.sym], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) return stdout || "(no match)"
    throw new Error(`trie grep-symbol failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_grep_symbol_neighbours(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Fuzzy symbol lookup plus trimmed triefact metadata for the best match's " +
    "immediate callers and callees. One round trip for the symbol and its " +
    "neighbourhood. Use when you want to orient around a symbol without a " +
    "separate read call.",
  args: {
    sym: tool.schema
      .string()
      .describe("Symbol name or fragment to fuzzy-match."),
  },
  async execute(args, context) {
    const proc = Bun.spawn(["trie", "grep-symbol-neighbours", args.sym], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) return stdout || "(no match)"
    throw new Error(`trie grep-symbol-neighbours failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_explain_symbol(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Full prose for a symbol plus a joined narrative that weaves together the " +
    "prose of its callers and callees. Use when you want to deeply understand a " +
    "symbol and how it fits into the system — not just its own docstring but the " +
    "story of what calls it and what it calls.",
  args: {
    sym: tool.schema
      .string()
      .describe("Symbol qname (e.g. 'trie/sync/cascade:compute_cascade') or name fragment."),
  },
  async execute(args, context) {
    const proc = Bun.spawn(["trie", "explain-symbol", args.sym], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) return stdout || "(no prose)"
    throw new Error(`trie explain-symbol failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_explain_symbol_refs(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Explain how a symbol is used — callers only, with their prose. Use when you " +
    "want to understand the call sites of a symbol: who uses it, in what context, " +
    "and with what intent. Skips the symbol's own prose and focuses on the usage story.",
  args: {
    sym: tool.schema
      .string()
      .describe("Symbol qname or name fragment to look up callers for."),
  },
  async execute(args, context) {
    const proc = Bun.spawn(["trie", "explain-symbol-refs", args.sym], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) return stdout || "(no callers)"
    throw new Error(`trie explain-symbol-refs failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_trace_flow(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Find call chain(s) between two symbols. Returns the shortest path(s) " +
    "following callee edges. If no path exists within the search depth, says so " +
    "clearly. Use to verify that one symbol can reach another, or to find the " +
    "execution path between an entry point and a deep utility.",
  args: {
    symbol1: tool.schema
      .string()
      .describe("Starting symbol — qname or name fragment (e.g. 'run_incremental')."),
    symbol2: tool.schema
      .string()
      .describe("Target symbol — qname or name fragment (e.g. 'Store.upsert_section_record')."),
  },
  async execute(args, context) {
    const proc = Bun.spawn(["trie", "trace-flow", args.symbol1, args.symbol2], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) return stdout || "(no path found)"
    throw new Error(`trie trace-flow failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_explain_flow(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Trace the call chain between two symbols and narrate each step with prose. " +
    "Use when you want to understand not just that a path exists but what each " +
    "step in the chain actually does — the story of the execution flow from entry " +
    "to target.",
  args: {
    symbol1: tool.schema
      .string()
      .describe("Starting symbol — qname or name fragment."),
    symbol2: tool.schema
      .string()
      .describe("Target symbol — qname or name fragment."),
  },
  async execute(args, context) {
    const proc = Bun.spawn(["trie", "explain-flow", args.symbol1, args.symbol2], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) return stdout || "(no path found)"
    throw new Error(`trie explain-flow failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


# ---------------------------------------------------------------------------
# opencode: 4 patch tools.
# ---------------------------------------------------------------------------


def _render_opencode_patch(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Record WHY a symbol changed (or is about to change): post an intent " +
    "note against a named symbol. You make the code change yourself with " +
    "your normal tools; notes accumulate until `patch_apply` archives them " +
    "to the session log. The pre-commit `trie intent` gate requires a note " +
    "for every changed symbol, and the notes feed the commit digest and " +
    "`read --history`.",
  args: {
    qname: tool.schema
      .string()
      .describe("Qualified name of the symbol to patch, e.g. 'src/foo:bar'."),
    note: tool.schema
      .string()
      .describe("Implementation change note describing what to modify."),
    reason: tool.schema
      .string()
      .optional()
      .describe("Why this change was made — the intent, not the mechanics."),
  },
  async execute(args, context) {
    const flags: string[] = [
      "patch", "create", args.qname,
      "--note", args.note,
    ]
    if (args.reason) flags.push("--reason", args.reason)

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0) return stdout.trim() || "patch posted"
    throw new Error(`trie patch create failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_patch_drop(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Remove pending patches. Pass `--qname` to drop patches for a specific " +
    "symbol, or `--all` to clear every pending patch.",
  args: {
    qname: tool.schema
      .string()
      .optional()
      .describe("Drop patches for a specific symbol by qualified name."),
    all: tool.schema
      .boolean()
      .optional()
      .describe("Drop all pending patches."),
  },
  async execute(args, context) {
    const flags: string[] = ["patch", "drop"]
    if (args.all) flags.push("--all")
    else if (args.qname) flags.push("--qname", args.qname)
    else throw new Error("specify either --qname <symbol> or --all")

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0) return stdout.trim() || "patches dropped"
    throw new Error(`trie patch drop failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_patch_list(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "List all pending patches grouped by symbol. Shows each symbol\\'s " +
    "qualified name and how many patches are queued for it.",
  args: {},
  async execute(_args, context) {
    const proc = Bun.spawn(["trie", "patch", "list"], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0) return stdout.trim() || "(no pending patches)"
    throw new Error(`trie patch list failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_patch_apply(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Commit all pending patch notes as intent — trie generates NO code. " +
    "Archives every pending note to the session log (feeding the per-commit " +
    "digest, read --history, and the `trie intent` pre-commit gate) and " +
    "clears the queue. Multi-symbol applies REQUIRE a session_note " +
    "describing the unifying intent. The output ends with gate coverage: " +
    "touched symbols still lacking notes are listed so you can stage and " +
    "re-apply now instead of failing the commit later.",
  args: {
    session_note: tool.schema
      .string()
      .optional()
      .describe(
        "The unifying intent behind this batch of patches. Required when " +
          "more than one symbol is being recorded; ignored for single-symbol " +
          "applies.",
      ),
  },
  async execute(args, context) {
    const flags: string[] = ["patch", "apply"]
    if (args.session_note) flags.push("--note", args.session_note)

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0) return stdout.trim() || "patches applied"
    throw new Error(`trie patch apply failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_create_symbol(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Record the intent behind a NEW symbol that isn't in the graph yet " +
    "(you write the code yourself; trie stores the why). Use this instead " +
    "of `patch` when the target qname doesn't exist — `patch` only accepts " +
    "existing symbols. The note is archived on `patch_apply` and satisfies " +
    "the `trie intent` gate for the added symbol.",
  args: {
    qname: tool.schema
      .string()
      .describe(
        "Intended qualified name for the new symbol, e.g. 'pkg/mod:new_fn'. " +
          "The module part may name a file that doesn't exist yet.",
      ),
    note: tool.schema
      .string()
      .describe("What the new symbol should do — signature, behaviour, contracts."),
    file: tool.schema
      .string()
      .optional()
      .describe("Target source file (derived from the qname when omitted)."),
    anchor: tool.schema
      .string()
      .optional()
      .describe("Place the new symbol after this existing qname in the file."),
    reason: tool.schema
      .string()
      .optional()
      .describe("Why this symbol is needed."),
  },
  async execute(args, context) {
    const flags: string[] = ["patch", "create-symbol", args.qname, "--note", args.note]
    if (args.file) flags.push("--file", args.file)
    if (args.anchor) flags.push("--anchor", args.anchor)
    if (args.reason) flags.push("--reason", args.reason)

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0) return stdout.trim() || "create staged"
    throw new Error(`trie patch create-symbol failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_rename_symbol(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Record a rename of an existing symbol (you perform the rename in " +
    "source yourself). The note is archived as rename intent on " +
    "`patch_apply`. `new_name` is the bare local identifier, not a qname.",
  args: {
    qname: tool.schema
      .string()
      .describe("Qualified name of the symbol to rename."),
    new_name: tool.schema
      .string()
      .describe("New local name (identifier only, e.g. 'compute_totals')."),
    reason: tool.schema
      .string()
      .optional()
      .describe("Why it's being renamed."),
  },
  async execute(args, context) {
    const flags: string[] = ["patch", "rename-symbol", args.qname, args.new_name]
    if (args.reason) flags.push("--reason", args.reason)

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0) return stdout.trim() || "rename staged"
    throw new Error(`trie patch rename-symbol failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_delete_symbol(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Record the intent behind deleting an existing symbol (you remove the " +
    "code yourself). Dependent callers are reported so you can review the " +
    "blast radius; the note is archived as delete intent on `patch_apply`. " +
    "For symbols already gone from the graph, use the CLI form: " +
    "`trie patch create <qname> -n \\"...\\" --gone`.",
  args: {
    qname: tool.schema
      .string()
      .describe("Qualified name of the symbol to delete."),
    reason: tool.schema
      .string()
      .optional()
      .describe("Why it's being removed."),
  },
  async execute(args, context) {
    const flags: string[] = ["patch", "delete-symbol", args.qname]
    if (args.reason) flags.push("--reason", args.reason)

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0) return stdout.trim() || "delete staged"
    throw new Error(`trie patch delete-symbol failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


def _render_opencode_batch_patch(_project_root: Path) -> str:
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Record intent notes for MANY symbols in one call instead of N separate " +
    "`patch`/`create_symbol` round trips — the usual way to clear the " +
    "`trie intent` gate after a multi-symbol change. Items are processed " +
    "independently: a bad item is reported in the summary but does not " +
    "abort the rest. Returns a JSON summary {staged, failed, results}.",
  args: {
    items: tool.schema
      .array(
        tool.schema.object({
          op: tool.schema
            .string()
            .optional()
            .describe("'patch' (default, existing symbol) or 'create' (new symbol)."),
          qname: tool.schema.string().describe("Qualified name of the target symbol."),
          note: tool.schema.string().describe("Implementation note for this item."),
          file: tool.schema
            .string()
            .optional()
            .describe("Target file for creates (derived from qname when omitted)."),
          anchor: tool.schema
            .string()
            .optional()
            .describe("For creates: place the new symbol after this existing qname."),
          reason: tool.schema.string().optional().describe("Why this change is needed."),
        }),
      )
      .describe("The patch/create items to stage."),
  },
  async execute(args, context) {
    const payload = JSON.stringify(args.items)
    const proc = Bun.spawn(["trie", "patch", "create-batch"], {
      cwd: context.directory,
      stdin: new TextEncoder().encode(payload),
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0) return stdout.trim() || "batch staged"
    throw new Error(`trie patch create-batch failed (exit ${code}): ${[stderr.trim(), stdout.trim()].filter(Boolean).join("\n") || "no output"}`)
  },
})
"""
    )


# ---------------------------------------------------------------------------
# Claude Code: PreToolUse advisory hook on `Grep`.
# ---------------------------------------------------------------------------


def _render_claude_code_hooks_json(_project_root: Path) -> str:
    """Render `.claude/hooks/trie-tools.json` — advisory hook on the built-in Grep.

    Claude Code has no tool-override surface comparable to opencode's. The
    closest mechanism is a `PreToolUse` hook that fires before every tool
    call and can emit a `systemMessage` Claude sees on its next turn. We
    use it for advisory steering only: every time Claude reaches for the
    built-in `Grep`, the hook injects a one-line tip pointing at
    `mcp__trie__grep`. Claude's call is allowed (no permissionDecision), so
    nothing breaks; we just nudge the model toward the trie tool on the
    next round.

    We don't try to intercept Read or Glob — their semantics are too
    different from trie's read/trace, and false positives on those would
    block legitimate file reads.

    The hook calls `echo` with a JSON payload on stdout. Claude Code reads
    the `systemMessage` field and shows it to the model. We keep the
    message short and instruction-shaped because system reminders are
    consumed every turn the hook fires; a long message would burn context.
    """
    # The hook file lands at `.claude/hooks/trie-tools.json`. Claude Code
    # also accepts hook configuration in settings.json, but a dedicated
    # file is easier to remove (delete the file → no more nudging) and
    # easier to detect for idempotency on re-runs of `trie setup`.
    import json as _json

    body = {
        "_comment": (
            "Auto-generated by `trie setup --override-builtins`. Do not hand-edit — "
            "re-running setup will overwrite this file. Delete it to opt out of "
            "the advisory hook."
        ),
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Grep",
                    "hooks": [
                        {
                            "type": "command",
                            "command": (
                                'echo \'{"systemMessage":"For symbol or '
                                "code-structure queries, prefer mcp__trie__grep "
                                "(or `trie grep --json` from a shell): it "
                                "searches the indexed symbol graph and falls "
                                "back to ripgrep against in-scope source "
                                "bodies, attributing hits to enclosing "
                                "symbols. Use built-in Grep only when you "
                                "specifically need raw line-level matches.\"}'"
                            ),
                        }
                    ],
                }
            ]
        },
    }
    return _json.dumps(body, indent=2) + "\n"


# ---------------------------------------------------------------------------
# Target registry.
# ---------------------------------------------------------------------------

# Every name MUST also exist in `trie.mcp_install.TARGETS` so `trie setup` can
# pair MCP / hook / tool-override install under one target slug.
TARGETS: dict[str, ToolOverrideTarget] = {
    "opencode": ToolOverrideTarget(
        name="opencode",
        display_name="opencode",
        summary=(
            "Override built-in `grep` and `read`, add `trace`, and install "
            "16 extended tools: `grep_str` (regex over source), "
            "`grep_entry_points` (hub discovery by topic), `grep_symbol` "
            "(fuzzy name lookup), `grep_symbol_neighbours` (symbol + "
            "neighbourhood), `explain_symbol` (full prose + narrative), "
            "`explain_symbol_refs` (usage story), `trace_flow` (call chain "
            "between two symbols), `explain_flow` (narrated execution path), "
            "`patch` (post implementation notes), `batch_patch` (stage many "
            "patches/creates at once), `create_symbol` (stage new symbols), "
            "`rename_symbol` / `delete_symbol` (structural edits), "
            "`patch_drop` (remove patches), `patch_list` (list patches), "
            "`patch_apply` (record all pending notes to the session log — "
            "no code generation)."
        ),
        files=(
            FileToWrite(
                relative_path=(".opencode", "tools", "grep.ts"),
                render=_render_opencode_grep_override,
                description="override built-in `grep` (routes to `trie grep`)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "read.ts"),
                render=_render_opencode_read_override,
                description=(
                    "override built-in `read` (qname → `trie read`; path → "
                    "triefact; `show_source: true` → raw source)"
                ),
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "trace.ts"),
                render=_render_opencode_trace,
                description="add `trace` (trace the call graph)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "grep_str.ts"),
                render=_render_opencode_grep_str,
                description="add `grep_str` (regex search over source bodies)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "grep_entry_points.ts"),
                render=_render_opencode_grep_entry_points,
                description="add `grep_entry_points` (find hubs matching a topic)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "grep_symbol.ts"),
                render=_render_opencode_grep_symbol,
                description="add `grep_symbol` (fuzzy symbol name lookup)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "grep_symbol_neighbours.ts"),
                render=_render_opencode_grep_symbol_neighbours,
                description="add `grep_symbol_neighbours` (symbol + immediate neighbours)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "explain_symbol.ts"),
                render=_render_opencode_explain_symbol,
                description="add `explain_symbol` (full prose + reference narrative)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "explain_symbol_refs.ts"),
                render=_render_opencode_explain_symbol_refs,
                description="add `explain_symbol_refs` (callers-only usage story)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "trace_flow.ts"),
                render=_render_opencode_trace_flow,
                description="add `trace_flow` (find call chains between two symbols)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "explain_flow.ts"),
                render=_render_opencode_explain_flow,
                description="add `explain_flow` (narrated execution path between two symbols)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "patch.ts"),
                render=_render_opencode_patch,
                description="add `patch` (post implementation notes)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "patch_drop.ts"),
                render=_render_opencode_patch_drop,
                description="add `patch_drop` (remove pending patches)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "patch_list.ts"),
                render=_render_opencode_patch_list,
                description="add `patch_list` (list pending patches)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "patch_apply.ts"),
                render=_render_opencode_patch_apply,
                description="add `patch_apply` (execute all pending patches)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "create_symbol.ts"),
                render=_render_opencode_create_symbol,
                description="add `create_symbol` (stage creation of a new symbol)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "rename_symbol.ts"),
                render=_render_opencode_rename_symbol,
                description="add `rename_symbol` (stage a symbol rename)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "delete_symbol.ts"),
                render=_render_opencode_delete_symbol,
                description="add `delete_symbol` (stage a symbol deletion)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "batch_patch.ts"),
                render=_render_opencode_batch_patch,
                description="add `batch_patch` (stage many patches/creates in one call)",
            ),
        ),
        # Earlier versions of `trie setup --override-builtins` shipped a
        # separate `trie_read.ts` add-on (the new `read.ts` override
        # subsumes it) and a prefixed `trie_trace.ts` (renamed to
        # `trace.ts` so the custom tool name matches the verb, since
        # opencode doesn't auto-prefix custom tools the way it does MCP
        # tools). Drop both on apply so users don't see duplicate tools.
        obsolete_files=(
            (".opencode", "tools", "trie_read.ts"),
            (".opencode", "tools", "trie_trace.ts"),
            # Briefly shipped as `patch_batch` before being renamed to match
            # the MCP server's `batch_patch` tool name.
            (".opencode", "tools", "patch_batch.ts"),
        ),
    ),
    "claude-code": ToolOverrideTarget(
        name="claude-code",
        display_name="Claude Code",
        summary=(
            "Install a PreToolUse advisory hook that emits a system reminder "
            "every time Claude reaches for built-in `Grep`, nudging the model "
            "toward `mcp__trie__grep`. Claude Code has no full tool-override "
            "surface, so this is the strongest available steer. Non-blocking — "
            "Grep still works; the agent just sees the tip."
        ),
        files=(
            FileToWrite(
                relative_path=(".claude", "hooks", "trie-tools.json"),
                render=_render_claude_code_hooks_json,
                description="advisory PreToolUse hook on built-in `Grep`",
            ),
        ),
    ),
    "claude-desktop": ToolOverrideTarget(
        name="claude-desktop",
        display_name="Claude Desktop",
        summary="",
        manual_instructions=(
            "Claude Desktop exposes no tool-override mechanism. Use the trie "
            "MCP server (already registered by `trie setup`) and prefer "
            "`mcp__trie__grep` / `mcp__trie__read` / `mcp__trie__trace` over "
            "the built-in tools manually."
        ),
    ),
    "cursor": ToolOverrideTarget(
        name="cursor",
        display_name="Cursor",
        summary="",
        manual_instructions=(
            "Cursor has no documented tool-override mechanism. Use the trie "
            "MCP server (already registered by `trie setup`) and the `trie "
            "grep` / `trie read` / `trie trace` CLI commands from the "
            "terminal when you want the symbol-aware path."
        ),
    ),
    "windsurf": ToolOverrideTarget(
        name="windsurf",
        display_name="Windsurf",
        summary="",
        manual_instructions=(
            "Windsurf has no documented tool-override mechanism. Use the trie "
            "MCP server and the `trie` CLI commands directly."
        ),
    ),
    "vscode": ToolOverrideTarget(
        name="vscode",
        display_name="VS Code",
        summary="",
        manual_instructions=(
            "VS Code's MCP integration has no tool-override mechanism. Use "
            "the trie MCP server and the `trie` CLI commands directly."
        ),
    ),
    "codex": ToolOverrideTarget(
        name="codex",
        display_name="Codex CLI",
        summary="",
        manual_instructions=(
            "Codex CLI has no documented tool-override mechanism. Use the "
            "trie MCP server and the `trie` CLI commands directly."
        ),
    ),
}


# ---------------------------------------------------------------------------
# Application logic.
# ---------------------------------------------------------------------------


@dataclass
class ToolOverrideInstallPlan:
    """Aggregate result of a full `install` call across one or more targets."""

    target_names: list[str]
    print_only: bool
    dry_run: bool
    results: list[ToolOverrideApplyResult] = field(default_factory=list)


def install(
    *,
    target_names: list[str] | None,
    print_only: bool,
    dry_run: bool,
    project_root: Path,
) -> ToolOverrideInstallPlan:
    """Apply tool-override files for one or more targets.

    Symmetric with `mcp_install.install` and `hook_install.install`: same
    flag semantics, same return-shape philosophy. Unknown target names
    raise `ToolOverrideInstallError`.

    Unlike the other installers, there's no `install_all`: tool overrides
    are explicit per harness and we don't want a multi-target rollout to
    happen by accident. The CLI is expected to drive this with the
    `target_names` from a prior `mcp_install` plan, after the user has
    consented via the interactive prompt.
    """
    if not target_names:
        raise ToolOverrideInstallError(
            "tool-override install requires explicit target names; pass --target."
        )

    chosen: list[ToolOverrideTarget] = []
    for name in target_names:
        if name not in TARGETS:
            raise ToolOverrideInstallError(
                f"unknown tool-override target: {name!r}. Known: {', '.join(TARGETS)}"
            )
        chosen.append(TARGETS[name])

    plan = ToolOverrideInstallPlan(
        target_names=[t.name for t in chosen],
        print_only=print_only,
        dry_run=dry_run,
    )
    for target in chosen:
        plan.results.append(apply_one(target, project_root, print_only, dry_run))
    return plan


def apply_one(
    target: ToolOverrideTarget,
    project_root: Path,
    print_only: bool,
    dry_run: bool,
    *,
    scope: Scope = "project",
) -> ToolOverrideApplyResult:
    """Install (or preview) every override file for one target.

    Each file in `target.files` is rendered, compared against any existing
    contents at its path, and written when content differs. Per-file
    results land in the returned `ToolOverrideApplyResult.files` list so
    the CLI can show which individual overrides changed.

    `scope` is accepted for API symmetry but currently unused: override
    files always live under the project (a user-scope override would have
    to know which project to target).
    """
    _ = scope  # reserved
    if not target.files:
        return ToolOverrideApplyResult(
            target=target.name,
            action="needs_manual_setup",
            detail=target.manual_instructions
            or f"{target.display_name} has no automated tool-override path in this trie version.",
        )

    file_results: list[ToolOverrideFileResult] = []
    for spec in target.files:
        file_results.append(_apply_file(spec, project_root, print_only, dry_run))
    # Drop any files that earlier versions of this installer used to ship
    # but newer versions no longer need. The cleanup runs after the writes
    # so an interrupted install can't leave the user with both the new
    # file AND the obsolete file simultaneously.
    for rel_parts in target.obsolete_files:
        file_results.append(_remove_obsolete(rel_parts, project_root, print_only, dry_run))

    # Summarise the per-file actions into one target-level action so the
    # rendered report can lead with a single status verb. Precedence:
    # error > created/updated > preview > skipped.
    actions = {r.action for r in file_results}
    if "error" in actions:
        top_action: Action = "error"
    elif "created" in actions:
        top_action = "created"
    elif "updated" in actions:
        top_action = "updated"
    elif "preview" in actions:
        top_action = "preview"
    else:
        top_action = "skipped"

    return ToolOverrideApplyResult(
        target=target.name,
        action=top_action,
        files=file_results,
    )


def _remove_obsolete(
    relative_path: tuple[str, ...],
    project_root: Path,
    print_only: bool,
    dry_run: bool,
) -> ToolOverrideFileResult:
    """Remove an obsolete file if it exists, else report skipped.

    Used by `apply_one` to clean up tool-override files that earlier
    versions of `trie setup` wrote but newer versions no longer need
    (e.g. `trie_read.ts`, replaced by the `read.ts` override). The
    'description' tags this as a removal in the user-facing report.

    Preview / dry-run paths report the prospective removal without
    touching disk, matching `_apply_file`'s semantics for symmetry.
    """
    target_path = project_root.joinpath(*relative_path)
    rel_str = str(Path(*relative_path))
    description = "removed obsolete file from earlier trie version"

    if not target_path.exists():
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="skipped",
            path=target_path,
            description=description,
            detail="not present; nothing to clean up",
        )

    if print_only or dry_run:
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="preview",
            path=target_path,
            description=description,
            detail="would remove",
        )

    try:
        target_path.unlink()
    except OSError as exc:
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="error",
            path=target_path,
            description=description,
            detail=f"could not remove: {exc}",
        )
    return ToolOverrideFileResult(
        relative_path=rel_str,
        action="updated",  # file state changed (now gone) — closest fit
        path=target_path,
        description=description,
    )


def _apply_file(
    spec: FileToWrite,
    project_root: Path,
    print_only: bool,
    dry_run: bool,
) -> ToolOverrideFileResult:
    """Materialise one override file, with idempotency check.

    Same write semantics as `hook_install.apply_one`: if the file exists
    with identical contents, return `skipped`; if it exists with different
    contents, overwrite (the user opted in by re-running setup); if
    `--print-only` or `--dry-run`, return `preview` without touching the
    disk.
    """
    contents = spec.render(project_root)
    target_path = project_root.joinpath(*spec.relative_path)
    rel_str = str(Path(*spec.relative_path))

    if print_only:
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="preview",
            path=target_path,
            description=spec.description,
            detail=contents,
        )

    existed_before = target_path.exists()
    if existed_before:
        try:
            current = target_path.read_text()
        except OSError as exc:
            return ToolOverrideFileResult(
                relative_path=rel_str,
                action="error",
                path=target_path,
                description=spec.description,
                detail=f"could not read existing file: {exc}",
            )
        if current == contents:
            return ToolOverrideFileResult(
                relative_path=rel_str,
                action="skipped",
                path=target_path,
                description=spec.description,
                detail="already installed with the same contents",
            )

    if dry_run:
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="preview",
            path=target_path,
            description=spec.description,
            detail=contents,
        )

    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(contents)
    return ToolOverrideFileResult(
        relative_path=rel_str,
        action="updated" if existed_before else "created",
        path=target_path,
        description=spec.description,
    )
