"""Tool-override installation: replace an agent's built-in tools with trie wrappers.

Companion to `mcp_install.py` and `hook_install.py`. Where `mcp_install` makes
trie available to an agent and `hook_install` makes it automatic, this module
makes trie *unavoidable* — it replaces or supplements the agent's built-in
tools so the agent reaches for trie reflexively, not just when prompted.

The interception story differs per harness:

- **opencode** supports drop-in tool replacement via `.opencode/tools/<name>.ts`.
  A custom tool whose filename matches a built-in name takes precedence over
  the built-in. We override `grep` (symbol-aware search) and `read`
  (triefact-first dispatch on qname vs path with a `show_source` escape
  hatch), and add `trie_trace` as a new tool for graph traversal (no
  built-in collision).
- **Claude Code** has no tool-override surface. The closest mechanism is a
  `PreToolUse` hook that fires before each built-in tool call and can emit a
  `systemMessage` Claude sees on its next turn. We use it for advisory
  steering on `Grep` only: "for symbol queries, prefer mcp__trie__grep".

Other harnesses don't have a documented interception path; they get a
`needs_manual_setup` result that explains the situation.

This is opt-in. `trie setup` prompts before writing any override files; the
user must say yes. The generated files carry the same "generated by, do not
hand-edit" notice as the hook plugin so re-running setup picks up
content drift, and the user can delete a file to opt back out.
"""

from __future__ import annotations

from collections.abc import Callable
from dataclasses import dataclass, field
from pathlib import Path
from typing import Literal

from trie.mcp_install import Scope

Action = Literal["created", "updated", "skipped", "preview", "error", "needs_manual_setup"]


class ToolOverrideInstallError(Exception):
    pass


@dataclass(frozen=True)
class FileToWrite:
    """One file an override target needs on disk.

    A target may need several files: e.g. opencode needs `grep.ts` and
    `read.ts` (built-in overrides) plus `trie_trace.ts` (addition). Each
    is rendered independently with its own idempotency check, so a
    partial failure on one file doesn't roll back the others.
    """

    relative_path: tuple[str, ...]
    render: Callable[[Path], str]
    description: str  # short label for the human-readable report


@dataclass(frozen=True)
class ToolOverrideApplyResult:
    """Outcome of installing override files for one target.

    `files` carries per-file results so the CLI can report which individual
    overrides landed and which were skipped. The top-level `action` summarises
    across files: if any file errored, action is "error"; if all skipped,
    "skipped"; otherwise "created"/"updated" reflecting the highest-energy
    change.
    """

    target: str
    action: Action
    files: list[ToolOverrideFileResult] = field(default_factory=list)
    detail: str = ""


@dataclass(frozen=True)
class ToolOverrideFileResult:
    """Per-file outcome inside a target's apply result."""

    relative_path: str
    action: Action
    path: Path | None
    description: str
    detail: str = ""


@dataclass(frozen=True)
class ToolOverrideTarget:
    """Static description of an agent's tool-override surface.

    `files` is the list of override files to write. Empty list means the
    target has no automatable override path; `apply_one` returns
    `needs_manual_setup` with `manual_instructions` for the user.

    `obsolete_files` is the list of paths to delete on apply if they
    exist — for cleaning up files that prior versions of `trie setup`
    wrote but newer versions no longer need (e.g. when a separate
    `trie_read.ts` tool was subsumed by an override of `read.ts`).
    The cleanup is silent: an obsolete file that doesn't exist is a
    no-op, and a successful delete is reported as part of the apply
    result so users know the migration happened.
    """

    name: str
    display_name: str
    files: tuple[FileToWrite, ...] = ()
    obsolete_files: tuple[tuple[str, ...], ...] = ()
    manual_instructions: str = ""
    # Human-readable one-line description of what installing for this target
    # actually does. Used in the interactive prompt so the user knows what
    # they're consenting to.
    summary: str = ""


# ---------------------------------------------------------------------------
# opencode: override `grep` and `read`, add `trie_trace`.
# ---------------------------------------------------------------------------


_GENERATED_HEADER = """// Auto-generated by `trie setup --override-builtins`. Do not hand-edit —
// re-running setup will overwrite this file. Delete the file to opt out of
// the override; trie setup won't recreate it without explicit consent.
//
// See https://opencode.ai/docs/custom-tools for the custom-tools API.
"""


def _render_opencode_grep_override(_project_root: Path) -> str:
    """Render `.opencode/tools/grep.ts` — overrides opencode's built-in `grep`.

    The file ships under the same filename as the built-in tool. Opencode's
    rule (documented at opencode.ai/docs/custom-tools): a default-exported
    custom tool whose filename matches a built-in takes precedence over the
    built-in. So once this file lands, every `grep` call from the agent
    routes through trie's `grep` instead of opencode's regex-over-files
    grep.

    Args are intentionally close to opencode's built-in grep so the agent
    doesn't have to relearn the call shape: `pattern` is the substring to
    search for (mapped to trie's `name_contains` predicate), `path` becomes
    `scope_prefix`, `include` is rejected (trie's scope is config-driven,
    not per-call). The wrapper shells out to `trie grep --json` and returns
    the envelope verbatim so the agent gets the same structured response it
    would get over MCP.

    `Bun.spawn` is what's used by the existing `trie-refresh.ts` plugin in
    this directory, so we know the runtime supports it. Errors from `trie`
    are bubbled up so the agent sees them on the next turn.
    """
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Search for symbols and source-body text via trie. Replaces opencode's " +
    "built-in grep with a symbol-aware search that returns signatures, " +
    "one-liners, and call-graph metrics — and falls back to ripgrep against " +
    "indexed source bodies when the query doesn't match a symbol name.",
  args: {
    pattern: tool.schema
      .string()
      .describe(
        "Substring to search for. Mapped to trie's `name_contains` " +
          "predicate; case-insensitive, matched against symbol local names. " +
          "If no symbol matches, trie's text-match fallback searches in-scope " +
          "source bodies and attributes hits to enclosing symbols.",
      ),
    path: tool.schema
      .string()
      .optional()
      .describe(
        "Path prefix to restrict the search to (e.g. 'src/' or 'trie/sync/'). " +
          "Maps to trie's `scope_prefix` predicate.",
      ),
    kind: tool.schema
      .string()
      .optional()
      .describe(
        "Restrict to one symbol kind: 'function', 'class', 'method', or 'any'.",
      ),
    public_only: tool.schema
      .boolean()
      .optional()
      .describe("If true, exclude symbols whose name starts with an underscore."),
    rank_by: tool.schema
      .string()
      .optional()
      .describe(
        "Result ordering: 'public_first' (default), 'inbound_count' " +
          "(centrality), or 'alphabetical'.",
      ),
    limit: tool.schema
      .number()
      .optional()
      .describe("Maximum number of hits to return. Defaults to 10."),
  },
  async execute(args, context) {
    const flags: string[] = ["grep", "--json", "--name", args.pattern]
    if (args.path) flags.push("--scope-prefix", args.path)
    if (args.kind) flags.push("--kind", args.kind)
    if (args.public_only) flags.push("--public-only")
    if (args.rank_by) flags.push("--rank-by", args.rank_by)
    if (args.limit !== undefined) flags.push("--limit", String(args.limit))

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])

    // Exit code 1 is a tool-level error (e.g. invalid predicate); the JSON
    // envelope on stdout carries the structured error. Code 2 is a CLI
    // usage error from trie itself. Anything else is unexpected.
    if (code === 0 || code === 1) {
      return stdout || "(empty response from trie)"
    }
    throw new Error(
      `trie grep failed (exit ${code}): ${stderr.trim() || "no stderr"}`,
    )
  },
})
"""
    )


def _render_opencode_read_override(_project_root: Path) -> str:
    """Render `.opencode/tools/read.ts` — overrides opencode's built-in `read`.

    The override dispatches on the argument shape so a single tool call
    serves three distinct intents the agent has:

    1. **Symbol read (qname)**: arg looks like a qname
       (`path/to/file:Name` — contains `:`, not a URL scheme, not a
       Windows drive prefix). Routes to `trie read --json <qname>` and
       returns the standard trie envelope: signature, prose, source
       pointer, callers, callees. This is the "I have a specific symbol
       in mind, show me its prose and immediate neighbours" path.

    2. **File-as-triefact**: arg is a plain file path AND a triefact
       exists for it at `triefacts/<path>.md`. Returns the full triefact
       contents (YAML frontmatter + every per-symbol section body). The
       agent gets the dense, structured "what does this file contain"
       view trie already paid LLM cost to produce — much cheaper per
       token than reading raw source, and usually enough to decide which
       symbol to drill into. This is the "give me everything trie knows
       about this file" path.

    3. **Source fallthrough**: `show_source: true` OR the path has no
       triefact OR `offset`/`limit` were passed (the agent wants raw
       line ranges, which are meaningless against triefact prose). The
       wrapper shells out to a small `cat`-equivalent so the agent sees
       the raw file bytes. This is the "I'm about to edit this and
       need exact source" escape hatch.

    Detection rule for qname vs path: any string containing `:` (and
    not a URL scheme like `https://` or Windows drive prefix like
    `C:\\`) is treated as a qname. This is intentionally permissive —
    qnames have a stable `path/to/file:Name` shape; on the rare chance
    a real file is named with a colon, the agent can pass
    `show_source: true` to escape.

    The triefact lookup uses the default `triefacts/` root. Projects
    that have configured a different `triefacts.root` in trie.toml
    will fall through to source for path reads — a known limitation
    with a graceful failure mode.
    """
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"
import { readFile, stat, appendFile } from "node:fs/promises"
import { join, normalize, isAbsolute } from "node:path"

// Conservative qname detection: an argument is a qname when it contains
// `:` but is NOT a URL (scheme://...) and NOT a Windows drive prefix
// (^[A-Za-z]:[\\\\/]). Real qnames have shape `path/to/file:Name` or
// `path/to/file:Class.method` — colon-bearing strings with at least one
// slash and no URL/drive markers.
function looksLikeQname(s: string): boolean {
  if (!s.includes(":")) return false
  if (/^[A-Za-z][A-Za-z0-9+.-]*:\\/\\//.test(s)) return false  // URL scheme
  if (/^[A-Za-z]:[\\\\/]/.test(s)) return false                  // Windows drive
  return true
}

// --- Telemetry --------------------------------------------------------------
// The read override has three code paths that don't shell out to `trie`
// (triefact lookup, source fallthrough, show_source). Without TS-side
// telemetry those calls would be invisible to `trie audit`, which would
// only see the qname path. We emit `cli_call` events from here that mirror
// the shape Python emits, so the audit aggregator buckets them the same
// way regardless of which surface (CLI subprocess or in-process TS wrapper)
// produced them.

interface TelemetryConfig {
  enabled: boolean
  logPath: string | null  // absolute path to debug.jsonl, or null when off
  captureArgs: boolean
  captureResponses: boolean
}

// Cache the resolved config per (cwd) so we parse trie.toml at most once
// per project root over the wrapper's lifetime. The cwd-keyed map handles
// the unusual case of opencode being driven against multiple projects in
// one session.
const telemetryConfigCache = new Map<string, TelemetryConfig>()

function resolveTelemetryConfig(cwd: string): TelemetryConfig {
  const cached = telemetryConfigCache.get(cwd)
  if (cached !== undefined) return cached
  const cfg = computeTelemetryConfig(cwd)
  telemetryConfigCache.set(cwd, cfg)
  return cfg
}

function computeTelemetryConfig(cwd: string): TelemetryConfig {
  // Defaults match Python's behaviour when no config is present: off.
  const off: TelemetryConfig = {
    enabled: false,
    logPath: null,
    captureArgs: true,
    captureResponses: false,
  }

  // Parse trie.toml's [debug] section. Hand-rolled because we don't want
  // to drag a TOML parser dep into the .opencode/ package just for four
  // string/bool fields with a known schema. If the file is missing or
  // unreadable, fall back to env-var-only mode.
  let toml = ""
  try {
    toml = require("node:fs").readFileSync(join(cwd, "trie.toml"), "utf-8")
  } catch {
    // No trie.toml; honour TRIE_DEBUG anyway (see below).
  }
  const debugSection = extractTomlSection(toml, "debug")

  let enabled = parseBool(debugSection["enabled"]) ?? false
  let logPath = parseString(debugSection["log_path"]) ?? "debug.jsonl"
  const captureArgs = parseBool(debugSection["capture_args"]) ?? true
  const captureResponses = parseBool(debugSection["capture_responses"]) ?? false

  // Env var wins (mirrors Python's precedence): `TRIE_DEBUG=1` enables
  // with the default path; `TRIE_DEBUG=/some/path` enables with that path;
  // `TRIE_DEBUG=0` force-disables; anything else enables at default.
  const env = process.env.TRIE_DEBUG
  if (env !== undefined) {
    if (env === "0" || env === "" || env.toLowerCase() === "false") {
      return { ...off, captureArgs, captureResponses }
    }
    enabled = true
    if (env !== "1" && env.toLowerCase() !== "true") {
      logPath = env
    }
  }

  if (!enabled) {
    return { ...off, captureArgs, captureResponses }
  }

  // Resolve logPath: absolute → use as-is; relative → resolve against
  // project root (cwd). Matches what `trie/telemetry.py` does.
  const resolvedPath = isAbsolute(logPath) ? logPath : join(cwd, logPath)
  return { enabled: true, logPath: resolvedPath, captureArgs, captureResponses }
}

function extractTomlSection(toml: string, section: string): Record<string, string> {
  // Minimal TOML section extractor. Walks lines; tracks the current
  // section header; collects `key = value` pairs from `[section]`.
  // Skips comments and blank lines. Strings, bools, and numbers come
  // back as their raw string form so the caller can parse per-key.
  // Doesn't handle multi-line strings, arrays, or nested tables —
  // none of which we use in [debug].
  const out: Record<string, string> = {}
  let inSection = false
  for (const raw of toml.split(/\\r?\\n/)) {
    const line = raw.replace(/(^|\\s)#.*$/, "").trim()
    if (line === "") continue
    const header = /^\\[([^\\]]+)\\]$/.exec(line)
    if (header !== null) {
      inSection = header[1].trim() === section
      continue
    }
    if (!inSection) continue
    const kv = /^([A-Za-z_][A-Za-z0-9_]*)\\s*=\\s*(.+)$/.exec(line)
    if (kv === null) continue
    out[kv[1]] = kv[2].trim()
  }
  return out
}

function parseBool(raw: string | undefined): boolean | null {
  if (raw === undefined) return null
  const v = raw.toLowerCase()
  if (v === "true") return true
  if (v === "false") return false
  return null
}

function parseString(raw: string | undefined): string | null {
  if (raw === undefined) return null
  // Strip surrounding quotes if present (single or double).
  const m = /^["']([\\s\\S]*)["']$/.exec(raw)
  return m !== null ? m[1] : raw
}

interface TelemetryEvent {
  event: string
  tool: string
  mode: string  // "qname" | "triefact" | "source" | "show_source"
  result_kind: "ok" | "error"
  duration_ms: number
  response_bytes?: number
  args?: Record<string, unknown>
  error?: string
}

async function emitTelemetry(cwd: string, evt: TelemetryEvent): Promise<void> {
  // Telemetry is best-effort: any failure here (no config, no log path,
  // permission denied, disk full, etc.) is swallowed silently. The wrapper
  // must never crash the agent's turn over an observability concern.
  try {
    const cfg = resolveTelemetryConfig(cwd)
    if (!cfg.enabled || cfg.logPath === null) return
    const payload: Record<string, unknown> = {
      ts: new Date().toISOString(),
      ...evt,
    }
    if (!cfg.captureArgs && "args" in payload) {
      delete payload.args
    }
    await appendFile(cfg.logPath, JSON.stringify(payload) + "\\n", "utf-8")
  } catch {
    // Swallow. Nothing we can usefully do here.
  }
}

// --- I/O helpers ------------------------------------------------------------

async function shellOutToTrie(
  flags: string[],
  cwd: string,
): Promise<string> {
  const proc = Bun.spawn(["trie", ...flags], {
    cwd,
    stdout: "pipe",
    stderr: "pipe",
  })
  const [stdout, stderr, code] = await Promise.all([
    new Response(proc.stdout).text(),
    new Response(proc.stderr).text(),
    proc.exited,
  ])
  // 0 = success, 1 = structured error envelope (e.g. not_found).
  // Both produce useful JSON on stdout that the agent can consume.
  if (code === 0 || code === 1) {
    return stdout || "(empty response from trie)"
  }
  throw new Error(`trie failed (exit ${code}): ${stderr.trim() || "no stderr"}`)
}

async function readSourceFile(
  cwd: string,
  path: string,
  offset?: number,
  limit?: number,
): Promise<string> {
  // Resolve the path relative to the project root (cwd from context).
  // No path-traversal guard here — the agent already has free reign
  // over the project via the bash tool; this matches built-in `read`'s
  // permissiveness rather than imposing a stricter sandbox.
  const absPath = normalize(join(cwd, path))
  const text = await readFile(absPath, "utf-8")
  if (offset === undefined && limit === undefined) {
    return text
  }
  // Honour line-range args the same way built-in read does: 1-indexed
  // `offset` is the first line to include; `limit` is the count.
  const lines = text.split("\\n")
  const start = offset !== undefined ? Math.max(0, offset - 1) : 0
  const end = limit !== undefined ? start + limit : lines.length
  return lines.slice(start, end).join("\\n")
}

async function readTriefact(cwd: string, path: string): Promise<string | null> {
  // Default triefact location: `<cwd>/triefacts/<path>.md`. We swap the
  // source extension for `.md` (matching how the writer maps source →
  // triefact in trie/sync/single_file.py). Projects with a non-default
  // `triefacts.root` config won't be picked up here — we fall through
  // to source in that case rather than parsing trie.toml from TS.
  const dotIdx = path.lastIndexOf(".")
  const stem = dotIdx > 0 ? path.slice(0, dotIdx) : path
  const triefactPath = join(cwd, "triefacts", stem + ".md")
  try {
    const s = await stat(triefactPath)
    if (!s.isFile()) return null
  } catch {
    return null  // ENOENT or any stat failure → no triefact
  }
  return readFile(triefactPath, "utf-8")
}

export default tool({
  description:
    "Read source code or trie's synthesised description of it. Replaces " +
    "opencode's built-in `read` with a triefact-first wrapper that maximises " +
    "context per token: " +
    "(1) when `path` is a qualified symbol name like `pkg/module:Name`, returns " +
    "the symbol's prose plus its callers/callees from the trie graph; " +
    "(2) when `path` is a regular file path and a triefact exists at " +
    "`triefacts/<path>.md`, returns the full triefact (YAML frontmatter + " +
    "every per-symbol section); " +
    "(3) when `show_source: true`, or no triefact exists, or `offset`/`limit` " +
    "are passed for a line-range read, returns the raw source verbatim. " +
    "Use the default mode for understanding what a file or symbol does; " +
    "use `show_source: true` right before editing when you need exact source.",
  args: {
    path: tool.schema
      .string()
      .describe(
        "Either a file path (e.g. 'src/foo.py') OR a qualified symbol " +
          "name (e.g. 'src/foo:bar' for a top-level symbol, or " +
          "'src/foo:Bar.baz' for a method). Qnames are detected by the " +
          "presence of `:` (excluding URL schemes and Windows drive " +
          "prefixes). Drop the source extension in qnames.",
      ),
    show_source: tool.schema
      .boolean()
      .optional()
      .describe(
        "Force raw source mode. Use right before editing when you need " +
          "exact bytes/lines, not trie's synthesised description.",
      ),
    offset: tool.schema
      .number()
      .optional()
      .describe(
        "1-indexed first line to include. Implies `show_source: true` " +
          "since line numbers are only meaningful against source bytes, " +
          "not triefact prose.",
      ),
    limit: tool.schema
      .number()
      .optional()
      .describe(
        "Maximum number of lines to return from `offset`. Implies " +
          "`show_source: true` for the same reason as `offset`.",
      ),
  },
  async execute(args, context) {
    const cwd = context.directory
    const started = performance.now()

    // Telemetry args: only the path and the call-shape knobs. We don't
    // capture the full envelope arg unless the operator opts in via
    // capture_responses (handled below).
    const teleArgs: Record<string, unknown> = { path: args.path }
    if (args.show_source !== undefined) teleArgs.show_source = args.show_source
    if (args.offset !== undefined) teleArgs.offset = args.offset
    if (args.limit !== undefined) teleArgs.limit = args.limit

    let mode = "source"
    let result: string
    let resultKind: "ok" | "error" = "ok"
    let errorMessage: string | undefined
    try {
      const forceSource =
        args.show_source === true ||
        args.offset !== undefined ||
        args.limit !== undefined

      if (forceSource) {
        // Escape hatch: raw source bytes (or a line range from them).
        // The qname path emits its own `cli_call` from the subprocess
        // we spawn below; the in-process paths (this one + triefact +
        // source fallthrough) emit from here.
        mode = "show_source"
        result = await readSourceFile(cwd, args.path, args.offset, args.limit)
      } else if (looksLikeQname(args.path)) {
        // Symbol mode: route to `trie read --json <qname>`. The trie CLI
        // emits its own `cli_call` event from inside the subprocess, so
        // we mark this mode as `qname` here but skip our own emission
        // at the bottom to avoid double-counting.
        mode = "qname"
        result = await shellOutToTrie(["read", "--json", args.path], cwd)
      } else {
        // File-as-triefact mode: return the .md if it exists, otherwise
        // fall through to source. Non-source files (README.md, configs,
        // .gitignore, freshly added unsynced files) all 'just work' via
        // the fallthrough — the override is transparent for them.
        const triefact = await readTriefact(cwd, args.path)
        if (triefact !== null) {
          mode = "triefact"
          result = triefact
        } else {
          mode = "source"
          result = await readSourceFile(cwd, args.path)
        }
      }
    } catch (e) {
      resultKind = "error"
      errorMessage = e instanceof Error ? e.message : String(e)
      // Emit before re-throwing so we don't lose the call from telemetry.
      // The qname path emits its own event from `trie read` — but only
      // when that subprocess actually fires. If `shellOutToTrie` threw
      // (e.g. trie binary missing), the subprocess never emitted, so
      // we cover the gap by emitting here in all error cases.
      const elapsed = Math.round(performance.now() - started)
      await emitTelemetry(cwd, {
        event: "cli_call",
        tool: "read",
        mode,
        result_kind: "error",
        duration_ms: elapsed,
        args: teleArgs,
        error: errorMessage,
      })
      throw e
    }

    // Successful return: emit a `cli_call` for the in-process paths.
    // Skip emission on the qname path because `trie read` already
    // emitted its own `cli_call` from inside the subprocess; emitting
    // here too would double-count.
    if (mode !== "qname") {
      const elapsed = Math.round(performance.now() - started)
      await emitTelemetry(cwd, {
        event: "cli_call",
        tool: "read",
        mode,
        result_kind: resultKind,
        duration_ms: elapsed,
        response_bytes: Buffer.byteLength(result, "utf-8"),
        args: teleArgs,
      })
    }
    return result
  },
})
"""
    )


def _render_opencode_trie_trace(_project_root: Path) -> str:
    """Render `.opencode/tools/trie_trace.ts` — exposes `trie trace` to the agent.

    No built-in collision; this is purely additive. Gives the agent a
    direct tool entry for "trace the call graph from a symbol N hops out"
    instead of relying on the MCP-namespaced `mcp__trie__trace` (which is
    longer to type and visually noisy).
    """
    return (
        _GENERATED_HEADER
        + """
import { tool } from "@opencode-ai/plugin"

export default tool({
  description:
    "Trace the call graph outward from a symbol up to `depth` hops. " +
    "Returns the root, every reachable node within depth, and the directed " +
    "edges between them. Use to understand a change's blast radius (callers) " +
    "or what a function ends up doing (callees). For prose on any specific " +
    "node, follow up by calling `read` with that qname (the read override " +
    "detects qname-shaped paths and routes to `trie read`).",
  args: {
    qname: tool.schema
      .string()
      .describe(
        "Fully-qualified symbol name to trace from. Format is " +
          "'path/to/file:LocalName' for top-level symbols and " +
          "'path/to/file:ClassName.method' for methods. Drop the source " +
          "extension; forward slashes on all OSes.",
      ),
    direction: tool.schema
      .string()
      .optional()
      .describe(
        "Which direction to traverse: 'callers' (default), 'callees', or 'both'.",
      ),
    depth: tool.schema
      .number()
      .optional()
      .describe(
        "Maximum BFS depth. Defaults to 2. Clamped server-side by the " +
          "trace_max_depth config knob.",
      ),
  },
  async execute(args, context) {
    const flags: string[] = ["trace", "--json", args.qname]
    if (args.direction) flags.push("--direction", args.direction)
    if (args.depth !== undefined) flags.push("--depth", String(args.depth))

    const proc = Bun.spawn(["trie", ...flags], {
      cwd: context.directory,
      stdout: "pipe",
      stderr: "pipe",
    })
    const [stdout, stderr, code] = await Promise.all([
      new Response(proc.stdout).text(),
      new Response(proc.stderr).text(),
      proc.exited,
    ])
    if (code === 0 || code === 1) {
      return stdout || "(empty response from trie)"
    }
    throw new Error(
      `trie trace failed (exit ${code}): ${stderr.trim() || "no stderr"}`,
    )
  },
})
"""
    )


# ---------------------------------------------------------------------------
# Claude Code: PreToolUse advisory hook on `Grep`.
# ---------------------------------------------------------------------------


def _render_claude_code_hooks_json(_project_root: Path) -> str:
    """Render `.claude/hooks/trie-tools.json` — advisory hook on the built-in Grep.

    Claude Code has no tool-override surface comparable to opencode's. The
    closest mechanism is a `PreToolUse` hook that fires before every tool
    call and can emit a `systemMessage` Claude sees on its next turn. We
    use it for advisory steering only: every time Claude reaches for the
    built-in `Grep`, the hook injects a one-line tip pointing at
    `mcp__trie__grep`. Claude's call is allowed (no permissionDecision), so
    nothing breaks; we just nudge the model toward the trie tool on the
    next round.

    We don't try to intercept Read or Glob — their semantics are too
    different from trie's read/trace, and false positives on those would
    block legitimate file reads.

    The hook calls `echo` with a JSON payload on stdout. Claude Code reads
    the `systemMessage` field and shows it to the model. We keep the
    message short and instruction-shaped because system reminders are
    consumed every turn the hook fires; a long message would burn context.
    """
    # The hook file lands at `.claude/hooks/trie-tools.json`. Claude Code
    # also accepts hook configuration in settings.json, but a dedicated
    # file is easier to remove (delete the file → no more nudging) and
    # easier to detect for idempotency on re-runs of `trie setup`.
    import json as _json

    body = {
        "_comment": (
            "Auto-generated by `trie setup --override-builtins`. Do not hand-edit — "
            "re-running setup will overwrite this file. Delete it to opt out of "
            "the advisory hook."
        ),
        "hooks": {
            "PreToolUse": [
                {
                    "matcher": "Grep",
                    "hooks": [
                        {
                            "type": "command",
                            "command": (
                                'echo \'{"systemMessage":"For symbol or '
                                "code-structure queries, prefer mcp__trie__grep "
                                "(or `trie grep --json` from a shell): it "
                                "searches the indexed symbol graph and falls "
                                "back to ripgrep against in-scope source "
                                "bodies, attributing hits to enclosing "
                                "symbols. Use built-in Grep only when you "
                                "specifically need raw line-level matches.\"}'"
                            ),
                        }
                    ],
                }
            ]
        },
    }
    return _json.dumps(body, indent=2) + "\n"


# ---------------------------------------------------------------------------
# Target registry.
# ---------------------------------------------------------------------------

# Every name MUST also exist in `trie.mcp_install.TARGETS` so `trie setup` can
# pair MCP / hook / tool-override install under one target slug.
TARGETS: dict[str, ToolOverrideTarget] = {
    "opencode": ToolOverrideTarget(
        name="opencode",
        display_name="opencode",
        summary=(
            "Override built-in `grep` (routes to `trie grep`) and `read` "
            "(triefact-first: qname → `trie read`, path → triefact .md, "
            "with a `show_source: true` escape hatch for raw bytes). Also "
            "add `trie_trace` for graph traversal. The agent gets trie's "
            "synthesised view by default and falls through to source only "
            "when it asks explicitly."
        ),
        files=(
            FileToWrite(
                relative_path=(".opencode", "tools", "grep.ts"),
                render=_render_opencode_grep_override,
                description="override built-in `grep` (routes to `trie grep`)",
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "read.ts"),
                render=_render_opencode_read_override,
                description=(
                    "override built-in `read` (qname → `trie read`; path → "
                    "triefact; `show_source: true` → raw source)"
                ),
            ),
            FileToWrite(
                relative_path=(".opencode", "tools", "trie_trace.ts"),
                render=_render_opencode_trie_trace,
                description="add `trie_trace` (trace the call graph)",
            ),
        ),
        # Earlier versions of `trie setup --override-builtins` shipped a
        # separate `trie_read.ts` add-on; the new `read.ts` override
        # subsumes it (qname-shaped paths route to `trie read` automatically).
        # Drop the stale file on apply so users don't see two tools that do
        # the same thing.
        obsolete_files=((".opencode", "tools", "trie_read.ts"),),
    ),
    "claude-code": ToolOverrideTarget(
        name="claude-code",
        display_name="Claude Code",
        summary=(
            "Install a PreToolUse advisory hook that emits a system reminder "
            "every time Claude reaches for built-in `Grep`, nudging the model "
            "toward `mcp__trie__grep`. Claude Code has no full tool-override "
            "surface, so this is the strongest available steer. Non-blocking — "
            "Grep still works; the agent just sees the tip."
        ),
        files=(
            FileToWrite(
                relative_path=(".claude", "hooks", "trie-tools.json"),
                render=_render_claude_code_hooks_json,
                description="advisory PreToolUse hook on built-in `Grep`",
            ),
        ),
    ),
    "claude-desktop": ToolOverrideTarget(
        name="claude-desktop",
        display_name="Claude Desktop",
        summary="",
        manual_instructions=(
            "Claude Desktop exposes no tool-override mechanism. Use the trie "
            "MCP server (already registered by `trie setup`) and prefer "
            "`mcp__trie__grep` / `mcp__trie__read` / `mcp__trie__trace` over "
            "the built-in tools manually."
        ),
    ),
    "cursor": ToolOverrideTarget(
        name="cursor",
        display_name="Cursor",
        summary="",
        manual_instructions=(
            "Cursor has no documented tool-override mechanism. Use the trie "
            "MCP server (already registered by `trie setup`) and the `trie "
            "grep` / `trie read` / `trie trace` CLI commands from the "
            "terminal when you want the symbol-aware path."
        ),
    ),
    "windsurf": ToolOverrideTarget(
        name="windsurf",
        display_name="Windsurf",
        summary="",
        manual_instructions=(
            "Windsurf has no documented tool-override mechanism. Use the trie "
            "MCP server and the `trie` CLI commands directly."
        ),
    ),
    "vscode": ToolOverrideTarget(
        name="vscode",
        display_name="VS Code",
        summary="",
        manual_instructions=(
            "VS Code's MCP integration has no tool-override mechanism. Use "
            "the trie MCP server and the `trie` CLI commands directly."
        ),
    ),
    "codex": ToolOverrideTarget(
        name="codex",
        display_name="Codex CLI",
        summary="",
        manual_instructions=(
            "Codex CLI has no documented tool-override mechanism. Use the "
            "trie MCP server and the `trie` CLI commands directly."
        ),
    ),
}


# ---------------------------------------------------------------------------
# Application logic.
# ---------------------------------------------------------------------------


@dataclass
class ToolOverrideInstallPlan:
    """Aggregate result of a full `install` call across one or more targets."""

    target_names: list[str]
    print_only: bool
    dry_run: bool
    results: list[ToolOverrideApplyResult] = field(default_factory=list)


def install(
    *,
    target_names: list[str] | None,
    print_only: bool,
    dry_run: bool,
    project_root: Path,
) -> ToolOverrideInstallPlan:
    """Apply tool-override files for one or more targets.

    Symmetric with `mcp_install.install` and `hook_install.install`: same
    flag semantics, same return-shape philosophy. Unknown target names
    raise `ToolOverrideInstallError`.

    Unlike the other installers, there's no `install_all`: tool overrides
    are explicit per harness and we don't want a multi-target rollout to
    happen by accident. The CLI is expected to drive this with the
    `target_names` from a prior `mcp_install` plan, after the user has
    consented via the interactive prompt.
    """
    if not target_names:
        raise ToolOverrideInstallError(
            "tool-override install requires explicit target names; pass --target."
        )

    chosen: list[ToolOverrideTarget] = []
    for name in target_names:
        if name not in TARGETS:
            raise ToolOverrideInstallError(
                f"unknown tool-override target: {name!r}. Known: {', '.join(TARGETS)}"
            )
        chosen.append(TARGETS[name])

    plan = ToolOverrideInstallPlan(
        target_names=[t.name for t in chosen],
        print_only=print_only,
        dry_run=dry_run,
    )
    for target in chosen:
        plan.results.append(apply_one(target, project_root, print_only, dry_run))
    return plan


def apply_one(
    target: ToolOverrideTarget,
    project_root: Path,
    print_only: bool,
    dry_run: bool,
    *,
    scope: Scope = "project",
) -> ToolOverrideApplyResult:
    """Install (or preview) every override file for one target.

    Each file in `target.files` is rendered, compared against any existing
    contents at its path, and written when content differs. Per-file
    results land in the returned `ToolOverrideApplyResult.files` list so
    the CLI can show which individual overrides changed.

    `scope` is accepted for API symmetry but currently unused: override
    files always live under the project (a user-scope override would have
    to know which project to target).
    """
    _ = scope  # reserved
    if not target.files:
        return ToolOverrideApplyResult(
            target=target.name,
            action="needs_manual_setup",
            detail=target.manual_instructions
            or f"{target.display_name} has no automated tool-override path in this trie version.",
        )

    file_results: list[ToolOverrideFileResult] = []
    for spec in target.files:
        file_results.append(_apply_file(spec, project_root, print_only, dry_run))
    # Drop any files that earlier versions of this installer used to ship
    # but newer versions no longer need. The cleanup runs after the writes
    # so an interrupted install can't leave the user with both the new
    # file AND the obsolete file simultaneously.
    for rel_parts in target.obsolete_files:
        file_results.append(_remove_obsolete(rel_parts, project_root, print_only, dry_run))

    # Summarise the per-file actions into one target-level action so the
    # rendered report can lead with a single status verb. Precedence:
    # error > created/updated > preview > skipped.
    actions = {r.action for r in file_results}
    if "error" in actions:
        top_action: Action = "error"
    elif "created" in actions:
        top_action = "created"
    elif "updated" in actions:
        top_action = "updated"
    elif "preview" in actions:
        top_action = "preview"
    else:
        top_action = "skipped"

    return ToolOverrideApplyResult(
        target=target.name,
        action=top_action,
        files=file_results,
    )


def _remove_obsolete(
    relative_path: tuple[str, ...],
    project_root: Path,
    print_only: bool,
    dry_run: bool,
) -> ToolOverrideFileResult:
    """Remove an obsolete file if it exists, else report skipped.

    Used by `apply_one` to clean up tool-override files that earlier
    versions of `trie setup` wrote but newer versions no longer need
    (e.g. `trie_read.ts`, replaced by the `read.ts` override). The
    'description' tags this as a removal in the user-facing report.

    Preview / dry-run paths report the prospective removal without
    touching disk, matching `_apply_file`'s semantics for symmetry.
    """
    target_path = project_root.joinpath(*relative_path)
    rel_str = str(Path(*relative_path))
    description = "removed obsolete file from earlier trie version"

    if not target_path.exists():
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="skipped",
            path=target_path,
            description=description,
            detail="not present; nothing to clean up",
        )

    if print_only or dry_run:
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="preview",
            path=target_path,
            description=description,
            detail="would remove",
        )

    try:
        target_path.unlink()
    except OSError as exc:
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="error",
            path=target_path,
            description=description,
            detail=f"could not remove: {exc}",
        )
    return ToolOverrideFileResult(
        relative_path=rel_str,
        action="updated",  # file state changed (now gone) — closest fit
        path=target_path,
        description=description,
    )


def _apply_file(
    spec: FileToWrite,
    project_root: Path,
    print_only: bool,
    dry_run: bool,
) -> ToolOverrideFileResult:
    """Materialise one override file, with idempotency check.

    Same write semantics as `hook_install.apply_one`: if the file exists
    with identical contents, return `skipped`; if it exists with different
    contents, overwrite (the user opted in by re-running setup); if
    `--print-only` or `--dry-run`, return `preview` without touching the
    disk.
    """
    contents = spec.render(project_root)
    target_path = project_root.joinpath(*spec.relative_path)
    rel_str = str(Path(*spec.relative_path))

    if print_only:
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="preview",
            path=target_path,
            description=spec.description,
            detail=contents,
        )

    existed_before = target_path.exists()
    if existed_before:
        try:
            current = target_path.read_text()
        except OSError as exc:
            return ToolOverrideFileResult(
                relative_path=rel_str,
                action="error",
                path=target_path,
                description=spec.description,
                detail=f"could not read existing file: {exc}",
            )
        if current == contents:
            return ToolOverrideFileResult(
                relative_path=rel_str,
                action="skipped",
                path=target_path,
                description=spec.description,
                detail="already installed with the same contents",
            )

    if dry_run:
        return ToolOverrideFileResult(
            relative_path=rel_str,
            action="preview",
            path=target_path,
            description=spec.description,
            detail=contents,
        )

    target_path.parent.mkdir(parents=True, exist_ok=True)
    target_path.write_text(contents)
    return ToolOverrideFileResult(
        relative_path=rel_str,
        action="updated" if existed_before else "created",
        path=target_path,
        description=spec.description,
    )
