"""Install the triediff-comment GitHub workflow into a project.

`trie setup` drops `.github/workflows/triediff-comment.yml` into git repos so
every PR automatically gets a comment containing the latest session digest
(see `trie diff --write` / the `[diff]` config section). The workflow is
stateless: one comment per digest file, deduped by filename, linking to the
digest blob at the head SHA.

Install semantics mirror the other installers (idempotent, marker-fenced
ownership):

- file missing                          -> created
- file present with our marker, drifted -> updated (template evolution)
- file present with our marker, equal   -> unchanged
- file present without our marker       -> skipped (user-owned; never touched)
- no `.git` directory                   -> skipped (nothing to hook)

The workflow itself is inert off GitHub, so no remote detection is attempted —
a repo that never pushes to GitHub simply never runs it.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

WORKFLOW_RELPATH = Path(".github") / "workflows" / "triediff-comment.yml"

# First comment line of the rendered file. Presence marks the file as
# trie-managed (safe to regenerate); absence marks it user-owned.
WORKFLOW_MARKER = "# managed-by: trie setup (triediff-comment)"

# Raw string: shell line-continuations (`\` at EOL) and regex escapes (`\.`)
# must reach the YAML verbatim; a cooked string would eat them.
_TEMPLATE = r"""{marker}
# Comments each triediff ({diffs_dir}/*.md) added by a PR so reviewers
# see the intent-level summary of every commit before opening a file diff.
# Stateless: one comment per digest file, deduped by filename; a rewritten
# same-commit digest (amend) is not re-commented. Delete this file (or edit
# it — trie won't touch a file without the managed-by marker above) to opt
# out. Regenerated by `trie setup` when the template evolves.
name: triediff-comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{{{ github.event.pull_request.head.sha }}}}

      - name: Comment the PR's triediffs
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          PR: ${{{{ github.event.pull_request.number }}}}
          HEAD_SHA: ${{{{ github.event.pull_request.head.sha }}}}
        run: |
          set -eu
          dir="{diffs_dir}"
          # Every digest file ADDED by this PR — not just the newest: a PR
          # spans many commits, each carrying its own digest. Oldest first
          # so comments read chronologically.
          added="$(gh api "repos/${{GITHUB_REPOSITORY}}/pulls/${{PR}}/files" --paginate \
                     --jq '.[] | select(.status == "added") | .filename' \
                   | grep "^${{dir}}/" | grep '\.md$' | sort || true)"
          if [ -z "$added" ]; then
            echo "no new digest files in this PR; nothing to comment"
            exit 0
          fi

          # Fetch existing comments once; dedupe each digest by filename.
          existing="$(gh api "repos/${{GITHUB_REPOSITORY}}/issues/${{PR}}/comments" \
                        --paginate --jq '.[].body' || true)"

          for path in $added; do
            name="$(basename "$path")"
            if printf '%s' "$existing" | grep -qF "$name"; then
              echo "digest $name already commented; skipping"
              continue
            fi
            if [ ! -f "$path" ]; then
              echo "digest $name no longer exists at head (pruned?); skipping"
              continue
            fi
            url="${{GITHUB_SERVER_URL}}/${{GITHUB_REPOSITORY}}/blob/${{HEAD_SHA}}/${{path}}"
            # Prettify the raw digest into a quiet, scannable comment WITHOUT
            # altering the on-disk file (its `- <marker> qname — note` bullets
            # are a machine-readable record other tooling parses). The awk pass
            # below is display-only: it strips the auto-generated header comment,
            # renders the `### Changes` bullet list as a markdown table, folds
            # the hidden overflow record into that same table, and drops the
            # "… and N more" marker. Everything else (title, narrative, Staged)
            # passes through untouched, so the comment reads title-first.
            cat > /tmp/triediff-fmt.awk <<'AWK'
          BEGIN {{ in_changes=0; in_overflow=0; skip_lead=1; seen=0 }}
          skip_lead && /^<!--/ {{ in_lead=1 }}
          in_lead {{ if ($0 ~ /-->/) {{ in_lead=0; skip_lead=0 }} ; next }}
          {{ skip_lead=0 }}
          !seen && /^[[:space:]]*$/ {{ next }}
          {{ seen=1 }}
          $0 ~ /^<!-- trie:changes-(overflow|record)$/ {{ in_overflow=1; next }}
          in_overflow && /^-->$/ {{ in_overflow=0; next }}
          /^### Changes[[:space:]]*$/ {{
            print "### Changes"; print "";
            print "| Change | Symbol | Summary |";
            print "| --- | --- | --- |";
            in_changes=1; next
          }}
          /^### / && in_changes {{ in_changes=0; print ""; print $0; next }}
          (in_changes || in_overflow) && /^[[:space:]]*$/ {{ next }}
          in_changes && /^-[[:space:]]+…/ {{ next }}
          (in_changes || in_overflow) && /^-[[:space:]]/ {{
            line=$0; sub(/^-[[:space:]]+/, "", line);
            marker=substr(line,1,1); rest=substr(line,2); sub(/^[[:space:]]+/, "", rest);
            label="changed";
            if (marker=="+") label="added"; else if (marker=="~") label="changed"; else label="removed";
            qname=rest; summary=""; sep=index(rest, " — ");
            if (sep>0) {{ qname=substr(rest,1,sep-1); summary=substr(rest,sep+5) }}
            gsub(/\|/, "\\|", summary); gsub(/\|/, "\\|", qname);
            printf "| %s | `%s` | %s |\n", label, qname, summary;
            next
          }}
          {{ print }}
          AWK
            {{
              awk -f /tmp/triediff-fmt.awk "$path"
              echo
              echo "<sub><a href=\"${{url}}\">${{name}}</a></sub>"
            }} > /tmp/digest-comment.md
            gh pr comment "$PR" --body-file /tmp/digest-comment.md
          done
"""


def render_triediff_workflow(diffs_dir: str) -> str:
    """Render the workflow YAML for a project whose digests live in `diffs_dir`."""
    return _TEMPLATE.format(marker=WORKFLOW_MARKER, diffs_dir=diffs_dir.strip("/"))


@dataclass(frozen=True)
class WorkflowInstallResult:
    """Outcome of one triediff-workflow install attempt."""

    action: str  # created | updated | unchanged | skipped | error
    path: Path | None
    note: str = ""


def _install_managed_workflow(
    project_root: Path,
    *,
    relpath: Path,
    marker: str,
    desired: str,
    dry_run: bool = False,
) -> WorkflowInstallResult:
    """Shared engine for marker-fenced workflow installs (see module docstring)."""
    if not (project_root / ".git").is_dir():
        return WorkflowInstallResult("skipped", None, "not a git repository")

    path = project_root / relpath

    if path.exists():
        existing = path.read_text()
        if marker not in existing:
            return WorkflowInstallResult("skipped", path, "user-owned (no managed-by marker)")
        if existing == desired:
            return WorkflowInstallResult("unchanged", path)
        if dry_run:
            return WorkflowInstallResult("updated", path, "dry-run: template drift")
        path.write_text(desired)
        return WorkflowInstallResult("updated", path, "template drift")

    if dry_run:
        return WorkflowInstallResult("created", path, "dry-run")
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(desired)
    except OSError as exc:
        return WorkflowInstallResult("error", path, str(exc))
    return WorkflowInstallResult("created", path)


def install_triediff_workflow(
    project_root: Path,
    *,
    diffs_dir: str,
    dry_run: bool = False,
) -> WorkflowInstallResult:
    """Idempotently install the triediff-comment workflow into `project_root`.

    See the module docstring for the create/update/skip contract. `dry_run`
    reports the action that would be taken without writing.
    """
    return _install_managed_workflow(
        project_root,
        relpath=WORKFLOW_RELPATH,
        marker=WORKFLOW_MARKER,
        desired=render_triediff_workflow(diffs_dir),
        dry_run=dry_run,
    )
