"""Install the triediff-comment GitHub workflow into a project.

`trie setup` drops `.github/workflows/triediff-comment.yml` into git repos so
every PR automatically gets a comment containing the latest session digest
(see `trie diff --write` / the `[diff]` config section). The workflow is
stateless: one comment per digest file, deduped by filename, linking to the
digest blob at the head SHA.

Install semantics mirror the other installers (idempotent, marker-fenced
ownership):

- file missing                          -> created
- file present with our marker, drifted -> updated (template evolution)
- file present with our marker, equal   -> unchanged
- file present without our marker       -> skipped (user-owned; never touched)
- no `.git` directory                   -> skipped (nothing to hook)

The workflow itself is inert off GitHub, so no remote detection is attempted —
a repo that never pushes to GitHub simply never runs it.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

WORKFLOW_RELPATH = Path(".github") / "workflows" / "triediff-comment.yml"

# First comment line of the rendered file. Presence marks the file as
# trie-managed (safe to regenerate); absence marks it user-owned.
WORKFLOW_MARKER = "# managed-by: trie setup (triediff-comment)"

# Raw string: shell line-continuations (`\` at EOL) and regex escapes (`\.`)
# must reach the YAML verbatim; a cooked string would eat them.
_TEMPLATE = r"""{marker}
# Comments each session digest ({diffs_dir}/*.md) added by a PR so reviewers
# see the intent-level summary of every commit before opening a file diff.
# Stateless: one comment per digest file, deduped by filename; a rewritten
# same-commit digest (amend) is not re-commented. Delete this file (or edit
# it — trie won't touch a file without the managed-by marker above) to opt
# out. Regenerated by `trie setup` when the template evolves.
name: triediff-comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{{{ github.event.pull_request.head.sha }}}}

      - name: Comment the PR's session digests
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          PR: ${{{{ github.event.pull_request.number }}}}
          HEAD_SHA: ${{{{ github.event.pull_request.head.sha }}}}
        run: |
          set -eu
          dir="{diffs_dir}"
          # Every digest file ADDED by this PR — not just the newest: a PR
          # spans many commits, each carrying its own digest. Oldest first
          # so comments read chronologically.
          added="$(gh api "repos/${{GITHUB_REPOSITORY}}/pulls/${{PR}}/files" --paginate \
                     --jq '.[] | select(.status == "added") | .filename' \
                   | grep "^${{dir}}/" | grep '\.md$' | sort || true)"
          if [ -z "$added" ]; then
            echo "no new digest files in this PR; nothing to comment"
            exit 0
          fi

          # Fetch existing comments once; dedupe each digest by filename.
          existing="$(gh api "repos/${{GITHUB_REPOSITORY}}/issues/${{PR}}/comments" \
                        --paginate --jq '.[].body' || true)"

          for path in $added; do
            name="$(basename "$path")"
            if printf '%s' "$existing" | grep -qF "$name"; then
              echo "digest $name already commented; skipping"
              continue
            fi
            if [ ! -f "$path" ]; then
              echo "digest $name no longer exists at head (pruned?); skipping"
              continue
            fi
            url="${{GITHUB_SERVER_URL}}/${{GITHUB_REPOSITORY}}/blob/${{HEAD_SHA}}/${{path}}"
            {{
              echo "### Session digest — [\`${{name}}\`](${{url}})"
              echo
              cat "$path"
            }} > /tmp/digest-comment.md
            gh pr comment "$PR" --body-file /tmp/digest-comment.md
          done
"""


def render_triediff_workflow(diffs_dir: str) -> str:
    """Render the workflow YAML for a project whose digests live in `diffs_dir`."""
    return _TEMPLATE.format(marker=WORKFLOW_MARKER, diffs_dir=diffs_dir.strip("/"))


@dataclass(frozen=True)
class WorkflowInstallResult:
    """Outcome of one triediff-workflow install attempt."""

    action: str  # created | updated | unchanged | skipped | error
    path: Path | None
    note: str = ""


def _install_managed_workflow(
    project_root: Path,
    *,
    relpath: Path,
    marker: str,
    desired: str,
    dry_run: bool = False,
) -> WorkflowInstallResult:
    """Shared engine for marker-fenced workflow installs (see module docstring)."""
    if not (project_root / ".git").is_dir():
        return WorkflowInstallResult("skipped", None, "not a git repository")

    path = project_root / relpath

    if path.exists():
        existing = path.read_text()
        if marker not in existing:
            return WorkflowInstallResult("skipped", path, "user-owned (no managed-by marker)")
        if existing == desired:
            return WorkflowInstallResult("unchanged", path)
        if dry_run:
            return WorkflowInstallResult("updated", path, "dry-run: template drift")
        path.write_text(desired)
        return WorkflowInstallResult("updated", path, "template drift")

    if dry_run:
        return WorkflowInstallResult("created", path, "dry-run")
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(desired)
    except OSError as exc:
        return WorkflowInstallResult("error", path, str(exc))
    return WorkflowInstallResult("created", path)


def install_triediff_workflow(
    project_root: Path,
    *,
    diffs_dir: str,
    dry_run: bool = False,
) -> WorkflowInstallResult:
    """Idempotently install the triediff-comment workflow into `project_root`.

    See the module docstring for the create/update/skip contract. `dry_run`
    reports the action that would be taken without writing.
    """
    return _install_managed_workflow(
        project_root,
        relpath=WORKFLOW_RELPATH,
        marker=WORKFLOW_MARKER,
        desired=render_triediff_workflow(diffs_dir),
        dry_run=dry_run,
    )


SYNC_BOT_RELPATH = Path(".github") / "workflows" / "trie-sync-bot.yml"

SYNC_BOT_MARKER = "# managed-by: trie setup (trie-sync-bot)"

_SYNC_BOT_TEMPLATE = """\
{marker}
# One-payer pattern: committers without model API keys push branches with
# stale triefacts (the local verify gate tells them so); this job regenerates
# the prose with the org's key and pushes the sync commit onto the PR branch.
# Requires the ANTHROPIC_API_KEY repository secret. Spend per run is capped
# by --budget below. Never runs for forks (secret safety).
# Delete this file to opt out; trie won't touch it if you remove the
# managed-by marker above. Installed by `trie setup --with-sync-bot`.
name: trie-sync-bot

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  sync:
    if: github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{{{ github.event.pull_request.head.ref }}}}

      - name: Install trie
        run: |
          pipx install uv
          uv tool install git+https://github.com/computer-reinvention/trie

      - name: Regenerate stale triefacts and push
        env:
          ANTHROPIC_API_KEY: ${{{{ secrets.ANTHROPIC_API_KEY }}}}
        run: |
          set -eu
          if trie -q verify; then
            echo "triefact tree is coherent; nothing to sync"
            exit 0
          fi
          trie sync --budget {budget}
          if git diff --quiet; then
            echo "sync produced no changes"
            exit 0
          fi
          git config user.name "trie-sync-bot"
          git config user.email "trie-sync-bot@users.noreply.github.com"
          git add -A
          git commit -m "chore(trie): regenerate stale triefacts [sync-bot]"
          git push
"""


def render_sync_bot_workflow(*, budget: float = 5.0) -> str:
    """Render the sync-bot workflow YAML with a per-run spend cap baked in."""
    return _SYNC_BOT_TEMPLATE.format(marker=SYNC_BOT_MARKER, budget=budget)


def install_sync_bot_workflow(
    project_root: Path,
    *,
    budget: float = 5.0,
    dry_run: bool = False,
) -> WorkflowInstallResult:
    """Idempotently install the sync-bot workflow. Opt-in only (never default):
    it spends the org's API budget and pushes commits to PR branches, so the
    caller must have passed an explicit flag. Same marker-fenced ownership
    contract as the triediff-comment workflow."""
    return _install_managed_workflow(
        project_root,
        relpath=SYNC_BOT_RELPATH,
        marker=SYNC_BOT_MARKER,
        desired=render_sync_bot_workflow(budget=budget),
        dry_run=dry_run,
    )
