"""Install the triediff-comment GitHub workflow into a project.

`trie setup` drops `.github/workflows/triediff-comment.yml` into git repos so
every PR automatically gets a comment containing the latest session digest
(see `trie diff --write` / the `[diff]` config section). The workflow is
stateless: one comment per digest file, deduped by filename, linking to the
digest blob at the head SHA.

Install semantics mirror the other installers (idempotent, marker-fenced
ownership):

- file missing                          -> created
- file present with our marker, drifted -> updated (template evolution)
- file present with our marker, equal   -> unchanged
- file present without our marker       -> skipped (user-owned; never touched)
- no `.git` directory                   -> skipped (nothing to hook)

The workflow itself is inert off GitHub, so no remote detection is attempted —
a repo that never pushes to GitHub simply never runs it.
"""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

WORKFLOW_RELPATH = Path(".github") / "workflows" / "triediff-comment.yml"

# First comment line of the rendered file. Presence marks the file as
# trie-managed (safe to regenerate); absence marks it user-owned.
WORKFLOW_MARKER = "# managed-by: trie setup (triediff-comment)"

_TEMPLATE = """\
{marker}
# Comments the latest session digest ({diffs_dir}/*.md) on each PR so
# reviewers see the intent-level summary before opening a single file diff.
# Delete this file (or edit it — trie won't touch a file without the
# managed-by marker above) to opt out. Regenerated by `trie setup` when
# the template evolves.
name: triediff-comment

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{{{ github.event.pull_request.head.sha }}}}

      - name: Comment the latest session digest
        env:
          GH_TOKEN: ${{{{ github.token }}}}
          PR: ${{{{ github.event.pull_request.number }}}}
          HEAD_SHA: ${{{{ github.event.pull_request.head.sha }}}}
        run: |
          set -eu
          dir="{diffs_dir}"
          # Timestamp-prefixed names: lexicographic max == newest.
          latest="$(ls "$dir"/*.md 2>/dev/null | sort | tail -1 || true)"
          if [ -z "$latest" ]; then
            echo "no digest files under $dir; nothing to comment"
            exit 0
          fi
          name="$(basename "$latest")"

          # Dedupe: skip when any existing comment already references this file.
          if gh api "repos/${{GITHUB_REPOSITORY}}/issues/${{PR}}/comments" \\
               --paginate --jq '.[].body' | grep -qF "$name"; then
            echo "digest $name already commented; skipping"
            exit 0
          fi

          url="${{GITHUB_SERVER_URL}}/${{GITHUB_REPOSITORY}}/blob/${{HEAD_SHA}}/${{dir}}/${{name}}"
          {{
            echo "### Session digest — [\\`${{name}}\\`](${{url}})"
            echo
            cat "$latest"
          }} > /tmp/digest-comment.md

          gh pr comment "$PR" --body-file /tmp/digest-comment.md
"""


def render_triediff_workflow(diffs_dir: str) -> str:
    """Render the workflow YAML for a project whose digests live in `diffs_dir`."""
    return _TEMPLATE.format(marker=WORKFLOW_MARKER, diffs_dir=diffs_dir.strip("/"))


@dataclass(frozen=True)
class WorkflowInstallResult:
    """Outcome of one triediff-workflow install attempt."""

    action: str  # created | updated | unchanged | skipped | error
    path: Path | None
    note: str = ""


def install_triediff_workflow(
    project_root: Path,
    *,
    diffs_dir: str,
    dry_run: bool = False,
) -> WorkflowInstallResult:
    """Idempotently install the triediff-comment workflow into `project_root`.

    See the module docstring for the create/update/skip contract. `dry_run`
    reports the action that would be taken without writing.
    """
    if not (project_root / ".git").is_dir():
        return WorkflowInstallResult("skipped", None, "not a git repository")

    path = project_root / WORKFLOW_RELPATH
    desired = render_triediff_workflow(diffs_dir)

    if path.exists():
        existing = path.read_text()
        if WORKFLOW_MARKER not in existing:
            return WorkflowInstallResult("skipped", path, "user-owned (no managed-by marker)")
        if existing == desired:
            return WorkflowInstallResult("unchanged", path)
        if dry_run:
            return WorkflowInstallResult("updated", path, "dry-run: template drift")
        path.write_text(desired)
        return WorkflowInstallResult("updated", path, "template drift")

    if dry_run:
        return WorkflowInstallResult("created", path, "dry-run")
    try:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(desired)
    except OSError as exc:
        return WorkflowInstallResult("error", path, str(exc))
    return WorkflowInstallResult("created", path)
