from __future__ import annotations

from pathlib import Path

from trie.workflow_install import (
    WORKFLOW_MARKER,
    WORKFLOW_RELPATH,
    install_triediff_workflow,
    render_triediff_workflow,
)


def _git_repo(tmp_path: Path) -> Path:
    (tmp_path / ".git").mkdir()
    return tmp_path


def test_render_bakes_in_diffs_dir_and_marker() -> None:
    text = render_triediff_workflow("triefacts/triediffs")
    assert text.startswith(WORKFLOW_MARKER)
    assert 'dir="triefacts/triediffs"' in text
    assert "gh pr comment" in text
    # GitHub expression syntax must survive the template formatting.
    assert "${{ github.event.pull_request.head.sha }}" in text

    custom = render_triediff_workflow("my/digests/")
    assert 'dir="my/digests"' in custom  # trailing slash normalised


def test_render_comments_every_pr_digest_not_just_latest() -> None:
    """A PR spans many commits, each with its own digest; the workflow must
    enumerate every digest file the PR ADDED (via the PR files API) and
    comment each un-commented one — 'newest only' skipped intermediates."""
    text = render_triediff_workflow("triefacts/triediffs")
    assert "pulls/${PR}/files" in text, "must enumerate PR-added files"
    assert 'select(.status == "added")' in text
    assert "for path in $added" in text, "must loop over every added digest"
    # Shell escapes must survive templating into valid script text.
    assert r"grep '\.md$'" in text
    assert (
        "--paginate \
"
        in text
    ), "line continuations must reach the YAML"


def test_render_prettifies_digest_for_display_only() -> None:
    """The workflow must transform the raw digest into a table-based comment at
    display time, WITHOUT depending on any change to the on-disk digest format.
    We extract the embedded awk transformer from the rendered YAML and run it
    against a canonical digest (bullet record + overflow comment, exactly as
    `render_digest_section` writes it) to prove the display transform works."""
    import shutil
    import subprocess

    if not shutil.which("awk"):
        import pytest

        pytest.skip("awk not on PATH")

    text = render_triediff_workflow("triefacts/triediffs")
    # The prettifier is an awk heredoc; it must be present in the rendered step.
    assert "cat > /tmp/triediff-fmt.awk" in text
    assert "| Change | Symbol | Summary |" in text

    # Pull the awk program out of the `<<'AWK' ... AWK` heredoc. The closing
    # delimiter is indented to match the YAML block scalar, so match a line
    # whose stripped content is exactly "AWK".
    start = text.index("<<'AWK'\n") + len("<<'AWK'\n")
    body_lines: list[str] = []
    for line in text[start:].splitlines():
        if line.strip() == "AWK":
            break
        body_lines.append(line.strip())
    awk_program = "\n".join(body_lines)

    # A canonical digest exactly as render_digest_section emits it: leading
    # auto-generated comment, title, narrative, a bullet Changes list capped
    # with an overflow HTML-comment record, then a Staged section.
    digest = (
        "<!-- auto-generated by `trie diff --write`\n"
        "     do not edit by hand -->\n"
        "\n"
        "## Ship the widget — 2026-08-01 (parent abc123def456)\n"
        "\n"
        "**Did a thing.**\n"
        "\n"
        "Some narrative body.\n"
        "\n"
        "### Changes\n"
        "\n"
        '- ~ m:f — "Old." → "New."\n'
        "- … and 1 more\n"
        "<!-- trie:changes-overflow\n"
        '- + m:g — "Fresh."\n'
        "-->\n"
        "\n"
        "### Staged (not applied)\n"
        "\n"
        "- create m:pending — Not yet applied.\n"
    )

    proc = subprocess.run(
        ["awk", awk_program],
        input=digest,
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stderr
    out = proc.stdout

    # Title leads (auto-generated header comment stripped).
    assert out.lstrip().startswith("## Ship the widget — 2026-08-01 (parent abc123def456)")
    assert "auto-generated by" not in out
    # Narrative preserved.
    assert "**Did a thing.**" in out
    assert "Some narrative body." in out
    # Changes rendered as a table with both rows (overflow folded in).
    assert "| Change | Symbol | Summary |" in out
    assert "| --- | --- | --- |" in out
    assert "| changed | `m:f` |" in out
    assert "| added | `m:g` |" in out
    # Display noise removed.
    assert "… and 1 more" not in out
    assert "trie:changes-overflow" not in out
    assert "-->" not in out
    # No raw bullet lines survive in the Changes section.
    assert "- ~ m:f" not in out
    # Staged section passes through untouched.
    assert "### Staged (not applied)" in out
    assert "- create m:pending — Not yet applied." in out


def test_render_changes_table_preserves_full_summary_under_utf8_awk() -> None:
    """Regression: the awk split each `- <marker> <qname> — <summary>` bullet
    by advancing a *hardcoded byte count* past the ` — ` separator (space +
    U+2014 em-dash + space = 5 bytes but only 3 characters). Under a
    character-counting awk (gawk / BSD awk in a UTF-8 locale — what GitHub's
    runners use) that ate the first two characters of every summary, so
    "Change …" rendered as "ange …". The fix advances by `length(SEP)`, which
    matches whatever unit the awk counts in. We force a UTF-8 locale here so the
    test exercises the char-counting path that actually broke in CI."""
    import os
    import shutil
    import subprocess

    if not shutil.which("awk"):
        import pytest

        pytest.skip("awk not on PATH")

    text = render_triediff_workflow("triefacts/triediffs")
    start = text.index("<<'AWK'\n") + len("<<'AWK'\n")
    body_lines: list[str] = []
    for line in text[start:].splitlines():
        if line.strip() == "AWK":
            break
        body_lines.append(line.strip())
    awk_program = "\n".join(body_lines)

    # Summaries whose FIRST characters after the separator are load-bearing:
    # if the split miscounts, these leading chars vanish. Includes an em-dash
    # *inside* a summary to prove only the first separator splits.
    digest = (
        "## T — 2026-08-01 (parent abc123def456)\n"
        "\n"
        "### Changes\n"
        "\n"
        "- ~ pkg/mod:Alpha — Change the default; keep it — really — intact.\n"
        "- + pkg/mod:Beta — Update the thing without dropping a character.\n"
        "- \u2212 pkg/mod:Gamma — Remove it cleanly.\n"
    )

    env = {**os.environ, "LC_ALL": "en_US.UTF-8", "LANG": "en_US.UTF-8"}
    proc = subprocess.run(
        ["awk", awk_program],
        input=digest,
        capture_output=True,
        text=True,
        env=env,
    )
    assert proc.returncode == 0, proc.stderr
    out = proc.stdout

    # Full summaries must survive with their leading characters intact.
    assert "| changed | `pkg/mod:Alpha` | Change the default; keep it — really — intact. |" in out
    assert "| added | `pkg/mod:Beta` | Update the thing without dropping a character. |" in out
    assert "| removed | `pkg/mod:Gamma` | Remove it cleanly. |" in out
    # And explicitly guard against the two-char-eaten corruption we fixed.
    assert "| ange the default" not in out
    assert "| date the thing" not in out


def test_install_creates_updates_unchanged(tmp_path: Path) -> None:
    repo = _git_repo(tmp_path)

    created = install_triediff_workflow(repo, diffs_dir="triefacts/triediffs")
    assert created.action == "created"
    path = repo / WORKFLOW_RELPATH
    assert path.is_file()
    assert WORKFLOW_MARKER in path.read_text()

    # Idempotent rerun: no change.
    again = install_triediff_workflow(repo, diffs_dir="triefacts/triediffs")
    assert again.action == "unchanged"

    # Template drift (e.g. diffs_dir changed in config): updated in place.
    moved = install_triediff_workflow(repo, diffs_dir="elsewhere/diffs")
    assert moved.action == "updated"
    assert 'dir="elsewhere/diffs"' in path.read_text()


def test_install_never_touches_user_owned_file(tmp_path: Path) -> None:
    repo = _git_repo(tmp_path)
    path = repo / WORKFLOW_RELPATH
    path.parent.mkdir(parents=True)
    path.write_text("name: my own workflow\n")

    result = install_triediff_workflow(repo, diffs_dir="triefacts/triediffs")
    assert result.action == "skipped"
    assert "user-owned" in result.note
    assert path.read_text() == "name: my own workflow\n"


def test_install_skips_outside_git_repo(tmp_path: Path) -> None:
    result = install_triediff_workflow(tmp_path, diffs_dir="triefacts/triediffs")
    assert result.action == "skipped"
    assert "not a git repository" in result.note
    assert not (tmp_path / WORKFLOW_RELPATH).exists()


def test_install_dry_run_writes_nothing(tmp_path: Path) -> None:
    repo = _git_repo(tmp_path)

    result = install_triediff_workflow(repo, diffs_dir="triefacts/triediffs", dry_run=True)
    assert result.action == "created"
    assert not (repo / WORKFLOW_RELPATH).exists()


def test_this_repos_installed_workflow_matches_the_template() -> None:
    """Regression guard: the template and this repo's installed copy must not drift.

    The `+5` summary-truncation bug was fixed in the template (and covered by
    template tests) while the committed `.github/workflows/triediff-comment.yml`
    kept shipping the broken awk for several releases — template tests can't see
    installed-file drift. This pins the repo's own copy to the rendered template;
    when the template evolves, re-run `trie setup` (or
    `install_triediff_workflow`) to regenerate the file and keep this green.
    """
    repo_root = Path(__file__).resolve().parents[1]
    installed = repo_root / WORKFLOW_RELPATH
    assert installed.exists(), "trie's own repo should carry the managed workflow"
    assert installed.read_text() == render_triediff_workflow("triefacts/triediffs")
