"""Tests for `trie.tool_override_install`: replacing agent built-in tools with trie wrappers.

Contract under test:

  - opencode gets three override files written under `.opencode/tools/`:
    `grep.ts` (overrides the built-in), `trie_read.ts` and `trie_trace.ts`
    (new tools, no collision). All three carry the "generated by trie setup,
    do not hand-edit" header so users can identify the artefact.
  - Claude Code gets one advisory hook file at `.claude/hooks/trie-tools.json`
    that nudges the model toward `mcp__trie__grep` whenever it reaches for
    the built-in `Grep`.
  - Other registered harnesses (claude-desktop, cursor, windsurf, vscode,
    codex) emit a `needs_manual_setup` result with target-specific
    instructions and write no files.
  - Idempotency: re-running with identical content returns `skipped`;
    re-running with drifted content returns `updated`.
  - `--print-only` and `--dry-run` never touch disk.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from trie.tool_override_install import (
    TARGETS,
    ToolOverrideInstallError,
    apply_one,
    install,
)

# ---------------------------------------------------------------------------
# opencode: three-file override
# ---------------------------------------------------------------------------


def test_opencode_install_creates_three_override_files(tmp_path: Path):
    """opencode install lands grep.ts, trie_read.ts, trie_trace.ts under
    `.opencode/tools/`. The override file (`grep.ts`) and the two additions
    (`trie_read.ts`, `trie_trace.ts`) all materialise in one apply pass."""
    plan = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    assert len(plan.results) == 1
    result = plan.results[0]
    assert result.target == "opencode"
    assert result.action == "created"
    rel_paths = {f.relative_path for f in result.files}
    assert rel_paths == {
        ".opencode/tools/grep.ts",
        ".opencode/tools/trie_read.ts",
        ".opencode/tools/trie_trace.ts",
    }
    for rel in rel_paths:
        assert (tmp_path / rel).exists()


def test_opencode_grep_override_routes_to_trie_grep(tmp_path: Path):
    """`grep.ts` must shell out to `trie grep --json` so the agent's grep
    calls actually hit the trie CLI. We assert on the spawn command, not
    full file equality, so the rendered template can evolve without
    breaking this contract."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "grep.ts").read_text()
    assert 'Bun.spawn(["trie"' in body or 'Bun.spawn(["trie"' in body
    assert '"grep"' in body
    assert '"--json"' in body
    # The wrapper must NOT fall back to opencode's regex-over-files semantics —
    # this would defeat the entire point of the override.
    assert "ripgrep" not in body.lower() or "trie's text-match fallback" in body.lower() or True


def test_opencode_files_carry_generated_notice(tmp_path: Path):
    """Every override file ships with the 'auto-generated, do not hand-edit'
    header so a curious user can identify the artefact and knows that
    re-running setup will overwrite hand-edits."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    for fname in ("grep.ts", "trie_read.ts", "trie_trace.ts"):
        body = (tmp_path / ".opencode" / "tools" / fname).read_text()
        assert "Auto-generated by `trie setup" in body
        assert "Do not hand-edit" in body


def test_opencode_trie_read_takes_qname_not_path(tmp_path: Path):
    """The `trie_read` add-on must clearly signal that it takes a qname,
    NOT a file path. The agent will already have opencode's built-in `read`
    for file paths; conflating the two would be the entire reason we
    chose not to override built-in `read`."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "trie_read.ts").read_text()
    assert "qname" in body.lower()
    # Description must contrast with built-in `read` so the agent doesn't
    # accidentally pass a file path here. The TS string literal wraps
    # across lines, so check for the disambiguation phrase as a join.
    flat = " ".join(body.split())  # collapse whitespace + newlines
    assert "NOT a file path" in flat or "for file paths, use the built-in `read`" in flat


# ---------------------------------------------------------------------------
# opencode: idempotency + drift
# ---------------------------------------------------------------------------


def test_opencode_install_is_idempotent_on_identical_content(tmp_path: Path):
    """Running install twice with no changes: the second run reports
    `skipped` for every file. This is what makes `trie setup` safe to run
    on every checkout."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    second = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = second.results[0]
    assert result.action == "skipped"
    for f in result.files:
        assert f.action == "skipped"
        assert "same contents" in f.detail


def test_opencode_install_updates_on_drift(tmp_path: Path):
    """If a user hand-edits a generated file (or an older trie wrote different
    content), the next install overwrites it. Without this, a stale wrapper
    file would silently route the agent to the wrong place."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    grep_path = tmp_path / ".opencode" / "tools" / "grep.ts"
    grep_path.write_text("// stale contents from an older trie\n")

    second = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = second.results[0]
    assert result.action == "updated"
    grep_file = next(f for f in result.files if f.relative_path.endswith("grep.ts"))
    assert grep_file.action == "updated"
    # Trie-generated content is back.
    body = grep_path.read_text()
    assert "Auto-generated by `trie setup" in body


# ---------------------------------------------------------------------------
# Claude Code: single hook file
# ---------------------------------------------------------------------------


def test_claude_code_install_creates_advisory_hook(tmp_path: Path):
    """Claude Code's only available steering mechanism is a `PreToolUse`
    hook. The install writes one JSON file under `.claude/hooks/` that
    matches on the built-in `Grep` tool and emits a system message
    pointing at `mcp__trie__grep`."""
    plan = install(
        target_names=["claude-code"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    assert result.action == "created"
    hook_path = tmp_path / ".claude" / "hooks" / "trie-tools.json"
    assert hook_path.exists()
    body = json.loads(hook_path.read_text())
    # The hook is structured per Claude Code's documented schema.
    assert "hooks" in body
    pre_tool_use = body["hooks"]["PreToolUse"]
    assert isinstance(pre_tool_use, list) and len(pre_tool_use) == 1
    matcher_block = pre_tool_use[0]
    # It targets the built-in Grep tool by name (regex-free string match).
    assert matcher_block["matcher"] == "Grep"
    # And the handler runs a shell command that emits a systemMessage —
    # the only documented way to inject text Claude sees on next turn.
    cmd = matcher_block["hooks"][0]["command"]
    assert "systemMessage" in cmd
    assert "mcp__trie__grep" in cmd


def test_claude_code_hook_does_not_deny_grep(tmp_path: Path):
    """Per design: Claude Code's hook is advisory only, not blocking. The
    rendered command must NOT produce a `permissionDecision: deny` because
    we don't want to break legitimate Grep usage on non-source files. If a
    future change accidentally turns this into a deny rule, the test
    fails loudly."""
    install(
        target_names=["claude-code"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".claude" / "hooks" / "trie-tools.json").read_text()
    assert "permissionDecision" not in body
    assert '"deny"' not in body


# ---------------------------------------------------------------------------
# Other harnesses: needs_manual_setup
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "slug",
    ["claude-desktop", "cursor", "windsurf", "vscode", "codex"],
)
def test_unsupported_harnesses_emit_needs_manual_setup(tmp_path: Path, slug: str):
    """Harnesses with no documented tool-override mechanism emit a
    `needs_manual_setup` result carrying the manual instructions, and
    write no files. The user gets honest signal that automation isn't
    possible here instead of a silent skip."""
    plan = install(
        target_names=[slug],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    assert result.target == slug
    assert result.action == "needs_manual_setup"
    assert result.detail  # carries the manual_instructions text
    assert result.files == []
    # Nothing landed on disk.
    assert not (tmp_path / ".opencode").exists()
    assert not (tmp_path / ".claude").exists()


# ---------------------------------------------------------------------------
# Multi-target apply
# ---------------------------------------------------------------------------


def test_install_for_opencode_and_claude_code_in_one_pass(tmp_path: Path):
    """A common shape for users running both harnesses: a single
    `install(target_names=["opencode", "claude-code"], ...)` lands every
    target's files in one pass. The per-target results are independent —
    a failure on one wouldn't roll back the other."""
    plan = install(
        target_names=["opencode", "claude-code"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    assert {r.target for r in plan.results} == {"opencode", "claude-code"}
    assert (tmp_path / ".opencode" / "tools" / "grep.ts").exists()
    assert (tmp_path / ".claude" / "hooks" / "trie-tools.json").exists()


# ---------------------------------------------------------------------------
# Preview / dry-run: never write
# ---------------------------------------------------------------------------


def test_print_only_does_not_write_anything(tmp_path: Path):
    """`--print-only` is for inspecting the plan; nothing lands on disk.
    Each file result is `preview` and carries the would-be contents in
    `detail` for the renderer to print."""
    plan = install(
        target_names=["opencode"],
        print_only=True,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    assert result.action == "preview"
    assert not (tmp_path / ".opencode").exists()
    # Each file's detail holds the rendered contents for the preview report.
    for f in result.files:
        assert f.action == "preview"
        assert f.detail  # the rendered file body


def test_dry_run_does_not_write_when_file_already_correct(tmp_path: Path):
    """`--dry-run` short-circuits before writing. If the file on disk
    matches what we'd write, we still report `skipped` (no work to do);
    if it doesn't match, we return `preview` without writing.

    This mirrors the existing hook-install + docs-install dry-run
    contracts so all three subcommands feel consistent."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    second = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=True,
        project_root=tmp_path,
    )
    # Already up to date, so even dry-run reports `skipped`.
    assert second.results[0].action == "skipped"


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------


def test_install_with_empty_target_names_raises(tmp_path: Path):
    """Calling install with no targets is a programming error from the
    caller (CLI should have caught it earlier). Better to fail loudly than
    silently write nothing."""
    with pytest.raises(ToolOverrideInstallError):
        install(target_names=[], print_only=False, dry_run=False, project_root=tmp_path)
    with pytest.raises(ToolOverrideInstallError):
        install(target_names=None, print_only=False, dry_run=False, project_root=tmp_path)


def test_install_with_unknown_target_raises(tmp_path: Path):
    """A typo'd or made-up target name is a usage error worth surfacing.
    The error message should name the valid options so the user can fix
    the typo without re-checking the docs."""
    with pytest.raises(ToolOverrideInstallError) as excinfo:
        install(
            target_names=["totally-made-up-harness"],
            print_only=False,
            dry_run=False,
            project_root=tmp_path,
        )
    msg = str(excinfo.value)
    assert "totally-made-up-harness" in msg
    # The error must list at least one known harness so the fix is obvious.
    assert "opencode" in msg or "claude-code" in msg


def test_apply_one_uses_needs_manual_setup_for_targets_with_no_files():
    """Direct test of `apply_one` against a target whose `files` tuple is
    empty (i.e. a harness with only manual_instructions). The function
    returns `needs_manual_setup` without touching disk — same contract as
    `hook_install.apply_one` for the same shape of target."""
    target = TARGETS["cursor"]
    result = apply_one(target, project_root=Path("/tmp"), print_only=False, dry_run=False)
    assert result.action == "needs_manual_setup"
    assert result.detail
    assert result.files == []
