"""Tests for `trie.tool_override_install`: replacing agent built-in tools with trie wrappers.

Contract under test:

  - opencode gets three override files written under `.opencode/tools/`:
    `grep.ts` (overrides the built-in), `trie_read.ts` and `trie_trace.ts`
    (new tools, no collision). All three carry the "generated by trie setup,
    do not hand-edit" header so users can identify the artefact.
  - Claude Code gets one advisory hook file at `.claude/hooks/trie-tools.json`
    that nudges the model toward `mcp__trie__grep` whenever it reaches for
    the built-in `Grep`.
  - Other registered harnesses (claude-desktop, cursor, windsurf, vscode,
    codex) emit a `needs_manual_setup` result with target-specific
    instructions and write no files.
  - Idempotency: re-running with identical content returns `skipped`;
    re-running with drifted content returns `updated`.
  - `--print-only` and `--dry-run` never touch disk.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from trie.tool_override_install import (
    TARGETS,
    ToolOverrideInstallError,
    apply_one,
    install,
)

# ---------------------------------------------------------------------------
# opencode: three-file override
# ---------------------------------------------------------------------------


def test_opencode_install_creates_three_override_files(tmp_path: Path):
    """opencode install lands grep.ts, read.ts, trie_trace.ts under
    `.opencode/tools/`. Two override built-ins (`grep`, `read`) and one
    addition (`trie_trace`) materialise in one apply pass."""
    plan = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    assert len(plan.results) == 1
    result = plan.results[0]
    assert result.target == "opencode"
    assert result.action == "created"
    written_paths = {f.relative_path for f in result.files if f.action == "created"}
    assert written_paths == {
        ".opencode/tools/grep.ts",
        ".opencode/tools/read.ts",
        ".opencode/tools/trie_trace.ts",
    }
    for rel in written_paths:
        assert (tmp_path / rel).exists()


def test_opencode_grep_override_routes_to_trie_grep(tmp_path: Path):
    """`grep.ts` must shell out to `trie grep --json` so the agent's grep
    calls actually hit the trie CLI. We assert on the spawn command, not
    full file equality, so the rendered template can evolve without
    breaking this contract."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "grep.ts").read_text()
    assert 'Bun.spawn(["trie"' in body or 'Bun.spawn(["trie"' in body
    assert '"grep"' in body
    assert '"--json"' in body


def test_opencode_files_carry_generated_notice(tmp_path: Path):
    """Every override file ships with the 'auto-generated, do not hand-edit'
    header so a curious user can identify the artefact and knows that
    re-running setup will overwrite hand-edits."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    for fname in ("grep.ts", "read.ts", "trie_trace.ts"):
        body = (tmp_path / ".opencode" / "tools" / fname).read_text()
        assert "Auto-generated by `trie setup" in body
        assert "Do not hand-edit" in body


# ---------------------------------------------------------------------------
# opencode `read.ts` override behaviour
# ---------------------------------------------------------------------------


def test_opencode_read_override_dispatches_on_qname_path_or_show_source(tmp_path: Path):
    """The `read.ts` override is the headline of this feature: one tool,
    three modes. The TypeScript body must contain the dispatch logic for
    all three (qname → trie read, path → triefact .md, show_source → raw
    source). We assert on the presence of the dispatch markers rather than
    full string equality so the template can evolve."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    # Mode 1: qname routing
    assert "looksLikeQname" in body
    assert '"read", "--json"' in body
    # Mode 2: triefact-by-path lookup
    assert "readTriefact" in body
    assert "triefacts" in body
    # Mode 3: show_source / line-range escape hatch to raw source
    assert "show_source" in body
    assert "readSourceFile" in body


def test_opencode_read_override_advertises_show_source_arg(tmp_path: Path):
    """The wrapper's `args` schema must include `show_source`, `offset`,
    and `limit`. These are the escape-hatch arguments — without them the
    agent has no way to fall back to raw source when it needs to."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    assert "show_source: tool.schema" in body
    assert "offset: tool.schema" in body
    assert "limit: tool.schema" in body


def test_opencode_read_override_qname_detection_excludes_urls_and_drives(tmp_path: Path):
    """The qname detection must NOT misfire on URLs (https://...) or
    Windows drive prefixes (C:\\...). Both contain `:` but neither is a
    qname. The detection regex's purpose is to draw that boundary
    precisely; this test catches a regression in the detection rule."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    # The detection rule must explicitly check for URL schemes and Windows
    # drive prefixes. Both regexes are mentioned in `looksLikeQname`.
    assert "looksLikeQname" in body
    # URL scheme regex — `scheme://`
    assert "://" in body
    # Windows drive regex — `[A-Za-z]:[\\/]`
    assert "[A-Za-z]:" in body


def test_opencode_read_override_emits_telemetry_from_typescript(tmp_path: Path):
    """The `read.ts` wrapper handles three out of four call paths in-process
    (triefact lookup, source fallthrough, show_source escape). Only the
    qname path shells out to `trie read`, which gets `cli_call` telemetry
    for free from Python. Without TS-side emission, the other three paths
    would be invisible to `trie audit`.

    The wrapper must therefore embed its own telemetry plumbing: a helper
    that resolves the log path from trie.toml's [debug] section (or the
    TRIE_DEBUG env var), tags each call with the dispatch `mode`, and
    appends a `cli_call` JSONL event to debug.jsonl. We assert on the
    structural markers (function names, event-shape strings) rather than
    full template equality so the rendered TS can evolve."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    # Telemetry helpers must be present in the rendered TS.
    assert "emitTelemetry" in body
    assert "resolveTelemetryConfig" in body
    assert "extractTomlSection" in body
    # Event name + tool name are baked into every emit call.
    assert '"cli_call"' in body
    assert '"read"' in body
    # The `mode` field is what distinguishes the four dispatch branches.
    assert "mode" in body
    # Honours TRIE_DEBUG the same way Python does (env var wins).
    assert "TRIE_DEBUG" in body


def test_opencode_read_override_appends_telemetry_atomically(tmp_path: Path):
    """The telemetry write must use append-mode I/O (Node's `appendFile`),
    not read-modify-write. Concurrent `read` calls from a long-running
    opencode session must not race the log file. The rendered TS must
    import `appendFile` from `node:fs/promises` rather than the broader
    `writeFile` or any read-then-write pattern."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    # Single-line `appendFile` from node:fs/promises is the atomic-on-POSIX
    # write primitive we want for JSONL telemetry.
    assert "appendFile" in body
    # And we shouldn't be doing readback-then-write for the log.
    assert "readFile(cfg.logPath" not in body


def test_opencode_read_override_handles_absolute_paths(tmp_path: Path):
    """Earlier versions of `readSourceFile` did `normalize(join(cwd, path))`
    unconditionally. Node's `path.join` strips the leading slash on the
    second argument when it's absolute, producing `<cwd>/<abs-without-slash>`
    — a bogus path that ENOENTs every time. Agents do pass absolute paths
    (copy-paste from grep results, stack traces), so the wrapper must
    detect absolute paths and use them verbatim. We assert on the
    structural marker `isAbsolute(path)` being present in the resolver."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    # The resolver helper exists and branches on isAbsolute.
    assert "resolveAbsolutePath" in body
    # The resolver uses isAbsolute to skip joining onto cwd.
    assert "isAbsolute(path) ? normalize(path)" in body
    # The triefact lookup also handles absolute paths (strips cwd prefix
    # when the absolute path is inside the project tree).
    assert "projectRelativePath" in body


def test_opencode_read_override_advertises_full_arg(tmp_path: Path):
    """Compact mode is the new default for `read(path)`. The wrapper must
    advertise a `full: bool` arg so the agent can opt back into the
    historical "return the entire triefact verbatim" behaviour when it
    actually needs the whole bundle (e.g. for narrow files). Without
    this, agents would have no escape hatch from compact mode."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    assert "full: tool.schema" in body
    # Description must mention `compact` so the agent understands the
    # default behaviour.
    assert "compact" in body.lower() or "COMPACT" in body


def test_opencode_read_override_emits_compact_renderer(tmp_path: Path):
    """Compact rendering happens TS-side. The rendered wrapper must
    contain the helpers — frontmatter parser, sentinel-section scanner,
    and the renderer that ties them together. We assert on the helper
    names rather than full template equality so the rendering template
    can evolve."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    assert "renderCompact" in body
    assert "parseFrontMatter" in body
    assert "extractSections" in body
    # The compact mode and full mode each tag their telemetry differently
    # so the audit can split usage. The two mode names must appear.
    assert "triefact_compact" in body
    assert "triefact_full" in body


def test_opencode_trie_read_obsolete_file_removed_on_apply(tmp_path: Path):
    """Earlier versions of `trie setup --override-builtins` shipped a
    separate `.opencode/tools/trie_read.ts` add-on. The new `read.ts`
    override subsumes it (qname-shaped paths route to `trie read`
    automatically), so re-running setup must clean up the stale file —
    otherwise the agent ends up with two tools that do the same thing."""
    # Simulate a prior install that wrote the now-obsolete trie_read.ts.
    stale_dir = tmp_path / ".opencode" / "tools"
    stale_dir.mkdir(parents=True)
    stale_path = stale_dir / "trie_read.ts"
    stale_path.write_text("// stale from a prior trie setup\n")

    plan = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    # The stale file is gone; the per-file result for the cleanup is
    # included in the plan so the user sees what migration happened.
    assert not stale_path.exists()
    cleanup_results = [f for f in result.files if f.relative_path.endswith("trie_read.ts")]
    assert len(cleanup_results) == 1
    assert cleanup_results[0].action == "updated"
    assert "removed obsolete" in cleanup_results[0].description.lower()


def test_opencode_obsolete_cleanup_is_noop_on_fresh_install(tmp_path: Path):
    """A first-time install on a clean project should not error out trying
    to delete files that were never there. The cleanup step reports
    `skipped` for absent files and continues."""
    plan = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    cleanup_results = [f for f in result.files if "obsolete" in f.description.lower()]
    assert cleanup_results, "expected at least one cleanup result in the plan"
    for r in cleanup_results:
        assert r.action == "skipped"
        assert "nothing to clean up" in r.detail.lower()


# ---------------------------------------------------------------------------
# opencode: idempotency + drift
# ---------------------------------------------------------------------------


def test_opencode_install_is_idempotent_on_identical_content(tmp_path: Path):
    """Running install twice with no changes: the second run reports
    `skipped` for every file. This is what makes `trie setup` safe to run
    on every checkout."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    second = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = second.results[0]
    assert result.action == "skipped"
    # Write results report "same contents"; cleanup results for absent
    # obsolete files report "nothing to clean up". Both are `skipped`,
    # but the detail strings differ — filter by description before
    # asserting on detail.
    for f in result.files:
        assert f.action == "skipped"
        if "obsolete" not in f.description.lower():
            assert "same contents" in f.detail


def test_opencode_install_updates_on_drift(tmp_path: Path):
    """If a user hand-edits a generated file (or an older trie wrote different
    content), the next install overwrites it. Without this, a stale wrapper
    file would silently route the agent to the wrong place."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    grep_path = tmp_path / ".opencode" / "tools" / "grep.ts"
    grep_path.write_text("// stale contents from an older trie\n")

    second = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = second.results[0]
    assert result.action == "updated"
    grep_file = next(f for f in result.files if f.relative_path.endswith("grep.ts"))
    assert grep_file.action == "updated"
    # Trie-generated content is back.
    body = grep_path.read_text()
    assert "Auto-generated by `trie setup" in body


# ---------------------------------------------------------------------------
# Claude Code: single hook file
# ---------------------------------------------------------------------------


def test_claude_code_install_creates_advisory_hook(tmp_path: Path):
    """Claude Code's only available steering mechanism is a `PreToolUse`
    hook. The install writes one JSON file under `.claude/hooks/` that
    matches on the built-in `Grep` tool and emits a system message
    pointing at `mcp__trie__grep`."""
    plan = install(
        target_names=["claude-code"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    assert result.action == "created"
    hook_path = tmp_path / ".claude" / "hooks" / "trie-tools.json"
    assert hook_path.exists()
    body = json.loads(hook_path.read_text())
    # The hook is structured per Claude Code's documented schema.
    assert "hooks" in body
    pre_tool_use = body["hooks"]["PreToolUse"]
    assert isinstance(pre_tool_use, list) and len(pre_tool_use) == 1
    matcher_block = pre_tool_use[0]
    # It targets the built-in Grep tool by name (regex-free string match).
    assert matcher_block["matcher"] == "Grep"
    # And the handler runs a shell command that emits a systemMessage —
    # the only documented way to inject text Claude sees on next turn.
    cmd = matcher_block["hooks"][0]["command"]
    assert "systemMessage" in cmd
    assert "mcp__trie__grep" in cmd


def test_claude_code_hook_does_not_deny_grep(tmp_path: Path):
    """Per design: Claude Code's hook is advisory only, not blocking. The
    rendered command must NOT produce a `permissionDecision: deny` because
    we don't want to break legitimate Grep usage on non-source files. If a
    future change accidentally turns this into a deny rule, the test
    fails loudly."""
    install(
        target_names=["claude-code"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".claude" / "hooks" / "trie-tools.json").read_text()
    assert "permissionDecision" not in body
    assert '"deny"' not in body


# ---------------------------------------------------------------------------
# Other harnesses: needs_manual_setup
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "slug",
    ["claude-desktop", "cursor", "windsurf", "vscode", "codex"],
)
def test_unsupported_harnesses_emit_needs_manual_setup(tmp_path: Path, slug: str):
    """Harnesses with no documented tool-override mechanism emit a
    `needs_manual_setup` result carrying the manual instructions, and
    write no files. The user gets honest signal that automation isn't
    possible here instead of a silent skip."""
    plan = install(
        target_names=[slug],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    assert result.target == slug
    assert result.action == "needs_manual_setup"
    assert result.detail  # carries the manual_instructions text
    assert result.files == []
    # Nothing landed on disk.
    assert not (tmp_path / ".opencode").exists()
    assert not (tmp_path / ".claude").exists()


# ---------------------------------------------------------------------------
# Multi-target apply
# ---------------------------------------------------------------------------


def test_install_for_opencode_and_claude_code_in_one_pass(tmp_path: Path):
    """A common shape for users running both harnesses: a single
    `install(target_names=["opencode", "claude-code"], ...)` lands every
    target's files in one pass. The per-target results are independent —
    a failure on one wouldn't roll back the other."""
    plan = install(
        target_names=["opencode", "claude-code"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    assert {r.target for r in plan.results} == {"opencode", "claude-code"}
    assert (tmp_path / ".opencode" / "tools" / "grep.ts").exists()
    assert (tmp_path / ".claude" / "hooks" / "trie-tools.json").exists()


# ---------------------------------------------------------------------------
# Preview / dry-run: never write
# ---------------------------------------------------------------------------


def test_print_only_does_not_write_anything(tmp_path: Path):
    """`--print-only` is for inspecting the plan; nothing lands on disk.
    Each file-to-write result is `preview` and carries the would-be
    contents in `detail` for the renderer to print. Obsolete-file
    cleanups for files that don't exist report `skipped` regardless of
    --print-only because there's nothing to preview removing."""
    plan = install(
        target_names=["opencode"],
        print_only=True,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    assert result.action == "preview"
    assert not (tmp_path / ".opencode").exists()
    # The new-file write results are all `preview` with rendered contents
    # in `detail`. Cleanup-of-non-existent results are `skipped` (no body
    # to render). Filter by description to separate the two cohorts.
    write_results = [f for f in result.files if "obsolete" not in f.description.lower()]
    for f in write_results:
        assert f.action == "preview"
        assert f.detail  # the rendered file body


def test_dry_run_does_not_write_when_file_already_correct(tmp_path: Path):
    """`--dry-run` short-circuits before writing. If the file on disk
    matches what we'd write, we still report `skipped` (no work to do);
    if it doesn't match, we return `preview` without writing.

    This mirrors the existing hook-install + docs-install dry-run
    contracts so all three subcommands feel consistent."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    second = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=True,
        project_root=tmp_path,
    )
    # Already up to date, so even dry-run reports `skipped`.
    assert second.results[0].action == "skipped"


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------


def test_install_with_empty_target_names_raises(tmp_path: Path):
    """Calling install with no targets is a programming error from the
    caller (CLI should have caught it earlier). Better to fail loudly than
    silently write nothing."""
    with pytest.raises(ToolOverrideInstallError):
        install(target_names=[], print_only=False, dry_run=False, project_root=tmp_path)
    with pytest.raises(ToolOverrideInstallError):
        install(target_names=None, print_only=False, dry_run=False, project_root=tmp_path)


def test_install_with_unknown_target_raises(tmp_path: Path):
    """A typo'd or made-up target name is a usage error worth surfacing.
    The error message should name the valid options so the user can fix
    the typo without re-checking the docs."""
    with pytest.raises(ToolOverrideInstallError) as excinfo:
        install(
            target_names=["totally-made-up-harness"],
            print_only=False,
            dry_run=False,
            project_root=tmp_path,
        )
    msg = str(excinfo.value)
    assert "totally-made-up-harness" in msg
    # The error must list at least one known harness so the fix is obvious.
    assert "opencode" in msg or "claude-code" in msg


def test_apply_one_uses_needs_manual_setup_for_targets_with_no_files():
    """Direct test of `apply_one` against a target whose `files` tuple is
    empty (i.e. a harness with only manual_instructions). The function
    returns `needs_manual_setup` without touching disk — same contract as
    `hook_install.apply_one` for the same shape of target."""
    target = TARGETS["cursor"]
    result = apply_one(target, project_root=Path("/tmp"), print_only=False, dry_run=False)
    assert result.action == "needs_manual_setup"
    assert result.detail
    assert result.files == []
