"""Tests for `trie.docs_install`: project-local agent documentation install.

Contract under test:

  - `install(project_root=...)` always writes `TRIE.md` at the project
    root. The bundled body comes from `trie/data/TRIE.md`; the file gets
    a generated-file notice prepended so a curious reader knows where it
    came from.
  - When `AGENTS.md` or `CLAUDE.md` already exist at the project root,
    each receives a marker-fenced pointer block. Missing files are NOT
    materialised — that's user-owned territory.
  - Idempotency: running twice in a row produces `skipped` results when
    the on-disk content already matches the canonical write.
  - The pointer block has stable markers so the next run finds and
    refreshes only the block, leaving the rest of the file alone.
  - `--print-only` / `--dry-run` never write files (still returns
    `preview` results with full would-be contents).
"""

from __future__ import annotations

from pathlib import Path

from trie.docs_install import (
    AGENT_DOC_FILES,
    POINTER_END_MARKER,
    POINTER_LINE,
    POINTER_MARKER,
    TRIE_DOC_FILENAME,
    _splice_pointer_block,
    install,
)

# ---------------------------------------------------------------------------
# TRIE.md materialisation
# ---------------------------------------------------------------------------


def test_install_creates_trie_md_at_project_root(tmp_path: Path):
    """The headline contract: `install` writes a project-local TRIE.md.

    The body must be non-empty (we've actually loaded the bundled doc, not
    just touched the file) and must carry the generated-file notice so a
    reader can identify its provenance at a glance.
    """
    plan = install(project_root=tmp_path, print_only=False, dry_run=False)
    trie_md = tmp_path / TRIE_DOC_FILENAME
    assert trie_md.exists()
    body = trie_md.read_text(encoding="utf-8")
    assert "Generated by `trie setup`" in body
    # Sanity check we actually loaded the bundled body — the doc opens
    # with the title of the guide.
    assert "Using trie" in body
    # The plan reflects the write.
    trie_result = next(r for r in plan.results if r.target == TRIE_DOC_FILENAME)
    assert trie_result.action == "created"


def test_install_trie_md_is_idempotent_on_identical_content(tmp_path: Path):
    """A second `install` against the same project root sees `skipped`.

    This is what makes `trie setup` safe to run on every checkout: the
    work is bounded by what actually changed.
    """
    install(project_root=tmp_path, print_only=False, dry_run=False)
    second = install(project_root=tmp_path, print_only=False, dry_run=False)
    trie_result = next(r for r in second.results if r.target == TRIE_DOC_FILENAME)
    assert trie_result.action == "skipped"
    assert "up to date" in trie_result.detail.lower()


def test_install_trie_md_updates_on_drift(tmp_path: Path):
    """If something (or someone) modified TRIE.md since the last install,
    `install` rewrites it. The contract is "TRIE.md mirrors the bundled
    doc"; hand-edits don't survive — that's why the generated notice tells
    the user so."""
    install(project_root=tmp_path, print_only=False, dry_run=False)
    (tmp_path / TRIE_DOC_FILENAME).write_text("garbage that doesn't match\n")
    second = install(project_root=tmp_path, print_only=False, dry_run=False)
    trie_result = next(r for r in second.results if r.target == TRIE_DOC_FILENAME)
    assert trie_result.action == "updated"
    # The on-disk content is back to the bundled body.
    assert "Using trie" in (tmp_path / TRIE_DOC_FILENAME).read_text(encoding="utf-8")


# ---------------------------------------------------------------------------
# Pointer block: AGENTS.md / CLAUDE.md
# ---------------------------------------------------------------------------


def test_install_skips_pointer_when_agent_files_absent(tmp_path: Path):
    """If neither AGENTS.md nor CLAUDE.md exists, `install` doesn't create
    them. We treat those filenames as user-authored conventions; conjuring
    them out of thin air implies an opinion we don't have.

    The TRIE.md write still happens — that's the trie-owned artefact.
    """
    plan = install(project_root=tmp_path, print_only=False, dry_run=False)
    assert not (tmp_path / "AGENTS.md").exists()
    assert not (tmp_path / "CLAUDE.md").exists()
    # Only TRIE.md is in the plan; no pointer-line results were emitted.
    assert {r.target for r in plan.results} == {TRIE_DOC_FILENAME}


def test_install_appends_pointer_to_existing_agents_md(tmp_path: Path):
    """When AGENTS.md is present, the pointer block lands at the end with
    a blank-line separator from whatever the user had above."""
    (tmp_path / "AGENTS.md").write_text("# AGENTS.md\n\nOur conventions.\n")
    install(project_root=tmp_path, print_only=False, dry_run=False)
    content = (tmp_path / "AGENTS.md").read_text(encoding="utf-8")
    # User's content is preserved verbatim.
    assert "Our conventions." in content
    # Pointer block was added.
    assert POINTER_MARKER in content
    assert POINTER_END_MARKER in content
    assert "TRIE.md" in content
    # The pointer points at TRIE.md, not at some external URL — agents on
    # offline boxes still resolve the link.
    assert POINTER_LINE in content


def test_install_appends_pointer_to_existing_claude_md(tmp_path: Path):
    """CLAUDE.md gets the same treatment as AGENTS.md. Both conventions
    are equally supported; whichever the user maintains is the one that
    becomes discoverable."""
    (tmp_path / "CLAUDE.md").write_text("# Claude conventions\n")
    install(project_root=tmp_path, print_only=False, dry_run=False)
    content = (tmp_path / "CLAUDE.md").read_text(encoding="utf-8")
    assert POINTER_MARKER in content
    assert "TRIE.md" in content


def test_install_handles_both_agents_and_claude_files(tmp_path: Path):
    """Most projects pick one convention, but a few keep both (or
    symlink). Each file gets its own pointer block; the plan reports
    both writes."""
    (tmp_path / "AGENTS.md").write_text("# AGENTS.md\n")
    (tmp_path / "CLAUDE.md").write_text("# CLAUDE.md\n")
    plan = install(project_root=tmp_path, print_only=False, dry_run=False)
    targets = {r.target for r in plan.results}
    assert "AGENTS.md" in targets
    assert "CLAUDE.md" in targets
    # Both files now have a pointer block.
    for filename in ("AGENTS.md", "CLAUDE.md"):
        assert POINTER_MARKER in (tmp_path / filename).read_text(encoding="utf-8")


def test_install_pointer_is_idempotent(tmp_path: Path):
    """Two installs in a row: the second's pointer result is `skipped`
    because the marker block is already present with the same body."""
    (tmp_path / "AGENTS.md").write_text("# AGENTS.md\n\nOriginal content.\n")
    install(project_root=tmp_path, print_only=False, dry_run=False)
    second = install(project_root=tmp_path, print_only=False, dry_run=False)
    agents_result = next(r for r in second.results if r.target == "AGENTS.md")
    assert agents_result.action == "skipped"


def test_install_refreshes_stale_pointer_block_in_place(tmp_path: Path):
    """If an older trie version wrote a slightly different pointer line,
    a new install must replace ONLY the block between markers, leaving
    everything else untouched."""
    stale_block = (
        f"{POINTER_MARKER}\nOLD pointer line that no longer matches.\n{POINTER_END_MARKER}\n"
    )
    user_content = "# AGENTS.md\n\nUser content above.\n"
    user_below = "\nUser content below the block.\n"
    (tmp_path / "AGENTS.md").write_text(user_content + "\n" + stale_block + user_below)

    install(project_root=tmp_path, print_only=False, dry_run=False)

    final = (tmp_path / "AGENTS.md").read_text(encoding="utf-8")
    # User content on both sides preserved.
    assert "User content above." in final
    assert "User content below the block." in final
    # Old pointer is gone, new one is there.
    assert "OLD pointer line that no longer matches." not in final
    assert POINTER_LINE in final


# ---------------------------------------------------------------------------
# Preview / dry-run: never write
# ---------------------------------------------------------------------------


def test_print_only_does_not_write_anything(tmp_path: Path):
    """`--print-only` is for inspecting the plan; nothing lands on disk."""
    (tmp_path / "AGENTS.md").write_text("# AGENTS.md\n")
    plan = install(project_root=tmp_path, print_only=True, dry_run=False)
    # TRIE.md not created.
    assert not (tmp_path / TRIE_DOC_FILENAME).exists()
    # AGENTS.md unchanged.
    assert (tmp_path / "AGENTS.md").read_text(encoding="utf-8") == "# AGENTS.md\n"
    # The plan still describes what would happen.
    for r in plan.results:
        assert r.action == "preview"


def test_dry_run_does_not_write_when_file_already_correct(tmp_path: Path):
    """`--dry-run` short-circuits at the "would write" step. If the file
    on disk matches what we'd write, we still report `skipped` (no work
    to do); if it doesn't match, we return `preview` without writing."""
    install(project_root=tmp_path, print_only=False, dry_run=False)
    second = install(project_root=tmp_path, print_only=False, dry_run=True)
    trie_result = next(r for r in second.results if r.target == TRIE_DOC_FILENAME)
    # Already up to date, so even dry-run reports `skipped` — the comparison
    # happens before the dry-run early-return.
    assert trie_result.action == "skipped"


# ---------------------------------------------------------------------------
# Internal: _splice_pointer_block
# ---------------------------------------------------------------------------


def test_splice_appends_when_marker_absent(tmp_path: Path):
    """Direct test of the splice routine: no marker → append at end with
    a blank-line separator. Belt-and-braces against future regressions in
    the higher-level write path."""
    original = "# Header\n\nSome content.\n"
    result = _splice_pointer_block(original)
    assert result.startswith("# Header\n\nSome content.\n")
    assert POINTER_MARKER in result
    assert POINTER_END_MARKER in result
    # No stray double-blank-lines that would accumulate on repeated calls.
    assert "\n\n\n\n" not in result


def test_splice_replaces_when_marker_present():
    """When the marker block exists, splice rewrites between markers only
    and never duplicates."""
    original = f"# Header\n\n{POINTER_MARKER}\nOLD body.\n{POINTER_END_MARKER}\n\nFooter content.\n"
    result = _splice_pointer_block(original)
    assert "OLD body." not in result
    # Only one marker pair survives — no duplication on repeated rewrites.
    assert result.count(POINTER_MARKER) == 1
    assert result.count(POINTER_END_MARKER) == 1
    # Surrounding content is preserved.
    assert "# Header" in result
    assert "Footer content." in result


def test_splice_handles_empty_input():
    """Edge case: an empty file gets only the pointer block, no leading
    blank line to clean up."""
    result = _splice_pointer_block("")
    assert result.startswith(POINTER_MARKER)


# ---------------------------------------------------------------------------
# Plan registration: AGENT_DOC_FILES is the canonical list
# ---------------------------------------------------------------------------


def test_agent_doc_files_covers_known_conventions():
    """A safety net: if someone changes AGENT_DOC_FILES, this test fails
    visibly so the conventions list stays explicit rather than drifting
    silently."""
    assert AGENT_DOC_FILES == ("AGENTS.md", "CLAUDE.md")
