"""Tests for `trie.tool_override_install`: replacing agent built-in tools with trie wrappers.

Contract under test:

  - opencode gets three override files written under `.opencode/tools/`:
    `grep.ts` and `read.ts` (override the built-ins), plus `trace.ts`
    (new tool, no collision). All three carry the "generated by trie
    setup, do not hand-edit" header so users can identify the artefact.
  - Claude Code gets one advisory hook file at `.claude/hooks/trie-tools.json`
    that nudges the model toward `mcp__trie__grep` whenever it reaches for
    the built-in `Grep`.
  - Other registered harnesses (claude-desktop, cursor, windsurf, vscode,
    codex) emit a `needs_manual_setup` result with target-specific
    instructions and write no files.
  - Idempotency: re-running with identical content returns `skipped`;
    re-running with drifted content returns `updated`.
  - `--print-only` and `--dry-run` never touch disk.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from trie.tool_override_install import (
    TARGETS,
    ToolOverrideInstallError,
    apply_one,
    install,
)

# ---------------------------------------------------------------------------
# opencode: three-file override
# ---------------------------------------------------------------------------


def test_opencode_install_creates_override_files(tmp_path: Path):
    """opencode install lands all tool files under `.opencode/tools/`.
    The 3 original overrides/additions plus the 8 new extended tools
    all materialise in one apply pass."""
    plan = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    assert len(plan.results) == 1
    result = plan.results[0]
    assert result.target == "opencode"
    assert result.action == "created"
    written_paths = {f.relative_path for f in result.files if f.action == "created"}
    # The 3 original tools must still be present.
    for expected in (
        ".opencode/tools/grep.ts",
        ".opencode/tools/read.ts",
        ".opencode/tools/trace.ts",
    ):
        assert expected in written_paths, f"missing {expected}"
    # The 8 new extended tools must also be present.
    for expected in (
        ".opencode/tools/grep_str.ts",
        ".opencode/tools/grep_entry_points.ts",
        ".opencode/tools/grep_symbol.ts",
        ".opencode/tools/grep_symbol_neighbours.ts",
        ".opencode/tools/explain_symbol.ts",
        ".opencode/tools/explain_symbol_refs.ts",
        ".opencode/tools/trace_flow.ts",
        ".opencode/tools/explain_flow.ts",
    ):
        assert expected in written_paths, f"missing {expected}"
    for rel in written_paths:
        assert (tmp_path / rel).exists()


def test_opencode_grep_override_routes_to_trie_grep(tmp_path: Path):
    """`grep.ts` must shell out to `trie grep` so the agent's grep calls
    actually hit the trie CLI. We assert on the spawn command, not full
    file equality, so the rendered template can evolve without breaking
    this contract."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "grep.ts").read_text()
    assert 'Bun.spawn(["trie"' in body
    assert '"grep"' in body
    # plain-text output; no --json flag needed
    assert '"--json"' not in body


def test_opencode_files_carry_generated_notice(tmp_path: Path):
    """Every override file ships with the 'auto-generated, do not hand-edit'
    header so a curious user can identify the artefact and knows that
    re-running setup will overwrite hand-edits."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    for fname in ("grep.ts", "read.ts", "trace.ts"):
        body = (tmp_path / ".opencode" / "tools" / fname).read_text()
        assert "Auto-generated by `trie setup" in body
        assert "Do not hand-edit" in body


def test_opencode_rendered_files_have_balanced_backticks_per_line(tmp_path: Path):
    """Regression guard for a class of bug where a Python-side single-
    backslash `\\n` inside a TypeScript single-line comment expands to a real
    newline. The result splits a `// ...` line in two: the second half loses
    its leading `//`, the parser treats it as code, and bun fails with
    "Expected ';' but found ..." — opencode then can't load `read.ts` and
    the entire session silently dies (no tool registration → no responses).

    The narrow invariant that catches the bug class: in any rendered `.ts`
    file, no comment line (starts with `//`) may carry an unterminated
    backtick. Either the line has zero backticks, or an even count. If a
    comment line ever opens an unmatched backtick, the next line(s) get
    swallowed as a JS template literal.
    """
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    for fname in ("grep.ts", "read.ts", "trace.ts"):
        body = (tmp_path / ".opencode" / "tools" / fname).read_text()
        for lineno, line in enumerate(body.splitlines(), 1):
            stripped = line.lstrip()
            if not stripped.startswith("//"):
                continue
            count = stripped.count("`")
            assert count % 2 == 0, (
                f"{fname}:{lineno} has an unbalanced backtick in a comment "
                f"({count} backticks). This opens a stray template literal "
                f"that breaks bun's parser. Likely cause: an unescaped `\\n` "
                f"in the Python renderer split a single-line comment in two. "
                f"Line: {line!r}"
            )


# ---------------------------------------------------------------------------
# opencode `read.ts` override behaviour
# ---------------------------------------------------------------------------


def test_opencode_read_override_dispatches_on_qname_path_or_show_source(tmp_path: Path):
    """The `read.ts` override is the headline of this feature: one tool,
    three modes. The TypeScript body must contain the dispatch logic for
    all three (qname → trie read, path → triefact .md, show_source → raw
    source). We assert on the presence of the dispatch markers rather than
    full string equality so the template can evolve."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    # Mode 1: qname routing — plain-text output, no --json
    assert "looksLikeQname" in body
    assert '"read"' in body
    assert '"--json"' not in body
    # Mode 2: triefact-by-path lookup
    assert "readTriefact" in body
    assert "triefacts" in body
    # Mode 3: show_source / line-range escape hatch to raw source
    assert "show_source" in body
    assert "readSourceFile" in body


def test_opencode_read_override_advertises_show_source_arg(tmp_path: Path):
    """The wrapper's `args` schema must include `show_source`, `offset`,
    and `limit`. These are the escape-hatch arguments — without them the
    agent has no way to fall back to raw source when it needs to."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    assert "show_source: tool.schema" in body
    assert "offset: tool.schema" in body
    assert "limit: tool.schema" in body


def test_opencode_read_override_qname_detection_excludes_urls_and_drives(tmp_path: Path):
    """The qname detection must NOT misfire on URLs (https://...) or
    Windows drive prefixes (C:\\...). Both contain `:` but neither is a
    qname. The detection regex's purpose is to draw that boundary
    precisely; this test catches a regression in the detection rule."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    # The detection rule must explicitly check for URL schemes and Windows
    # drive prefixes. Both regexes are mentioned in `looksLikeQname`.
    assert "looksLikeQname" in body
    # URL scheme regex — `scheme://`
    assert "://" in body
    # Windows drive regex — `[A-Za-z]:[\\/]`
    assert "[A-Za-z]:" in body


def test_opencode_read_override_emits_telemetry_from_typescript(tmp_path: Path):
    """The `read.ts` wrapper handles three out of four call paths in-process
    (triefact lookup, source fallthrough, show_source escape). Only the
    qname path shells out to `trie read`, which gets `cli_call` telemetry
    for free from Python. Without TS-side emission, the other three paths
    would be invisible to `trie audit`.

    The wrapper must therefore embed its own telemetry plumbing: a helper
    that resolves the log path from trie.toml's [debug] section (or the
    TRIE_DEBUG env var), tags each call with the dispatch `mode`, and
    appends a `cli_call` JSONL event to debug.jsonl. We assert on the
    structural markers (function names, event-shape strings) rather than
    full template equality so the rendered TS can evolve."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    # Telemetry helpers must be present in the rendered TS.
    assert "emitTelemetry" in body
    assert "resolveTelemetryConfig" in body
    assert "extractTomlSection" in body
    # Event name + tool name are baked into every emit call.
    assert '"cli_call"' in body
    assert '"read"' in body
    # The `mode` field is what distinguishes the four dispatch branches.
    assert "mode" in body
    # Honours TRIE_DEBUG the same way Python does (env var wins).
    assert "TRIE_DEBUG" in body


def test_opencode_read_override_appends_telemetry_atomically(tmp_path: Path):
    """The telemetry write must use append-mode I/O (Node's `appendFile`),
    not read-modify-write. Concurrent `read` calls from a long-running
    opencode session must not race the log file. The rendered TS must
    import `appendFile` from `node:fs/promises` rather than the broader
    `writeFile` or any read-then-write pattern."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    # Single-line `appendFile` from node:fs/promises is the atomic-on-POSIX
    # write primitive we want for JSONL telemetry.
    assert "appendFile" in body
    # And we shouldn't be doing readback-then-write for the log.
    assert "readFile(cfg.logPath" not in body


def test_opencode_read_override_handles_absolute_paths(tmp_path: Path):
    """Earlier versions of `readSourceFile` did `normalize(join(cwd, path))`
    unconditionally. Node's `path.join` strips the leading slash on the
    second argument when it's absolute, producing `<cwd>/<abs-without-slash>`
    — a bogus path that ENOENTs every time. Agents do pass absolute paths
    (copy-paste from grep results, stack traces), so the wrapper must
    detect absolute paths and use them verbatim. We assert on the
    structural marker `isAbsolute(path)` being present in the resolver."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    # The resolver helper exists and branches on isAbsolute.
    assert "resolveAbsolutePath" in body
    # The resolver uses isAbsolute to skip joining onto cwd.
    assert "isAbsolute(path) ? normalize(path)" in body
    # The triefact lookup also handles absolute paths (strips cwd prefix
    # when the absolute path is inside the project tree).
    assert "projectRelativePath" in body


def test_opencode_read_override_advertises_full_arg(tmp_path: Path):
    """Compact mode is the new default for `read(path)`. The wrapper must
    advertise a `full: bool` arg so the agent can opt back into the
    historical "return the entire triefact verbatim" behaviour when it
    actually needs the whole bundle (e.g. for narrow files). Without
    this, agents would have no escape hatch from compact mode."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    assert "full: tool.schema" in body
    # Description must mention `compact` so the agent understands the
    # default behaviour.
    assert "compact" in body.lower() or "COMPACT" in body


def test_opencode_read_override_emits_compact_renderer(tmp_path: Path):
    """Compact rendering happens TS-side. The rendered wrapper must
    contain the helpers — frontmatter parser, sentinel-section scanner,
    and the renderer that ties them together. We assert on the helper
    names rather than full template equality so the rendering template
    can evolve."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    assert "renderCompact" in body
    assert "parseFrontMatter" in body
    assert "extractSections" in body
    # The compact mode and full mode each tag their telemetry differently
    # so the audit can split usage. The two mode names must appear.
    assert "triefact_compact" in body
    assert "triefact_full" in body


def test_opencode_read_override_full_mode_trims_for_agent(tmp_path: Path):
    """`full: true` used to return the raw `.md` bytes — frontmatter +
    every sentinel with its fingerprints. That's machinery noise to the
    agent. The wrapper must now route full mode through `renderForAgent`,
    which strips internal frontmatter keys (`trie_version`,
    `file_fingerprint`, `last_synced_at`, `source`) and every
    `<!-- trie:section ... -->` / `<!-- trie:end -->` sentinel before
    handing the bytes back."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".opencode" / "tools" / "read.ts").read_text()
    # Helper present.
    assert "function renderForAgent" in body
    assert "function stripSentinels" in body
    assert "function renderFrontMatterForAgent" in body
    # Full mode invokes it (and does NOT pass `triefact` verbatim).
    assert "result = renderForAgent(triefact)" in body
    # The old "result = triefact" leak must be gone for full mode.
    assert 'mode = "triefact_full"\n            result = triefact' not in body


def test_opencode_trie_read_obsolete_file_removed_on_apply(tmp_path: Path):
    """Earlier versions of `trie setup --override-builtins` shipped a
    separate `.opencode/tools/trie_read.ts` add-on. The new `read.ts`
    override subsumes it (qname-shaped paths route to `trie read`
    automatically), so re-running setup must clean up the stale file —
    otherwise the agent ends up with two tools that do the same thing."""
    # Simulate a prior install that wrote the now-obsolete trie_read.ts.
    stale_dir = tmp_path / ".opencode" / "tools"
    stale_dir.mkdir(parents=True)
    stale_path = stale_dir / "trie_read.ts"
    stale_path.write_text("// stale from a prior trie setup\n")

    plan = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    # The stale file is gone; the per-file result for the cleanup is
    # included in the plan so the user sees what migration happened.
    assert not stale_path.exists()
    cleanup_results = [f for f in result.files if f.relative_path.endswith("trie_read.ts")]
    assert len(cleanup_results) == 1
    assert cleanup_results[0].action == "updated"
    assert "removed obsolete" in cleanup_results[0].description.lower()


def test_opencode_trie_trace_obsolete_file_removed_on_apply(tmp_path: Path):
    """Earlier versions of `trie setup --override-builtins` wrote the
    trace custom tool as `.opencode/tools/trie_trace.ts` (matching what
    opencode's MCP auto-prefix would produce). The file was renamed to
    `trace.ts` so the custom-tool name matches the verb. Re-running setup
    must clean up the stale prefixed file — otherwise the agent ends up
    with two trace tools."""
    stale_dir = tmp_path / ".opencode" / "tools"
    stale_dir.mkdir(parents=True)
    stale_path = stale_dir / "trie_trace.ts"
    stale_path.write_text("// stale from a prior trie setup\n")

    plan = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    assert not stale_path.exists()
    cleanup_results = [f for f in result.files if f.relative_path.endswith("trie_trace.ts")]
    assert len(cleanup_results) == 1
    assert cleanup_results[0].action == "updated"
    assert "removed obsolete" in cleanup_results[0].description.lower()


def test_opencode_obsolete_cleanup_is_noop_on_fresh_install(tmp_path: Path):
    """A first-time install on a clean project should not error out trying
    to delete files that were never there. The cleanup step reports
    `skipped` for absent files and continues."""
    plan = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    cleanup_results = [f for f in result.files if "obsolete" in f.description.lower()]
    assert cleanup_results, "expected at least one cleanup result in the plan"
    for r in cleanup_results:
        assert r.action == "skipped"
        assert "nothing to clean up" in r.detail.lower()


# ---------------------------------------------------------------------------
# opencode: idempotency + drift
# ---------------------------------------------------------------------------


def test_opencode_install_is_idempotent_on_identical_content(tmp_path: Path):
    """Running install twice with no changes: the second run reports
    `skipped` for every file. This is what makes `trie setup` safe to run
    on every checkout."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    second = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = second.results[0]
    assert result.action == "skipped"
    # Write results report "same contents"; cleanup results for absent
    # obsolete files report "nothing to clean up". Both are `skipped`,
    # but the detail strings differ — filter by description before
    # asserting on detail.
    for f in result.files:
        assert f.action == "skipped"
        if "obsolete" not in f.description.lower():
            assert "same contents" in f.detail


def test_opencode_install_updates_on_drift(tmp_path: Path):
    """If a user hand-edits a generated file (or an older trie wrote different
    content), the next install overwrites it. Without this, a stale wrapper
    file would silently route the agent to the wrong place."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    grep_path = tmp_path / ".opencode" / "tools" / "grep.ts"
    grep_path.write_text("// stale contents from an older trie\n")

    second = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = second.results[0]
    assert result.action == "updated"
    grep_file = next(f for f in result.files if f.relative_path.endswith("grep.ts"))
    assert grep_file.action == "updated"
    # Trie-generated content is back.
    body = grep_path.read_text()
    assert "Auto-generated by `trie setup" in body


# ---------------------------------------------------------------------------
# Claude Code: single hook file
# ---------------------------------------------------------------------------


def test_claude_code_install_creates_advisory_hook(tmp_path: Path):
    """Claude Code's only available steering mechanism is a `PreToolUse`
    hook. The install writes one JSON file under `.claude/hooks/` that
    matches on the built-in `Grep` tool and emits a system message
    pointing at `mcp__trie__grep`."""
    plan = install(
        target_names=["claude-code"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    assert result.action == "created"
    hook_path = tmp_path / ".claude" / "hooks" / "trie-tools.json"
    assert hook_path.exists()
    body = json.loads(hook_path.read_text())
    # The hook is structured per Claude Code's documented schema.
    assert "hooks" in body
    pre_tool_use = body["hooks"]["PreToolUse"]
    assert isinstance(pre_tool_use, list) and len(pre_tool_use) == 1
    matcher_block = pre_tool_use[0]
    # It targets the built-in Grep tool by name (regex-free string match).
    assert matcher_block["matcher"] == "Grep"
    # And the handler runs a shell command that emits a systemMessage —
    # the only documented way to inject text Claude sees on next turn.
    cmd = matcher_block["hooks"][0]["command"]
    assert "systemMessage" in cmd
    assert "mcp__trie__grep" in cmd


def test_claude_code_hook_does_not_deny_grep(tmp_path: Path):
    """Per design: Claude Code's hook is advisory only, not blocking. The
    rendered command must NOT produce a `permissionDecision: deny` because
    we don't want to break legitimate Grep usage on non-source files. If a
    future change accidentally turns this into a deny rule, the test
    fails loudly."""
    install(
        target_names=["claude-code"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    body = (tmp_path / ".claude" / "hooks" / "trie-tools.json").read_text()
    assert "permissionDecision" not in body
    assert '"deny"' not in body


# ---------------------------------------------------------------------------
# Other harnesses: needs_manual_setup
# ---------------------------------------------------------------------------


@pytest.mark.parametrize(
    "slug",
    ["claude-desktop", "cursor", "windsurf", "vscode", "codex"],
)
def test_unsupported_harnesses_emit_needs_manual_setup(tmp_path: Path, slug: str):
    """Harnesses with no documented tool-override mechanism emit a
    `needs_manual_setup` result carrying the manual instructions, and
    write no files. The user gets honest signal that automation isn't
    possible here instead of a silent skip."""
    plan = install(
        target_names=[slug],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    assert result.target == slug
    assert result.action == "needs_manual_setup"
    assert result.detail  # carries the manual_instructions text
    assert result.files == []
    # Nothing landed on disk.
    assert not (tmp_path / ".opencode").exists()
    assert not (tmp_path / ".claude").exists()


# ---------------------------------------------------------------------------
# Multi-target apply
# ---------------------------------------------------------------------------


def test_install_for_opencode_and_claude_code_in_one_pass(tmp_path: Path):
    """A common shape for users running both harnesses: a single
    `install(target_names=["opencode", "claude-code"], ...)` lands every
    target's files in one pass. The per-target results are independent —
    a failure on one wouldn't roll back the other."""
    plan = install(
        target_names=["opencode", "claude-code"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    assert {r.target for r in plan.results} == {"opencode", "claude-code"}
    assert (tmp_path / ".opencode" / "tools" / "grep.ts").exists()
    assert (tmp_path / ".claude" / "hooks" / "trie-tools.json").exists()


# ---------------------------------------------------------------------------
# Preview / dry-run: never write
# ---------------------------------------------------------------------------


def test_print_only_does_not_write_anything(tmp_path: Path):
    """`--print-only` is for inspecting the plan; nothing lands on disk.
    Each file-to-write result is `preview` and carries the would-be
    contents in `detail` for the renderer to print. Obsolete-file
    cleanups for files that don't exist report `skipped` regardless of
    --print-only because there's nothing to preview removing."""
    plan = install(
        target_names=["opencode"],
        print_only=True,
        dry_run=False,
        project_root=tmp_path,
    )
    result = plan.results[0]
    assert result.action == "preview"
    assert not (tmp_path / ".opencode").exists()
    # The new-file write results are all `preview` with rendered contents
    # in `detail`. Cleanup-of-non-existent results are `skipped` (no body
    # to render). Filter by description to separate the two cohorts.
    write_results = [f for f in result.files if "obsolete" not in f.description.lower()]
    for f in write_results:
        assert f.action == "preview"
        assert f.detail  # the rendered file body


def test_dry_run_does_not_write_when_file_already_correct(tmp_path: Path):
    """`--dry-run` short-circuits before writing. If the file on disk
    matches what we'd write, we still report `skipped` (no work to do);
    if it doesn't match, we return `preview` without writing.

    This mirrors the existing hook-install + docs-install dry-run
    contracts so all three subcommands feel consistent."""
    install(
        target_names=["opencode"],
        print_only=False,
        dry_run=False,
        project_root=tmp_path,
    )
    second = install(
        target_names=["opencode"],
        print_only=False,
        dry_run=True,
        project_root=tmp_path,
    )
    # Already up to date, so even dry-run reports `skipped`.
    assert second.results[0].action == "skipped"


# ---------------------------------------------------------------------------
# Error handling
# ---------------------------------------------------------------------------


def test_install_with_empty_target_names_raises(tmp_path: Path):
    """Calling install with no targets is a programming error from the
    caller (CLI should have caught it earlier). Better to fail loudly than
    silently write nothing."""
    with pytest.raises(ToolOverrideInstallError):
        install(target_names=[], print_only=False, dry_run=False, project_root=tmp_path)
    with pytest.raises(ToolOverrideInstallError):
        install(target_names=None, print_only=False, dry_run=False, project_root=tmp_path)


def test_install_with_unknown_target_raises(tmp_path: Path):
    """A typo'd or made-up target name is a usage error worth surfacing.
    The error message should name the valid options so the user can fix
    the typo without re-checking the docs."""
    with pytest.raises(ToolOverrideInstallError) as excinfo:
        install(
            target_names=["totally-made-up-harness"],
            print_only=False,
            dry_run=False,
            project_root=tmp_path,
        )
    msg = str(excinfo.value)
    assert "totally-made-up-harness" in msg
    # The error must list at least one known harness so the fix is obvious.
    assert "opencode" in msg or "claude-code" in msg


def test_apply_one_uses_needs_manual_setup_for_targets_with_no_files():
    """Direct test of `apply_one` against a target whose `files` tuple is
    empty (i.e. a harness with only manual_instructions). The function
    returns `needs_manual_setup` without touching disk — same contract as
    `hook_install.apply_one` for the same shape of target."""
    target = TARGETS["cursor"]
    result = apply_one(target, project_root=Path("/tmp"), print_only=False, dry_run=False)
    assert result.action == "needs_manual_setup"
    assert result.detail
    assert result.files == []


def test_rendered_tools_relay_both_streams_on_failure(tmp_path: Path):
    """Regression: failure messages used `stderr || stdout` (either/or), so
    anything the CLI printed to stdout alongside a stderr error — e.g. the
    did-you-mean qname suggestions — was silently dropped by every tool
    wrapper. The templates must join both streams."""
    from trie.tool_override_install import TARGETS

    spec = TARGETS["opencode"]
    rendered = [f.render(tmp_path) for f in spec.files if f.relative_path[-1].endswith(".ts")]
    assert rendered, "expected rendered .ts tool files"
    joined = "\n".join(rendered)
    assert "stderr.trim() || stdout.trim()" not in joined
    assert "[stderr.trim(), stdout.trim()].filter(Boolean).join" in joined


# ---------------------------------------------------------------------------
# Parse guard: every rendered `.ts` override must be valid JavaScript/TypeScript.
#
# These templates are authored as Python string literals, which makes a single
# mis-escaped `\n` invisible: it turns into a raw newline in the generated JS
# and produces an unterminated string literal. opencode's plugin loader then
# fails to load the *entire* `.opencode/tools/` directory, and every message
# send dies with an "unexpected server error" — the coding agent is bricked
# with no obvious cause. This guard renders each override and rejects any that
# won't parse, so that class of footgun can never ship again.
# ---------------------------------------------------------------------------


# Significant chars after which a `/` begins a regex literal rather than a
# division operator. Punctuation-only (no keyword handling) — sufficient and
# false-positive-free for the generated overrides, which contain regex literals
# only after `=`/`(` and no division at all.
_REGEX_START_CHARS = frozenset("(,=:[!&|?{;")


def _first_raw_newline_in_quoted_string(source: str) -> tuple[int, str] | None:
    """Scan JS source for a raw newline inside a single/double-quoted string.

    Returns `(line_number, snippet)` for the first offending string, or `None`
    if every `'...'` / `"..."` string is properly terminated on its own line.

    This is the exact bug that `.join("\\n")` mis-escaped as `.join("<newline>")`
    produces: a quoted string literal broken across a line boundary, which JS
    forbids (only backtick template literals may span newlines). We hand-roll a
    minimal lexer rather than depend on a JS runtime so the guard runs in every
    environment, including CI without node/bun.

    The scanner tracks these lexical states — normal code, `//` line comment,
    `/* */` block comment, `/regex/` literals, backtick template literals, and
    the two quoted-string kinds — honouring backslash escapes so an escaped
    quote (`\\"`) or escaped newline doesn't confuse it. Crucially it descends
    into `${...}` interpolations inside template literals and scans them as
    code, because the real bug lives *inside* an interpolation:
    `join("<newline>")` sits in a `${...}` of a backtick string. A scanner that
    treated backtick literals as opaque would miss it entirely.

    Backtick literals may span newlines (legal in JS); only `'`/`"` strings are
    checked for the illegal raw-newline case. Regex literals are consumed whole
    (a `/` is a regex start only when the previous significant char can't end an
    expression, e.g. after `(`, `=`, `[`) so a quote inside `/["']/` isn't
    mistaken for a string.

    Implementation: a context stack. Each frame is either `("code", brace_depth)`
    — top level or the interior of a `${...}` interpolation, tracking `{`/`}`
    nesting so a literal brace doesn't close the interpolation early — or
    `("tmpl",)` for the body of a template literal between interpolations.
    """
    i = 0
    n = len(source)
    line = 1
    prev_sig = ""  # last significant char in the current code context
    # Stack of contexts; bottom frame is the top-level code.
    stack: list = [["code", 0]]

    def _consume_regex(idx: int, ln: int) -> tuple[int, int]:
        idx += 1
        in_class = False
        while idx < n:
            c = source[idx]
            if c == "\\":
                idx += 2
                continue
            if c == "\n":
                ln += 1
                idx += 1
                continue
            if c == "[":
                in_class = True
            elif c == "]":
                in_class = False
            elif c == "/" and not in_class:
                idx += 1
                break
            idx += 1
        return idx, ln

    while i < n:
        ctx = stack[-1]
        ch = source[i]

        # ---- template-literal body: consume until backtick or `${` ----
        if ctx[0] == "tmpl":
            if ch == "\\":
                if i + 1 < n and source[i + 1] == "\n":
                    line += 1
                i += 2
                continue
            if ch == "\n":
                line += 1
                i += 1
                continue
            if ch == "`":
                stack.pop()
                prev_sig = "`"
                i += 1
                continue
            if ch == "$" and i + 1 < n and source[i + 1] == "{":
                stack.append(["code", 0])  # enter interpolation as code
                prev_sig = "{"
                i += 2
                continue
            i += 1
            continue

        # ---- code context (top level or inside `${...}`) ----
        if ch == "\n":
            line += 1
            i += 1
            continue
        if ch in (" ", "\t", "\r"):
            i += 1
            continue
        if ch == "/" and i + 1 < n and source[i + 1] == "/":
            while i < n and source[i] != "\n":
                i += 1
            continue
        if ch == "/" and i + 1 < n and source[i + 1] == "*":
            i += 2
            while i + 1 < n and not (source[i] == "*" and source[i + 1] == "/"):
                if source[i] == "\n":
                    line += 1
                i += 1
            i += 2
            continue
        if ch == "/" and prev_sig in _REGEX_START_CHARS:
            i, line = _consume_regex(i, line)
            prev_sig = "/"
            continue
        if ch == "`":
            stack.append(["tmpl"])
            i += 1
            continue
        if ch in ("'", '"'):
            quote = ch
            open_line = line
            snippet_start = max(0, i - 20)
            i += 1
            while i < n:
                c = source[i]
                if c == "\\":
                    if i + 1 < n and source[i + 1] == "\n":
                        line += 1
                    i += 2
                    continue
                if c == "\n":
                    snippet = source[snippet_start:i].replace("\n", "\\n")
                    return open_line, snippet
                if c == quote:
                    i += 1
                    break
                i += 1
            prev_sig = quote
            continue
        if ch == "{":
            ctx[1] += 1
            prev_sig = ch
            i += 1
            continue
        if ch == "}":
            if ctx[1] == 0 and len(stack) > 1:
                # Close of a `${...}` interpolation: pop back to template body.
                stack.pop()
                i += 1
                continue
            if ctx[1] > 0:
                ctx[1] -= 1
            prev_sig = ch
            i += 1
            continue
        prev_sig = ch
        i += 1
    return None


def _rendered_opencode_ts_files(project_root: Path) -> dict[str, str]:
    """Render every opencode `.ts` override, keyed by its filename."""
    spec = TARGETS["opencode"]
    return {
        f.relative_path[-1]: f.render(project_root)
        for f in spec.files
        if f.relative_path[-1].endswith(".ts")
    }


def test_rendered_ts_overrides_have_no_unterminated_string_literals(tmp_path: Path):
    """Every rendered `.ts` override must have no raw newline inside a quoted
    string. Hermetic guard for the `.join("\\n")` footgun (an unescaped `\\n`
    in the Python template becomes a real newline, breaking the JS string and
    bricking opencode's plugin loader). Runs everywhere, no JS runtime needed."""
    rendered = _rendered_opencode_ts_files(tmp_path)
    assert rendered, "expected rendered .ts tool files"

    offenders = {}
    for name, source in rendered.items():
        hit = _first_raw_newline_in_quoted_string(source)
        if hit is not None:
            offenders[name] = hit

    assert not offenders, (
        "rendered opencode overrides contain unterminated string literals "
        "(a raw newline inside a '...'/\"...\" string — most likely a `\\n` in "
        "the Python template that should be `\\\\n`). opencode fails to load the "
        "whole tools dir when this ships. Offending files (line, snippet): "
        + "; ".join(f"{k}: line {v[0]} …{v[1]!r}" for k, v in offenders.items())
    )


def test_scanner_flags_a_known_unterminated_string_literal():
    """Guard the guard: the scanner must actually catch a raw newline inside a
    double-quoted string, and must NOT false-positive on a legal `\\n` escape,
    on a newline inside a backtick template, or on a quote inside a comment."""
    bad = 'const x = "abc\ndef"'
    assert _first_raw_newline_in_quoted_string(bad) is not None

    good_escape = 'const x = "abc\\ndef"\n'
    assert _first_raw_newline_in_quoted_string(good_escape) is None

    good_template = "const x = `abc\ndef`\n"
    assert _first_raw_newline_in_quoted_string(good_template) is None

    good_comment = "// a lone ' quote in a comment\nconst x = 1\n"
    assert _first_raw_newline_in_quoted_string(good_comment) is None

    # The exact shape of the real regression: a broken quoted string living
    # *inside* a `${...}` interpolation of a template literal. The scanner must
    # descend into interpolations, not treat backtick literals as opaque.
    interp_bug = 'throw new Error(`x ${[a].join("\n") || "y"}`)\n'
    assert _first_raw_newline_in_quoted_string(interp_bug) is not None
    interp_ok = 'throw new Error(`x ${[a].join("\\n") || "y"}`)\n'
    assert _first_raw_newline_in_quoted_string(interp_ok) is None

    # A regex literal containing quotes must not be mistaken for a string.
    regex_ok = "const m = /^[\"']+$/.exec(raw)\n"
    assert _first_raw_newline_in_quoted_string(regex_ok) is None


@pytest.mark.parametrize("runtime", ["bun"])
def test_rendered_ts_overrides_parse_under_js_runtime(tmp_path: Path, runtime: str):
    """Authoritative parse check: when a TypeScript-aware JS runtime is on PATH,
    every rendered override must parse cleanly. `bun build` strips types and
    reports real syntax errors (unlike `node --check`, which rejects TS type
    annotations). Skipped when the runtime is unavailable so the suite stays
    hermetic; the pure-Python guard above always runs regardless."""
    import shutil
    import subprocess

    exe = shutil.which(runtime)
    if not exe:
        pytest.skip(f"{runtime} not on PATH; pure-Python guard still covers this")
    assert exe is not None

    rendered = _rendered_opencode_ts_files(tmp_path)
    tools_dir = tmp_path / ".opencode" / "tools"
    tools_dir.mkdir(parents=True, exist_ok=True)
    # Stub the plugin import so parsing doesn't require a network install.
    stub_dir = tmp_path / "node_modules" / "@opencode-ai" / "plugin"
    stub_dir.mkdir(parents=True, exist_ok=True)
    (stub_dir / "package.json").write_text(
        json.dumps({"name": "@opencode-ai/plugin", "version": "0.0.0", "main": "index.js"})
    )
    (stub_dir / "index.js").write_text(
        "const s = new Proxy(function(){}, { get: () => s, apply: () => s });\n"
        "function tool(d){ return d; } tool.schema = s;\n"
        "module.exports = { tool };\n"
    )

    failures = {}
    for name, source in rendered.items():
        path = tools_dir / name
        path.write_text(source)
        proc = subprocess.run(
            [exe, "build", str(path), "--target=node"],
            capture_output=True,
            text=True,
            cwd=str(tmp_path),
        )
        if proc.returncode != 0:
            failures[name] = proc.stderr.strip() or proc.stdout.strip()

    assert not failures, "rendered overrides failed to parse:\n" + "\n".join(
        f"--- {k} ---\n{v}" for k, v in failures.items()
    )
